resources:
- name: 15m
  type: time
  source: {interval: 15m}
- name: 1h
  type: time
  source: {interval: 1h}
- name: daily
  type: time
  source:
    start: 8:00 PM
    stop: 9:00 PM
    location: America/Denver
- name: loggregator-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
- name: loggregator
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-release
    branch: develop

jobs:
- name: restage-logspinners
  public: false
  serial: true
  serial_groups: ["restage"]
  plan:
  - get: daily
    trigger: true
  - get: loggregator-ci
  - task: restage-logspinner
    file: loggregator-ci/tasks/restage-apps.yml
    params:
      APP_NAMES: "floodspinner dripspinner flowspinner"
      CF_API: "api.ng.bluemix.net"
      ORG: "Cloud Foundry Flintstone"
      PASSWORD: {{bluemix-password}}
      SPACE: loggregator
      USERNAME: {{bluemix-username}}

- name: floodspinner
  public: false
  serial: true
  serial_groups: ["restage"]
  plan:
  - get: loggregator-ci
  - get: 15m
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/blackbox/app.yml
    params:
      CYCLES: 10000
      DELAY: "2"
      DELAY_UNIT: "us"
      MESSAGE: "FIFTEEN-MINUTE"
      APP_NAME: "floodspinner"
      WAIT: 300
      USERNAME: {{bluemix-username}}
      PASSWORD: {{bluemix-password}}
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      CF_API: "api.ng.bluemix.net"
      APP_DOMAIN: "floodspinner.mybluemix.net"
      ORG: "Cloud Foundry Flintstone"
      SPACE: loggregator
    timeout: 15m
  - task: run-recent-logs-smoke-tests
    file: loggregator-ci/tasks/generic-recent-logs-smoke-test.yml
    params: &basic-smoke-details
      APP_NAME: "floodspinner"
      CF_API: "api.ng.bluemix.net"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      LOGGREGATOR_ADDR: "wss://doppler.ng.bluemix.net:443"
      ORG: "Cloud Foundry Flintstone"
      PASSWORD: {{bluemix-password}}
      SPACE: loggregator
      USERNAME: {{bluemix-username}}
    timeout: 15m
  - task: container metrics
    file: loggregator-ci/tasks/container-metrics-smoke-test.yml
    params: *basic-smoke-details
    timeout: 15m

- name: dripspinner
  public: false
  serial: true
  serial_groups: ["restage"]
  plan:
  - get: loggregator-ci
  - get: 1h
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/blackbox/app.yml
    params:
      CYCLES: 1000
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
      APP_NAME: "dripspinner"
      WAIT: 600
      USERNAME: {{bluemix-username}}
      PASSWORD: {{bluemix-password}}
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      CF_API: "api.ng.bluemix.net"
      APP_DOMAIN: "dripspinner.mybluemix.net"
      ORG: "Cloud Foundry Flintstone"
      SPACE: loggregator
    timeout: 15m

- name: flowspinner
  public: false
  serial: true
  serial_groups: ["restage"]
  plan:
  - get: loggregator-ci
  - get: 1h
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/blackbox/app.yml
    params:
      CYCLES: 1000
      DELAY: "1"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
      APP_NAME: "flowspinner"
      WAIT: 60
      USERNAME: {{bluemix-username}}
      PASSWORD: {{bluemix-password}}
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      CF_API: "api.ng.bluemix.net"
      APP_DOMAIN: "flowspinner.mybluemix.net"
      ORG: "Cloud Foundry Flintstone"
      SPACE: loggregator
    timeout: 15m

- name: latency
  public: false
  serial: true
  plan:
  - get: loggregator
  - get: loggregator-ci
  - get: 15m
    trigger: true
  - task: run-latency-tests
    file: loggregator-ci/tasks/latency-test.yml
    params:
      APP_DOMAIN: "loggregator-latency.mybluemix.net"
      APP_NAME: "loggregator-latency"
      CF_API: "api.ng.bluemix.net"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      ORG: "Cloud Foundry Flintstone"
      SPACE: loggregator
      USERNAME: {{bluemix-username}}
      PASSWORD: {{bluemix-password}}
    timeout: 15m
