resources:

- name: base-image
  type: docker-image
  source:
    repository: loggregator/base
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: base-image-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/base

- name: golang-1.8-tarball
  type: s3
  source:
    endpoint: storage.googleapis.com
    bucket: golang
    regexp: 'go(1\.8(\.\d+)?)\.linux-amd64\.tar.gz'

- name: bosh10-image-dockerfile
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/bosh10

- name: bosh10-image
  type: docker-image
  source:
    repository: loggregator/bosh10
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:
- name: build-base-image
  public: true
  plan:
  - aggregate:
    - get: golang-1.8-tarball
      trigger: true
    - get: image-dockerfile
      resource: base-image-dockerfile
      trigger: true
  - task: prepare-image-build
    config:
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: latest
      platform: linux
      inputs:
      - name: image-dockerfile
      outputs:
      - name: build-image
      params:
        IMAGE_NAME: base
      run:
        path: bash
        args:
        - -c
        - {{prepare-docker-image}}
  - put: base-image
    params:
      build: build-image/build
      tag: build-image/tag
      tag_as_latest: true
      cache_tag: latest

- name: bosh10
  plan:
    - get: bosh10-image-dockerfile
      trigger: true
    - put: bosh10-image
      params:
        build: bosh10-image-dockerfile/docker-images/bosh10
        tag_as_latest: true
        cache_tag: latest
