resources:
- name: datadog-firehose-nozzle-release-repo
  type: git
  source:
    uri: https://github.com/DataDog/datadog-firehose-nozzle-release
    branch: master

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

- name: datadog-firehose-nozzle-release
  type: bosh-io-release
  source:
    repository: DataDog/datadog-firehose-nozzle-release
    version: 63

jobs:
- name: deploy
  serial: true
  plan:
  - aggregate:
    - get: deployments-loggregator
    - get: datadog-firehose-nozzle-release
    - get: datadog-firehose-nozzle-release-repo
  - task: deploy
    config:
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
      platform: linux
      inputs:
      - name: deployments-loggregator
      - name: datadog-firehose-nozzle-release
      - name: datadog-firehose-nozzle-release-repo
      params:
        MANIFEST_FILE: datadog-firehose-nozzle-release-repo/templates/datadog-bosh2.yml
        MANIFEST_VARS: deployments-loggregator/gcp/coconut/datadog-vars.yml
        DEPLOYMENT_NAME: datadog
      run:
        path: bash
        args:
          - -c
          - |
            #!/bin/bash

            set -e -x

            source ~/.bashrc

            pushd deployments-loggregator/gcp/bbl
              export BOSH_CLIENT=`bbl director-username`
              export BOSH_CLIENT_SECRET=`bbl director-password`
              export BOSH_CA_CERT=`bbl director-ca-cert`
              export BOSH_ENVIRONMENT=`bbl director-address`
            popd

            bosh -n upload-release datadog-firehose-nozzle-release/*.tgz
            bosh -n -d ${DEPLOYMENT_NAME} deploy ${MANIFEST_FILE} \
              -o deployments-loggregator/gcp/bbl/ops-files/datadog/metric-prefix.yml \
              -l ${MANIFEST_VARS}
