resources:
- name: loggregator-tools
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/loggregator-tools

jobs:
- name: run-tests
  public: true
  plan:
  - get: loggregator-tools
    resource: loggregator-tools
    trigger: true
  - task: run-tests
    timeout: 5m
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: loggregator/base
      inputs:
      - name: loggregator-tools
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -ex

          mkdir -p workspace/src/code.cloudfoundry.org/
          cp -r loggregator-tools workspace/src/code.cloudfoundry.org/loggregator-tools
          cd workspace

          export GOPATH=`pwd`
          export TERM=xterm

          cd src/code.cloudfoundry.org/loggregator-tools/

          go version
          go get -d -t ./...
          go get github.com/onsi/ginkgo/ginkgo

          go test ./... --race
