image_resource:
  type: docker-image
  source:
    repository: loggregator/base

platform: linux

params:
  VERSION_MAJOR:
  VERSION_MINOR:
  VERSION_PATCH:

inputs:
- name: noisy-neighbor-nozzle-repo

outputs:
- name: binary-output
- name: github-release
- name: repo-output

run:
  path: loggregator-ci/tasks/noisy-neighbor-create-binaries/task