platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
inputs:
- name: loggregator
params:
  DATADOG_APP_KEY:
run:
  path: bash
  args:
  - -c
  - |
    #/bin/bash
    set -ex

    pushd loggregator
      SHA=$(git rev-parse HEAD)
    popd

    EVENT_TITLE="Staging deployed SHA: $(echo "$SHA" | cut -c 1-5)"
    echo "EVENT_TITLE: $EVENT_TITLE"

    cat <<EOF >> /tmp/request-body.json
    {
      "title": "$EVENT_TITLE",
      "text": "$EVENT_TITLE",
      "tags": [
        "sha:$SHA"
      ]
    }
    EOF

    curl "https://app.datadoghq.com/api/v1/events?application_key=${DATADOG_APP_KEY}" \
      -X POST \
      -H "Content-type: application/json" \
      -d "@/tmp/request-body.json"
