platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
params:
  SYSTEM_DOMAIN:
  VARS_STORE_FILE:
  ORG:
  SPACE:
inputs:
- name: vars-store
- name: loggregator-tools
run:
  path: bash
  args:
  - -c
  - |
    #!/bin/bash
    set -ex
    password=$(bosh int vars-store/$VARS_STORE_FILE --path=/cf_admin_password)

    cf login -a api.$SYSTEM_DOMAIN -u admin -p $password -o system --skip-ssl-validation

    set +e
    cf org $ORG
    set -e
    if [ $? -eq 0 ]; then
      cf create-org $ORG
    fi
    cf target -o $ORG

    set +e
    cf space $SPACE
    set -e
    if [ $? -eq 0 ]; then
      cf create-space $SPACE
    fi
    cf target -s $SPACE
    cf create-shared-domain tcp.$SYSTEM_DOMAIN --router-group default-tcp || true

    pushd loggregator-tools/jsonspinner
      cf push floodspinner
    popd
