---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci # - This repo
- name: bbl-state

outputs:
- name: cats-config

run:
  path: loggregator-ci/tasks/generate-cats-config/task

params:
  BBL_STATE_DIR:
  SYSTEM_DOMAIN:
