#!/usr/bin/env bash
set -e

source loggregator-ci/scripts/environment-targeting/target-cf.sh
CF_ADMIN_PASSWORD=$(cf-password-from-credhub)

cat <<EOT >> cats-config/cats-config.json
{
	"api": "api.${SYSTEM_DOMAIN}",
	"admin_user": "admin",
	"admin_password": "${CF_ADMIN_PASSWORD}",
	"apps_domain": "${SYSTEM_DOMAIN}",
	"skip_ssl_validation": false,
	"use_http": true,
	"backend": "diego",
	"include_apps": true,
	"include_backend_compatibility": true,
	"include_container_networking": true,
	"include_detect": true,
	"include_docker": true,
	"include_internet_dependent": true,
	"include_privileged_container_support": false,
	"include_route_services": true,
	"include_routing": true,
	"include_security_groups": true,
	"include_services": true,
	"include_ssh": true,
	"include_sso": true,
	"include_tasks": true,
	"include_v3": true,
	"include_zipkin": false,
	"include_capi_experimental": false,
	"include_credhub": false,
	"include_isolation_segments": false,
	"include_routing_isolation_segments": false,
	"include_private_docker_registry": false,
	"isolation_segment_name": "persistent_isolation_segment"
}
EOT