---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci          # - This repo
- name: deployments-loggregator # - Needed to have kubectl target env

run:
  path: loggregator-ci/tasks/k8s-log-cache-blackbox/task

params:
  # - Required
  # - The API Key to send metrics to DataDog.
  DATADOG_API_KEY:

  # - Optional
  # - Skip SSL validation when logging into CF.
  SKIP_SSL_VALIDATION: false
