#!/bin/bash

set -ex

function fail_on_empty {
    if [ "$1" = "" ]; then
        exit 1
    fi
}

function teardown {
    killall kubectl
    killall ssh
    killall ssh-agent
}
trap teardown EXIT

eval "$(ssh-agent)"

pushd deployments-loggregator/gcp/playground
    source .envrc
    set +e
    source k8s_login
    set -e
    echo "
apiVersion: v1
kind: Namespace
metadata:
  name: blackbox-tests
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: log-cache-blackbox
  namespace: blackbox-tests
  labels:
    run: log-cache-blackbox
spec:
  replicas: 1
  selector:
    matchLabels:
      run: log-cache-blackbox
  template:
    metadata:
      labels:
        run: log-cache-blackbox
    spec:
      containers:
      - name: log-cache-blackbox
        image: loggregator/log-cache-blackbox
        env:
        - name: LOG_CACHE_URL
          value: http://log-cache-reads.loggregator.svc.cluster.local:8081
        - name: SOURCE_ID
          value: "blackbox-tests/deployment/log-cache-blackbox"
        - name: PORT
          value: \"12345\"
        - name: SKIP_SSL_VALIDATION
          value: \"$SKIP_SSL_VALIDATION\"
---
apiVersion: v1
kind: Service
metadata:
  name: log-cache-blackbox
  namespace: blackbox-tests
  labels:
    run: log-cache-blackbox
spec:
  selector:
    run: log-cache-blackbox
  type: LoadBalancer
  ports:
  - port: 12345
    protocol: TCP
" | kubectl apply -f -

    # Setup portforwarding to each log-cache's health port
    kubectl -n loggregator port-forward log-cache-0 6060:6060 > /dev/null &
    kubectl -n loggregator port-forward log-cache-1 6061:6060 > /dev/null &
    kubectl -n loggregator port-forward log-cache-2 6062:6060 > /dev/null &
    sleep 3
popd

while true; do
  ip="$(
    kubectl get service log-cache-blackbox \
        --output=json \
        --namespace blackbox-tests | \
      jq --raw-output .status.loadBalancer.ingress[0].ip
  )"
  if [ "$ip" != "" ] && [ "$ip" != "null" ]; then
    echo "Retrieved the log-cache-blackbox IP: $ip"
    break
  fi
  sleep 10
done

response="$(curl -X POST "$ip:12345")"
latency="$(echo "$response" | jq .latency)"
avg_query_time="$(echo "$response" | jq .averageQueryTime)"

fail_on_empty "$latency"
fail_on_empty "$avg_query_time"

response="$(curl -X POST "$ip:12345/reliability")"
logs_sent="$(echo "$response" | jq .logsSent)"
logs_received="$(echo "$response" | jq .logsReceived)"
fail=false
if [ "$logs_received" -lt 9900 ]; then
    fail=true
fi

fail_on_empty "$logs_received"

cache_period_0="$(curl -s localhost:6060/debug/vars | jq --raw-output .LogCache.CachePeriod)"
cache_period_1="$(curl -s localhost:6061/debug/vars | jq --raw-output .LogCache.CachePeriod)"
cache_period_2="$(curl -s localhost:6062/debug/vars | jq --raw-output .LogCache.CachePeriod)"
cache_period_avg="$(python -c "print ($cache_period_0 + $cache_period_1 + $cache_period_2) / 3.0")"

currenttime="$(date +%s)"
SYSTEM_DOMAIN=k8s-playground
APP_NAME=k8s-playground-log-cache-blackbox
curl --fail -X POST -H "Content-type: application/json" \
-d "{ \"series\" :
  [
    {
      \"metric\":\"log-cache-blackbox.k8s_cache_duration\",
      \"points\":[[${currenttime}, ${cache_period_avg}]],
      \"type\":\"gauge\",
      \"host\":\"${SYSTEM_DOMAIN}\",
      \"tags\":[\"${APP_NAME}\"]
    },
    {
      \"metric\":\"log-cache-blackbox.k8s_latency\",
      \"points\":[[${currenttime}, ${latency}]],
      \"type\":\"gauge\",
      \"host\":\"${SYSTEM_DOMAIN}\",
      \"tags\":[\"${APP_NAME}\"]
    },
    {
      \"metric\":\"log-cache-blackbox.k8s_avg_query_time\",
      \"points\":[[${currenttime}, ${avg_query_time}]],
      \"type\":\"gauge\",
      \"host\":\"${SYSTEM_DOMAIN}\",
      \"tags\":[\"${APP_NAME}\"]
    },
    {
      \"metric\":\"log-cache-blackbox.k8s_logs_sent\",
      \"points\":[[${currenttime}, ${logs_sent}]],
      \"type\":\"gauge\",
      \"host\":\"${SYSTEM_DOMAIN}\",
      \"tags\":[\"${APP_NAME}\"]
    },
    {
      \"metric\":\"log-cache-blackbox.k8s_logs_received\",
      \"points\":[[${currenttime}, ${logs_received}]],
      \"type\":\"gauge\",
      \"host\":\"${SYSTEM_DOMAIN}\",
      \"tags\":[\"${APP_NAME}\"]
    }
  ]
}" \
'https://app.datadoghq.com/api/v1/series?api_key='"$DATADOG_API_KEY"

if [ "$fail" = true ]; then
    echo the reliability test did not meet our SLO
    exit 123
fi
