platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: deployments-loggregator
- name: loggregator-ci
- name: bbl-state

outputs:
- name: ops-files
- name: vars-files

run:
  path: loggregator-ci/tasks/prepare-service-metrics-ops-and-vars/task

params:
  ENV_NAME:
  BBL_STATE_DIR:
