---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci # - This repo
- name: cfar-logging-acceptance-tests
- name: cf-drain-cli

run:
  path: loggregator-ci/tasks/cfar-lats/task

params:
  # - Required
  # - Username to use to login to cloud foundry.
  CF_ADMIN_USER:

  # - Required
  # - The password to use to login to cloud foundry.
  CF_ADMIN_PASSWORD:

  # - Required
  # - The cloud foundry system domain.
  CF_DOMAIN:

  # - Optional
  # - Whether to disable SSL validation.
  SKIP_SSL_VALIDATION: false
