---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci # - This repo
- name: cfar-logging-acceptance-tests

run:
  path: loggregator-ci/tasks/cfar-lats/task

params:
  # - Required
  # - Username to use to login to cloud foundry.
  USERNAME:

  # - Required
  # - The password to use to login to cloud foundry.
  PASSWORD:

  # - Required
  # - The cloud foundry API endpoint.
  API_ENDPOINT:

  # - Optional
  # - Whether to disable SSL validation.
  SKIP_SSL_VALIDATION: false
