---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci # - This repo
- name: cfar-logging-acceptance-tests
- name: cf-drain-cli
- name: log-stream-cli
- name: bbl-state
  optional: true

run:
  path: loggregator-ci/tasks/cfar-lats/task

params:
  # - Required
  # - Username to use to login to cloud foundry.
  CF_ADMIN_USER:

  # - Optional
  # - The password to use to login to cloud foundry.
  CF_ADMIN_PASSWORD:

  # - Optional
  # - The path relative to bbl-state that stores bbl environment information.
  BBL_STATE_DIR:

  # - Required
  # - The cloud foundry system domain.
  CF_DOMAIN:

  # - Optional
  # - Whether to disable SSL validation.
  SKIP_SSL_VALIDATION: false

  # - Optional
  # - App push timeout
  APP_PUSH_TIMEOUT: 180s
