#!/usr/bin/env bash

set -e

mkdir -p $GOPATH/src/github.com/cloudfoundry
mkdir -p $GOPATH/src/code.cloudfoundry.org

cp -R cfar-logging-acceptance-tests $GOPATH/src/github.com/cloudfoundry
cp -R cf-drain-cli $GOPATH/src/code.cloudfoundry.org
cp -R log-stream-cli $GOPATH/src/github.com/cloudfoundry


pushd $GOPATH/src/code.cloudfoundry.org/cf-drain-cli
    go get ./...
popd

pushd $GOPATH/src/code.cloudfoundry.org/cf-drain-cli/cmd/cf-drain-cli
    go build
    cf install-plugin -f cf-drain-cli
popd

pushd $GOPATH/src/github.com/cloudfoundry/log-stream-cli
    go get ./...
popd

pushd $GOPATH/src/github.com/cloudfoundry/log-stream-cli/cmd/log_stream
    go build
    cf install-plugin -f log-stream
popd

pushd $GOPATH/src/github.com/cloudfoundry/cfar-logging-acceptance-tests
  go get -t ./...
  go install github.com/onsi/ginkgo/ginkgo
  ginkgo -r -race -flakeAttempts=2
popd
