#!/usr/bin/env bash

set -e

export BBL_STATE_DIR=$(cat environment/metadata)
export BBL_ENV_NAME=$(cat environment/name)

workspace=$PWD

cat <<EOT >> add-director-access.yml
- type: replace
  path: /vm_extensions/-
  value:
    cloud_properties:
        tags:
        - $BBL_ENV_NAME-bosh-open
    name: access-director
EOT

pushd bbl-state/$BBL_STATE_DIR
    eval "$(bbl print-env)"
    bosh update-cloud-config $workspace/add-director-access.yml
popd
