---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.20.0

inputs:
- name: loggregator-ci # - This repo
- name: bbl-state
- name: environment

run:
  path: loggregator-ci/tasks/allow-director-access/task
