platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci

run:
  path: loggregator-ci/tasks/blackbox/ensure-drain/task

params:
  EMITTER_NAME:
  DRAIN_NAME:
  DRAIN_URL:
  CF_API:
  ORG:
  PASSWORD:
  SPACE:
  USERNAME:
  USE_CLIENT_AUTH:
