platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
inputs:
- name: loggregator-tools
params:
  CF_SYSTEM_DOMAIN:
  CF_USERNAME:
  CF_PASSWORD:
  CF_SPACE:
  CF_ORG:
  CYCLES: 10000
  DELAY_US: 100
  DATADOG_API_KEY:
  DRAIN_VERSION:
  TEARDOWN: true
  JOB_NAME:
run:
  path: bash
  args:
  - -c
  - |
    #!/bin/bash

    set -e

    cd loggregator-tools
    export GOPATH=$PWD
    export PATH=$GOPATH/bin:$PATH

    go get ./...

    function teardown {
      set +e
      ./report.sh
      exit_code=$?

      ./teardown.sh

      exit $exit_code
    }

    function restart {
      set +e
      ./report.sh
      exit_code=$?

      ./restart.sh

      exit $exit_code
    }

    if [ "$TEARDOWN" = "true" ]; then
      trap teardown EXIT
    else
      trap restart EXIT
    fi

    cd smoke_tests
    ./push.sh
    ./hammer.sh
