platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
inputs:
- name: loggregator
- name: loggregator-ci
params:
  SKIP_CERT_VERIFY: false
  WORKER_INSTANCE_COUNT: 1
  APP_WS_PORT: 443
run:
  path: bash
  args:
  - -c
  - |
    loggregator-ci/tasks/scripts/firehose-reliability-test.py
    exit 1
