platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
inputs:
- name: loggregator
- name: loggregator-ci
params:
  SKIP_CERT_VERIFY: false
  INSTANCE_COUNT: 1
run:
  path: loggregator-ci/tasks/scripts/firehose-reliability-test.py
