platform: linux
inputs:
- name: vars-store
outputs:
- name: cf-credentials
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
params:
  VARS_STORE_FILE:
run:
  path: ruby
  args:
    - -e
    - |
      #!/usr/bin/env ruby
      def load_or_raise(name)
        value = ENV[name]
        if value.nil?
          raise MissingRequiredEnvironmentVariable.new(name)
        end
        value
      end
      vars_file_path = load_or_raise('VARS_STORE_FILE')
      password = `bosh int vars-store/#{vars_file_path} --path=/cf_admin_password`.chomp

      File.open('cf-credentials/password', 'w') do |f|
        f.write(password)
      end
