platform: linux
inputs:
- name: vars-store
outputs:
- name: cf-credentials
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
params:
  VARS_STORE_FILE:
run:
  path: bash
  args:
    - -c
    - |
      set -ex
      password=`bosh int vars-store/$VARS_STORE_FILE --path=/cf_admin_password`
      echo "$password" > cf-credentials/password
