platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
inputs:
  - name: loggregator-tools
  - name: loggregator-ci
params:
  CF_API:
  USERNAME:
  PASSWORD:
  SPACE:
  ORG:
  BBL_STATE_DIR:
  SKIP_CERT_VERIFY: false
  USE_CLIENT_AUTH: false
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash

      set -ex

      loggregator-ci/scripts/environment-targeting/target-cf.sh

      mkdir -p build-workspace/src/code.cloudfoundry.org/loggregator-tools
      cp -r loggregator-tools/. build-workspace/src/code.cloudfoundry.org/loggregator-tools/

      cd build-workspace
      export GOPATH=$PWD

      cd src/code.cloudfoundry.org/loggregator-tools/latency
      go get -d -u ./...
      go build

      cf/push.sh

      sleep 30
      latency=$(curl --retry 10 "$APP_DOMAIN/latency?samples=100")

      currenttime=$(date +%s)
      curl  -X POST -H "Content-type: application/json" \
      -d "{ \"series\" :
               [{\"metric\":\"smoke_test.loggregator.latency\",
                \"points\":[[${currenttime}, ${latency}]],
                \"type\":\"gauge\",
                \"host\":\"${CF_API}\",
                \"tags\":[\"${APP_NAME}\"]}
              ]
          }" \
      'https://app.datadoghq.com/api/v1/series?api_key='"$DATADOG_API_KEY"
