image_resource:
  type: docker-image
  source:
    repository: loggregator/base
platform: linux
inputs:
  - name: develop
  - name: release-elect
outputs:
  - name: promote-develop
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash -ex
      set -e

      pushd develop
        git checkout -b merge-branch
      popd

      pushd release-elect
        git remote add -f develop-repo ../develop
        git checkout release-elect
        git merge -v "develop-repo/merge-branch" -m "Merging develop into release-elect"
      popd

      rsync -ac release-elect/ promote-develop/
