platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
params:
  CF_API:
  ORG:
  SPACE:
  APP_NAMES:
  USERNAME:
  PASSWORD:
  USE_CLIENT_AUTH: false
inputs:
- name: loggregator-tools
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash
      set -ex

      if [ "$USE_CLIENT_AUTH" == "false" ]; then
        cf login \
          -a "$CF_API" \
          -u "$USERNAME" \
          -p "$PASSWORD" \
          -s "$SPACE" \
          -o "$ORG"
      else
        cf api "$CF_API"
        cf auth "$USERNAME" "$PASSWORD" --client-credentials
        cf target -o "$ORG" -s "$SPACE"
      fi

      for app_name in $APP_NAMES; do
        set +x
        echo "##################################################"
        echo "#"
        echo "# Setting up $app_name"
        echo "#"
        echo "##################################################"
        set -x
        set +e
        cf app $app_name
        ret=$?
        set -e

        if [ $ret -ne 0 ]; then
          pushd loggregator-tools/logspinner
            go build
            cf push $app_name -b binary_buildpack -c ./logspinner -m 64M
          popd
        else
          cf restage $app_name
        fi
      done
