platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
params:
  CF_API:
  ORG:
  SPACE:
  APP_NAMES:
  USERNAME:
  PASSWORD:
  BBL_STATE_DIR:
  USE_CLIENT_AUTH: false
  SKIP_CERT_VERIFY: false
inputs:
- name: loggregator-tools
- name: loggregator-ci
- name: bbl-state
  optional: true
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash
      set -ex

      loggregator-ci/scripts/environment-targeting/target-cf.sh

      for app_name in $APP_NAMES; do
        set +x
        echo "##################################################"
        echo "#"
        echo "# Setting up $app_name"
        echo "#"
        echo "##################################################"
        set -x
        set +e
        cf app $app_name
        ret=$?
        set -e

        if [ $ret -ne 0 ]; then
          pushd loggregator-tools/logspinner
            go build
            cf push $app_name -b binary_buildpack -c ./logspinner -m 64M
          popd
        else
          cf restage $app_name
        fi
      done
