platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
params:
  CF_API:
  ORG:
  SPACE:
  APP_NAMES:
  USERNAME:
  PASSWORD:
inputs:
  - name: loggregator-ci
run:
  path: bash
  args:
    - -c
    - |
      #!/bin/bash
      set -ex

      cf login \
        -a "$CF_API" \
        -u "$USERNAME" \
        -p "$PASSWORD" \
        -s "$SPACE" \
        -o "$ORG"

      for app_name in $APP_NAMES; do
        set +e
        cf app $app_name
        ret=$?
        set -e

        if [ $ret -ne 0 ]; then
          pushd loggregator-ci/tools/logspinner
            go build
            cf push $app_name -b binary_buildpack -c ./logspinner -m 64M
          popd
        fi

        cf restage $app_name
      done
