platform: linux
image_resource:
  type: docker-image
  source:
  - repository: loggregator/bosh20
params:
  CF_SYSTEM_DOMAIN:
  CF_USERNAME:
  CF_PASSWORD:
  CF_SPACE:
  CF_ORG:
  CYCLES: 10000
  DELAY_US: 100
  DATADOG_API_KEY:
  DRAIN_VERSION:
  NUM_APPS: 1
run:
  path: bash
  args:
  - -c
  - |
    #!/bin/bash

    set -e

    cd loggregator/src/tools/smokes

    ./push.sh && ./hammer.sh && ./report.sh && ./teardown.sh
