#!/bin/bash

set -ex

# target api
cf login \
  -a "$CF_API" \
  -u "$USERNAME" \
  -p "$PASSWORD" \
  -s "$SPACE" \
  -o "$ORG"

GOPATH=$PWD/go
pushd loggregator-tools/log-cache-blackbox
  go get -d ./...
  go build
  cf push "$APP_NAME" -b binary_buildpack -c ./log-cache-blackbox -m 1G
popd

response=$(curl "$APP_DOMAIN" -d='')

latency=$(echo $response | jq .latency)
avg_query_time=$(echo $response | jq .averageQueryTime)

response=$(curl "$APP_DOMAIN/reliability" -d='')

logs_sent=$(echo $response | jq .logsSent)
logs_received=$(echo $response | jq .logsReceived)

currenttime=$(date +%s)
curl --fail -X POST -H "Content-type: application/json" \
-d "{ \"series\" :
  [
    {
      \"metric\":\"log-cache-blackbox.latency\",
      \"points\":[[${currenttime}, ${latency}]],
      \"type\":\"gauge\",
      \"host\":\"${CF_API}\",
      \"tags\":[\"${APP_NAME}\"]
    },
    {
      \"metric\":\"log-cache-blackbox.avg_query_time\",
      \"points\":[[${currenttime}, ${avg_query_time}]],
      \"type\":\"gauge\",
      \"host\":\"${CF_API}\",
      \"tags\":[\"${APP_NAME}\"]
    },
    {
      \"metric\":\"log-cache-blackbox.logs_sent\",
      \"points\":[[${currenttime}, ${logs_sent}]],
      \"type\":\"gauge\",
      \"host\":\"${CF_API}\",
      \"tags\":[\"${APP_NAME}\"]
    },
    {
      \"metric\":\"log-cache-blackbox.logs_received\",
      \"points\":[[${currenttime}, ${logs_received}]],
      \"type\":\"gauge\",
      \"host\":\"${CF_API}\",
      \"tags\":[\"${APP_NAME}\"]
    }
  ]
}" \
'https://app.datadoghq.com/api/v1/series?api_key='"$DATADOG_API_KEY"
