#!/bin/bash
set -eux

NNN_PATH=$GOPATH/src/code.cloudfoundry.org/noisy-neighbor-nozzle
BINARY_PATH=$(mktemp -d)

# Setup GOPATH
mkdir -p $NNN_PATH
cp -r noisy-neighbor-nozzle/* $NNN_PATH

# Build Binaries
pushd $NNN_PATH
    export OUTPUT=$BINARY_PATH
    export VERSION_MAJOR=0
    export VERSION_MINOR=0
    export VERSION_PATCH=0
    ./scripts/generate-binaries.sh
popd

# CF Authentication
CF_API="https://api.$SYSTEM_DOMAIN"
source loggregator-ci/scripts/environment-targeting/target-cf.sh
target-cf
if [[ -d "bbl-state" ]]; then
    CLIENT_SECRET=$(credhub-get noisy-neighbor-nozzle-client-password)
fi


# Deploy
pushd $BINARY_PATH
    ./deployer-linux \
        --app-domain "$APP_DOMAIN" \
        --capi-addr ${CF_API} \
        --client-id "$CLIENT_ID" \
        --client-secret "$CLIENT_SECRET" \
        --datadog-api-key "$DATADOG_API_KEY" \
        --loggregator-addr "wss://doppler.$SYSTEM_DOMAIN:443" \
        --nozzle-instances "$NOZZLE_COUNT" \
        --system-domain "$SYSTEM_DOMAIN" \
        --uaa-addr "https://uaa.$SYSTEM_DOMAIN" \
        --skip-cert-verify="$SKIP_CERT_VERIFY"
popd
