#!/bin/bash
set -eux

NNN_PATH=$GOPATH/src/code.cloudfoundry.org/noisy-neighbor-nozzle
BINARY_PATH=$(mktemp -d)

# Setup GOPATH
mkdir -p $NNN_PATH
cp -r noisy-neighbor-nozzle/* $NNN_PATH

# Build Binaries
pushd $NNN_PATH
    export OUTPUT=$BINARY_PATH
    export VERSION_MAJOR=0
    export VERSION_MINOR=0
    export VERSION_PATCH=0
    ./scripts/generate-binaries.sh
popd

# CF Authentication
if [ "$USE_CLIENT_AUTH" == "false" ]; then
    args="-a api.$SYSTEM_DOMAIN -u $USERNAME -p $PASSWORD -s $SPACE -o $ORG"

    if [ $SKIP_CERT_VERIFY == "true" ]; then
        args+=" --skip-ssl-validation"
    fi

    cf login ${args}
else
    if [ $SKIP_CERT_VERIFY == "true" ]; then
        cf api api."$SYSTEM_DOMAIN" --skip-ssl-validation
    else
        cf api api."$SYSTEM_DOMAIN"
    fi

    cf auth "$USERNAME" "$PASSWORD" --client-credentials
    cf target -o "$ORG" -s "$SPACE"
fi

# Deploy
pushd $BINARY_PATH
    ./deployer-linux \
        --app-domain "$APP_DOMAIN" \
        --capi-addr "https://api.$SYSTEM_DOMAIN" \
        --client-id "$CLIENT_ID" \
        --client-secret "$CLIENT_SECRET" \
        --datadog-api-key "$DATADOG_API_KEY" \
        --loggregator-addr "wss://doppler.$SYSTEM_DOMAIN:443" \
        --nozzle-instances "$NOZZLE_COUNT" \
        --system-domain "$SYSTEM_DOMAIN" \
        --uaa-addr "https://uaa.$SYSTEM_DOMAIN" \
        --skip-cert-verify="$SKIP_CERT_VERIFY"
popd
