#!/bin/bash

set -ex

eval "$(ssh-agent)"

pushd deployments-loggregator/gcp/playground
  set +x
  source .envrc
  set +e
  source k8s_login
  set -ex

  kubectl get namespaces --output json | \
    jq --raw-output .items[].metadata.name | \
    while read ns; do
      kubectl --namespace "$ns" get all --output json | \
        jq --raw-output .items[].kind | \
        tr 'A-Z' 'a-z' | \
        sort -u | \
        while read kind; do
          kubectl --namespace "$ns" delete "$kind" --all --cascade --now
      done
  done
popd
