#!/bin/bash
set -ex

source loggregator-ci/scripts/environment-targeting/target-cf.sh && target-cf

mkdir -p build-workspace/src/code.cloudfoundry.org/loggregator-tools
cp -r loggregator-tools/. build-workspace/src/code.cloudfoundry.org/loggregator-tools/

cd build-workspace
export GOPATH=$PWD

cd src/code.cloudfoundry.org/loggregator-tools/latency
go get -d -u ./...
go build

cf/push.sh

sleep 30
latency=$(curl --retry 10 "$APP_DOMAIN/latency?samples=100")

currenttime=$(date +%s)
curl  -X POST -H "Content-type: application/json" \
-d "{ \"series\" :
         [{\"metric\":\"smoke_test.loggregator.latency\",
          \"points\":[[${currenttime}, ${latency}]],
          \"type\":\"gauge\",
          \"host\":\"${CF_API}\",
          \"tags\":[\"${APP_NAME}\"]}
        ]
    }" \
'https://app.datadoghq.com/api/v1/series?api_key='"$DATADOG_API_KEY"