platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
  - name: loggregator-tools
  - name: loggregator-ci
  - name: bbl-state
    optional: true

run:
  path: loggregator-ci/tasks/blackbox/latency-test/task

params:
  CF_API:
  USERNAME:
  PASSWORD:
  SPACE:
  ORG:
  BBL_STATE_DIR:
  SKIP_CERT_VERIFY: false
  USE_CLIENT_AUTH: false
