platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
inputs:
  - name: loggregator-ci
params:
  USE_CLIENT_AUTH: false
run:
  path: loggregator-ci/tasks/blackbox-recent-logs/task
