#!/bin/bash
set -ex

# establish version/tag strings
new_version="$MAJOR_VERSION"

backport_branch="$BRANCH_NAME"

# write out github release files
echo "Loggregator $new_version" > github-release/name
echo $tag_name > github-release/tag
echo "TBD" > github-release/body

# setup ssh for reading from github
eval "$(ssh-agent -s)"
mkdir -p ~/.ssh
echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
ssh-add <(echo "$SSH_KEY")

# build final release on backport branchd
pushd loggregator-backport
  export GOPATH=$PWD
  export PATH=$PATH:$GOPATH/bin
  git checkout "$backport_branch"

  # Ensure sync-package-specs has been run
  ./scripts/sync-package-specs

  # Running status here makes the following diff-index work as
  # intended. TODO: Why?
  git status

  # Assert there is not diff
  if ! git diff-index --quiet HEAD --; then
    echo "Looks like sync-package-specs wasn't run"
    exit 1
  fi

  # setup private.yml used by `create-release --final`
  cat << EOF > config/private.yml
---
blobstore:
  provider: s3
  options:
    bucket_name: loggregator-release-blobs
    access_key_id: $S3_ACCESS_KEY
    secret_access_key: $S3_SECRET_KEY
    credentials_source: static
EOF

  # create final release and commit artifcats
  bosh -n create-release --sha2 --final \
    --tarball ../github-release/release.tgz \
    --version $new_version
  git add .
  git commit -m "Create final release"

  final_release_abbrev=$(git rev-parse --abbrev-ref HEAD)
  final_release_sha=$(git rev-parse HEAD)
  git tag "$tag_name" $final_release_sha
popd

# copy repos into output
cp -r loggregator-backport create-final-release