---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v4.21.0

inputs:
- name: loggregator-ci # - This repo
- name: release-repo

outputs:
- name: committed-repo

run:
  path: ../loggregator-ci/tasks/commit/task
  dir: committed-repo

params:
  # - Required.
  # - The commit message.
  COMMIT_MESSAGE:
