#!/bin/bash
set -ex

cp -r ../release-repo/. .

if [ ! "$(git status --porcelain)" = "" ]; then
  git config user.email "cf-loggregator@pivotal.io"
  git config user.name "Loggregator CI"
  git add --all .

  msg="$COMMIT_MESSAGE"
  if [ "$CI_SKIP" = "true" ]; then
    msg="$msg

    [ci skip]"
  fi

  git commit -m "$msg"
else
  echo "No changes to commit"
fi
