platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
inputs:
- name: loggregator-ci
outputs:
- name: deployment-settings
params:
  ADAPTER_COUNT:
  ADAPTER_COLLOCATED: false
  API_VERSION:
  CLIENT_ID:
  DIEGO_CELL_COUNT:
  DOPPLER_COUNT:
  END_RPS:
  EVENT_COUNTER_COUNT:
  LOG_API_COUNT:
  LOG_EMITTER_COUNT:
  LOG_EMITTER_INSTANCE_COUNT:
  LOG_SIZE:
  METRIC_EMITTER_COUNT:
  ORG:
  ROUTER_COUNT:
  SPACE:
  START_RPS:
  STEPS:
  SYSLOG_COUNTER_COUNT:
  SYSLOG_SERVICE_NAME:
  SYSLOG_SERVICE_URL:
  SYSTEM_DOMAIN:
  TEST_EXECUTION_MINUTES:
run:
  path: loggregator-ci/tasks/capacity-planning/build-settings.rb
