platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
inputs:
- name: bbl-state
- name: deployment-settings
- name: loggregator-ci
params:
  DATADOG_API_KEY:
run:
  path: ruby
  args:
  - -e
  - |
    #/usr/bin/env ruby

    require_relative 'loggregator-ci/tasks/scripts/datadog/client.rb'

    settings = JSON.parse(File.read('deployment-settings/settings.json'))

    title = 'Capacity Planning Scale'
    text = %Q{Capacity Planning environment has been configured with the following:
    ```
    #{JSON.pretty_generate(settings)}
    ```}
    tags = settings.each_with_object({}) { |(k, v), o| o[k.downcase] = v }

    client = DataDog::Client.new(ENV['DATADOG_API_KEY'])
    client.create_event(title, text, tags)
