#!/bin/bash

set -eu

if [ -z "$SOURCE_IMPORT_PATH" ]; then
  echo please provide an import path for the package you are trying to compile
  exit 1
fi

mkdir -p "go-workspace/src/$SOURCE_IMPORT_PATH"
cd go-workspace
export GOPATH=$PWD
cp -a ../package-src/. "src/$SOURCE_IMPORT_PATH/"

if [ "$BUILD_NON_TEST" = "true" ]; then
  go build "$SOURCE_IMPORT_PATH/..."
fi
if [ "$BUILD_TEST" = "true" ]; then
  go test -run=XXXXXXXXXX "$SOURCE_IMPORT_PATH/..."
fi
