---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
  - name: bbl-state
  - name: loggregator-ci

run:
  path: loggregator-ci/tasks/service-logs-test/task

params:
  # Required - path to bbl-state.json relative to bbl-state input
  BBL_STATE_DIR:

  # Required
  CF_API:

  # Required - Username to log in to CF
  USERNAME:

  # Required - Org to target in CF (log-stream CLI requires targeting a space)
  ORG:

  # Required - Space to target in CF (log-stream CLI requires targeting a space)
  SPACE: