platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
inputs:
  - name: loggregator-ci
  - name: bbl-state
    optional: true
params:
  USE_CLIENT_AUTH: false
  APP_NAME:
  CF_API:
  DATADOG_API_KEY:
  LOGGREGATOR_ADDR:
  ORG:
  SPACE:
  USERNAME:
  BBL_STATE_DIR:
run:
  path: loggregator-ci/tasks/blackbox/recent-logs/task
