#!/bin/bash

set -exu

pushd "bbl-state/$BBL_STATE_DIR"
  BOSH_CLIENT=$(bbl director-username); export BOSH_CLIENT
  BOSH_CLIENT_SECRET=$(bbl director-password); export BOSH_CLIENT_SECRET
  BOSH_CA_CERT=$(bbl director-ca-cert); export BOSH_CA_CERT
  BOSH_ENVIRONMENT=$(bbl director-address); export BOSH_ENVIRONMENT
popd

pushd bosh-release-dir
  bosh create-release
  if [ "$FORCE" == "true" ]; then
    bosh upload-release --rebase --force
  else
    bosh upload-release --rebase
  fi
popd
