---
platform: linux

caches:
- path: bosh-release-dir/blobs

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci # - This repo
- name: bbl-state  # - The Director's `bbl-state.json`
- name: bosh-release-dir  # - The release to upload

run:
  path: loggregator-ci/tasks/upload-release/task

params:
  # - Optional
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - Defaults to the root of the `bbl-state` input
  BBL_STATE_DIR:

  # - Optional
  # - Ignore dirty state of release repo.
  FORCE: false
