platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: loggregator-ci
- name: cfd-env

params:
  METRICS_AGENT_PORT:

run:
  path: loggregator-ci/tasks/test-metrics-agent/task
