#!/bin/bash
set -exo pipefail
source loggregator-ci/tasks/create-final-release/helpers.sh
setup_github_ssh

pushd release-repo
  git checkout $BACKPORT_BRANCH
  old_tag=$(git describe --abbrev=0 --tags --match 'v*' || true)
  if [[ $old_tag == "" ]]; then
    exit 1
  fi

  old_version=${old_tag//v}
  split_version=( ${old_version//./ })

  length="${#split_version[@]}"
  if [[ $length -lt 3 ]]; then
    patch=1
  else
    # bump patch
    patch=`expr ${split_version[2]} + 1`
  fi

  split_version[2]=${patch}
  NEW_VERSION=$(join_by . "${split_version[@]}")
  commit_range="${old_tag}..HEAD"

  build_github_release_info "$PWD" "$RELEASE_NAME" "$NEW_VERSION" "${commit_range}"
  create_tagged_release "$PWD" "$NEW_VERSION"
popd

cp -r release-repo repos
