image_resource:
  type: docker-image
  source:
    repository: loggregator/base
platform: linux
inputs:
  # - Required
  # - The repo from which the final release will be created
- name: release-repo

  # - Required
  # - The task repository
- name: loggregator-ci

outputs:
  # - The artifacts used to create the github release
- name: github-release

  # - The modified repos that need to be pushed back to github
- name: repos

run:
  path: loggregator-ci/tasks/create-final-release/backport/task

params:
  # - Required
  # - The S3 access key for release blobstore
  S3_ACCESS_KEY:

  # - Required
  # - The S3 secret key for release blobstore
  S3_SECRET_KEY:

  # - Required
  # - The bucket name of the S3 release blobstore
  BLOBSTORE_BUCKET:

  # - Required
  # - The ssh key used to talk to github to pull latest branch version
  SSH_KEY:

  # - Required
  # - Human readable name of the created release (e.g. Loggregator)
  RELEASE_NAME:

  # - Required
  # - Branch from which the final release will be created
  BACKPORT_BRANCH:
