---
platform: linux

image_resource:
  type: docker-image
  source: {repository: loggregator/base}

inputs:
- name: loggregator-ci
- name: deployment-loggregator

outputs:
- name: manifest

run:
  path: loggregator-ci/tasks/service-metrics-release/scripts/generate-service-metrics-manifest.sh

params:
  VARS_FILE:
