platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: sonde-go
  path: src/github.com/cloudfoundry/sonde-go
- name: dropsonde-protocol
- name: loggregator-ci

outputs:
- name: bumped-sonde-go

run:
  path: loggregator-ci/tasks/sonde-go-generate/task
