image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
platform: linux
inputs:
  - name: loggregator-ci
  - name: bbl-state
params:
  BBL_STATE_DIR:
  ORG:
  SPACE:
  SYSTEM_DOMAIN:
run:
  path: loggregator-ci/tasks/create-org-and-space/task
