platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/blackbox
inputs:
- name: loggregator-ci
- name: bbl-state
  optional: true
params:
  DATADOG_API_KEY:
  CF_API:
  APP_NAME:
  BBL_STATE_DIR:
  CYCLES: 10000
  DELAY: 20
  DELAY_UNIT: ms
  USE_CLIENT_AUTH: false
  SKIP_CERT_VERIFY: false
run:
  path: loggregator-ci/tasks/blackbox/logspinner/task
