resources:
- name: bosh-hm-forwarder-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-hm-forwarder-release
    branch: master
    private_key: {{bosh-hm-forwarder-key}}
    ignore_paths:
    - .final_builds
    - releases

- name: bosh-hm-forwarder
  type: git
  source:
    uri: git@github.com:cloudfoundry/bosh-hm-forwarder
    private_key: {{bosh-hm-forwarder-key}}

jobs:
- name: unit-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: bosh-hm-forwarder-release
      trigger: false
    - get: bosh-hm-forwarder
      trigger: true
  - task: run-units
    config:
      image_resource:
        type: docker-image
        source:
          repository: loggregator/base
      platform: linux
      inputs:
      - name: bosh-hm-forwarder-release
      - name: bosh-hm-forwarder
      run:
        path: bash
        args:
        - -c
        - {{bosh_hm_forwarder_units}}

- name: bump-release-submodule
  serial: true
  public: false
  plan:
  - aggregate:
    - get: bosh-hm-forwarder-release
      trigger: false
    - get: bosh-hm-forwarder
      passed:
      - unit-tests
      trigger: true
  - task: update-submodule
    file: loggregator-ci/tasks/bump-submodule/task.yml
    input_mapping:
      release-repo: bosh-hm-forwarder-release
      source-repo: bosh-hm-forwarder
    output_mapping:
      bumped-release-repo: updated-bosh-hm-forwarder-release
    params:
      SUBMODULE_PATH: src/github.com/cloudfoundry/bosh-hm-forwarder
  - task: commit
    file: loggregator-ci/tasks/commit/task.yml
    input_mapping:
      release-repo: updated-bosh-hm-forwarder-release
    output_mapping:
      committed-repo: bumped-bosh-hm-forwarder-release
    params:
      COMMIT_MESSAGE: "Bump bosh-hm-forwarder"
  - put: bosh-hm-forwarder-release
    params:
      repository: bumped-bosh-hm-forwarder-release
      rebase: false
