resources:
- name: 5m
  type: time
  source: {interval: 5m}

- name: go-loggregator
  type: git
  source:
    uri: https://github.com/cloudfoundry/go-loggregator
    branch: master

- name: deployments-loggregator
  type: git
  source: &deployments_loggregator
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: ((deployments-loggregator-key))

- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git

- name: cfar-logging-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cfar-logging-acceptance-tests.git

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    tag_filter: v3.*
    private_key: ((loggregator-key))

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    tag_filter: v7.*

- name: loggregator-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-ci
    branch: master
    private_key: ((cf-loggregator-oauth-bot-key))

- name: cf-syslog-drain-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-syslog-drain-release
    branch: develop
    private_key: ((cf-loggregator-oauth-bot-key))
    ignore_paths:
    - .final_builds
    - releases

- name: cf-syslog-drain-release-release-elect
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-syslog-drain-release
    branch: release-elect
    private_key: ((cf-loggregator-oauth-bot-key))
    ignore_paths:
    - .final_builds
    - releases

- name: cf-syslog-drain-release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-syslog-drain-release
    branch: master
    private_key: ((cf-loggregator-oauth-bot-key))
    disable_ci_skip: true

- name: scalable-syslog
  type: git
  source:
    uri: git@github.com:cloudfoundry/scalable-syslog
    private_key: ((cf-loggregator-oauth-bot-key))
    branch: master

- name: bumper-tool
  type: git
  source:
    uri: https://github.com/loggregator/bumper

- name: cf-drain-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-drain-cli
    branch: develop

- name: cf-drain-cli-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-drain-cli
    branch: master
    private_key: ((cf-loggregator-oauth-bot-key))

- name: service-metrics-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/service-metrics-release
    branch: develop
    private_key: {{cf-loggregator-oauth-bot-key}}

- name: on-demand-service-broker-release
  type: git
  source:
    uri: https://github.com/pivotal-cf/on-demand-service-broker-release
    branch: v0.20.0

jobs:
- name: cf-syslog-drain-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: loggregator-ci
    - get: scalable-syslog
      trigger: true
  - task: run-tests
    file: loggregator-ci/tasks/go-test-with-latest-packages/task.yml
    input_mapping:
      source-repo: scalable-syslog
    params:
      IMPORT_PATH: code.cloudfoundry.org/scalable-syslog

- name: cf-drain-cli-tests
  serial: true
  public: true
  plan:
  - aggregate:
    - get: loggregator-ci
    - get: cf-drain-cli
      trigger: true
  - task: run-tests
    file: loggregator-ci/tasks/go-test-with-latest-packages/task.yml
    input_mapping:
      source-repo: cf-drain-cli
    params:
      IMPORT_PATH: code.cloudfoundry.org/cf-drain-cli

- name: cf-syslog-drain-bump-submodule
  serial: true
  plan:
  - aggregate:
    - get: loggregator-ci
    - get: go-loggregator
    - get: cf-syslog-drain-release
      trigger: true
    - get: scalable-syslog
      passed: ["cf-syslog-drain-tests"]
      trigger: true
  - task: update-submodule
    file: loggregator-ci/tasks/bump-submodule/task.yml
    input_mapping:
      release-repo: cf-syslog-drain-release
      source-repo: scalable-syslog
    output_mapping:
      bumped-release-repo: updated-cf-syslog-drain-release
    params:
      SUBMODULE_PATH: src/code.cloudfoundry.org/scalable-syslog
  - task: update-go-loggregator-submodule
    file: loggregator-ci/tasks/bump-submodule/task.yml
    input_mapping:
      release-repo: updated-cf-syslog-drain-release
      source-repo: go-loggregator
    output_mapping:
      bumped-release-repo: bumped-go-loggregator-release
    params:
      SUBMODULE_PATH: src/code.cloudfoundry.org/go-loggregator
  - task: sync-package-specs
    file: loggregator-ci/tasks/run-release-script/task.yml
    input_mapping:
      release-repo: bumped-go-loggregator-release
    output_mapping:
      updated-release-repo: synced-cf-syslog-drain-release
    params:
      SCRIPT: scripts/sync-package-specs
  - task: run-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: loggregator/base
      inputs:
      - name: synced-cf-syslog-drain-release
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash

          set -ex

          pushd synced-cf-syslog-drain-release
            export GOPATH="$PWD"
            export PATH="$GOPATH/bin:$PATH"
            go test -race code.cloudfoundry.org/scalable-syslog/...
          popd
  - task: commit
    file: loggregator-ci/tasks/commit-with-shortlog/task.yml
    input_mapping:
      release-repo: synced-cf-syslog-drain-release
    output_mapping:
      committed-repo: committed-cf-syslog-drain-release
    params:
      PATHS: |
        src/code.cloudfoundry.org/scalable-syslog
        src/code.cloudfoundry.org/go-loggregator
        packages
  - put: cf-syslog-drain-release
    params:
      repository: committed-cf-syslog-drain-release
      rebase: true

- name: cf-syslog-drain-promotion
  serial: true
  plan:
  - aggregate:
    - get: develop
      resource: cf-syslog-drain-release
      trigger: true
      passed: ["cats", "cfar-lats"]
    - get: cf-syslog-drain-release-release-elect
  - put: cf-syslog-drain-release-release-elect
    params:
      repository: develop

- name: cf-syslog-drain-master-promotion
  serial: true
  plan:
  - get: 5m
    trigger: true
  - aggregate:
    - get: cf-syslog-drain-release-release-elect
      passed: ["cf-syslog-drain-promotion"]
      trigger: true
    - get: cf-syslog-drain-release-master
    - get: bumper-tool
    - get: loggregator-ci
  - task: bumper
    file: loggregator-ci/tasks/bumper/task.yml
    input_mapping:
      source: cf-syslog-drain-release-release-elect
      dest: cf-syslog-drain-release-master
    params:
      SOURCE_BRANCH: release-elect
      DEST_BRANCH: master
      FOLLOW_BUMPS_OF: src/code.cloudfoundry.org/scalable-syslog
  - put: cf-syslog-drain-release-master
    params:
      repository: merged-dest

- name: cf-drain-cli-promotion
  serial: true
  plan:
  - get: 5m
    trigger: true
  - aggregate:
    - get: cf-drain-cli
      passed: ["cfar-lats"]
      trigger: true
    - get: cf-drain-cli-master
    - get: bumper-tool
    - get: loggregator-ci
  - task: bumper
    file: loggregator-ci/tasks/bumper/task.yml
    input_mapping:
      source: cf-drain-cli
      dest: cf-drain-cli-master
    params:
      SOURCE_BRANCH: develop
      DEST_BRANCH: master
  - put: cf-drain-cli-master
    params:
      repository: merged-dest

- name: cf-deploy
  serial: true
  serial_groups:
  - cf-deploy
  - bosh-cf-cats
  - bosh-cfar-lats
  plan:
  - aggregate:
    - get: loggregator-ci
    - get: bbl-state
      resource: deployments-loggregator
    - get: cf-deployment
      trigger: true
    - get: cf-deployment-concourse-tasks
    - get: cf-syslog-drain-release
      trigger: true
      passed: ["cf-syslog-drain-bump-submodule"]
    - get: cf-drain-cli
      trigger: true
      passed: ["cf-drain-cli-tests"]
    - get: vars-store
      resource: deployments-loggregator
    - get: vars-files
      resource: deployments-loggregator
    - get: deployments-loggregator
    - get: service-metrics-release
    - get: on-demand-service-broker-release
      params:
        submodules:
        - src/github.com/pivotal-cf/on-demand-services-sdk
        - src/github.com/pivotal-cf/on-demand-service-broker
        - src/github.com/pivotal-cf/brokerapi
  - task: upload-syslog-drain-release
    file: loggregator-ci/tasks/upload-release/task.yml
    input_mapping:
      bosh-release-dir: cf-syslog-drain-release
    params:
      BBL_STATE_DIR: gcp/ci-pool/eight
  - task: upload-on-demand-service-broker-release
    file: loggregator-ci/tasks/upload-release/task.yml
    input_mapping:
      bosh-release-dir: on-demand-service-broker-release
    params:
      BBL_STATE_DIR: gcp/ci-pool/eight
  - task: upload-service-metrics-release
    file: loggregator-ci/tasks/upload-release/task.yml
    input_mapping:
      bosh-release-dir: service-metrics-release
    params:
      BBL_STATE_DIR: gcp/ci-pool/eight
  - task: copy-ops-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          tag: v5.20.0
      inputs:
      - name: bbl-state
      - name: cf-deployment
      outputs:
      - name: ops-files
      - name: vars-files
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          set -e

          pushd bbl-state/gcp/ci-pool/eight
            eval "$(bbl print-env)"
          popd

          cp cf-deployment/operations/scale-to-one-az.yml ops-files/

          cat <<EOT >> ops-files/on-the-fly.yml
          - type: replace
            path: /releases/name=cf-syslog-drain
            value:
              name: cf-syslog-drain
              version: latest
          - type: replace
            path: /instance_groups/name=adapter/jobs/name=adapter/properties/scalablesyslog?/adapter?/syslog_skip_cert_verify?
            value: true
          EOT
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    params:
      BBL_STATE_DIR: gcp/ci-pool/eight
  - task: cf-deploy
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    params:
      BBL_STATE_DIR: gcp/ci-pool/eight
      SYSTEM_DOMAIN: eight.loggr.cf-app.com
      OPS_FILES: |
        scale-to-one-az.yml
        on-the-fly.yml
  - task: enable-feature-flags
    file: cf-deployment-concourse-tasks/set-feature-flags/task.yml
    params:
      BBL_STATE_DIR: gcp/ci-pool/eight
      SYSTEM_DOMAIN: eight.loggr.cf-app.com
      ENABLED_FEATURE_FLAGS: diego_docker

- name: deploy-on-demand-broker
  serial: true
  serial_groups:
  - cf-deploy
  - bosh-cf-cats
  - bosh-cfar-lats
  plan:
  - aggregate:
    - get: loggregator-ci
    - get: bbl-state
      resource: deployments-loggregator
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: cf-syslog-drain-release
      trigger: true
      passed: ["cf-deploy"]
    - get: cf-drain-cli
      trigger: true
      passed: ["cf-deploy"]
    - get: vars-store
      resource: deployments-loggregator
    - get: vars-files
      resource: deployments-loggregator
    - get: deployments-loggregator
    - get: service-metrics-release
    - get: on-demand-service-broker-release
      params:
        submodules:
        - src/github.com/pivotal-cf/on-demand-services-sdk
        - src/github.com/pivotal-cf/on-demand-service-broker
        - src/github.com/pivotal-cf/brokerapi
  - task: copy-ops-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          tag: v5.20.0
      inputs:
      - name: bbl-state
      - name: cf-deployment
      outputs:
      - name: ops-files
      - name: vars-files
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          set -e

          pushd bbl-state/gcp/ci-pool/eight
            eval "$(bbl print-env)"
          popd

          cp bbl-state/gcp/ci-pool/eight/service-metrics-broker-vars.yml vars-files

          service_metrics_version=$(bosh releases | grep service-metrics | grep -v service-metrics-adapter | head -n1 | awk '{print $2}' | cut -d '*' -f 1)
          cat <<EOT >> vars-files/service-metrics-version.yml
          service-metrics-release-version: $service_metrics_version
          EOT

          odb_version=$(bosh releases | grep on-demand-service-broker | head -n1 | awk '{print $2}' | cut -d '*' -f 1)
          cat <<EOT >> ops-files/service-metrics.yml
          - type: remove
            path: /variables/name=loggregator_ca
          - type: replace
            path: /variables/name=service_metrics/options/ca
            value: /bosh-eight/cf/loggregator_ca
          - type: replace
            path: /variables/name=loggregator_agent/options/ca
            value: /bosh-eight/cf/loggregator_ca
          - type: replace
            path: /variables/name=loggregator_agent/options/alternative_names
            value:
              - metron
              - agent
              - logalhost
              - 127.0.0.1
          - type: replace
            path: /releases/name=on-demand-service-broker/version
            value: $odb_version
          EOT

  - task: deploy
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      cf-deployment: service-metrics-release
      ops-files: ops-files
      bbl-state: deployments-loggregator
      vars-files: vars-files
    params:
      BBL_STATE_DIR: gcp/ci-pool/eight
      SYSTEM_DOMAIN: eight.loggr.cf-app.com
      MANIFEST_FILE: manifests/sample-service-metrics.yml
      VARS_FILES: |
        service-metrics-broker-vars.yml
        service-metrics-version.yml
      OPS_FILES: |
        service-metrics.yml
  - task: wait-for-service-broker
    timeout: 10m
    file: loggregator-ci/tasks/wait-for-service-broker/task.yml
    params:
      ENV_URL: sample-odb.eight.loggr.cf-app.com
  - task: register-service-broker
    file: loggregator-ci/tasks/run-errand/task.yml
    input_mapping:
      bbl-state: deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/ci-pool/eight
      DEPLOYMENT_NAME: sample-service-metrics
      ERRAND: register-broker
  - task: upgrade-all-service-instances
    file: loggregator-ci/tasks/run-errand/task.yml
    input_mapping:
      bbl-state: deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/ci-pool/eight
      DEPLOYMENT_NAME: sample-service-metrics
      ERRAND: upgrade-all-service-instances

- name: cats
  serial: true
  serial_groups:
  - bosh-cf-cats
  plan:
    - aggregate:
      - get: cf-deployment-concourse-tasks
      - get: deployments-loggregator
      - get: cf-acceptance-tests
      - get: cf-syslog-drain-release
        passed: ["cf-deploy"]
        trigger: true
      - get: loggregator-ci
    - task: update-config
      file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
      input_mapping:
        bbl-state: deployments-loggregator
        integration-configs: deployments-loggregator
      params:
        CATS_INTEGRATION_CONFIG_FILE: gcp/ci-pool/cats-config.json
        BBL_STATE_DIR: gcp/ci-pool/eight
        SYSTEM_DOMAIN: eight.loggr.cf-app.com
    - task: run-cats
      file: cf-deployment-concourse-tasks/run-cats/task.yml
      input_mapping:
        integration-config: updated-integration-configs
      params:
        NODES: 9
        CONFIG_FILE_PATH: gcp/ci-pool/cats-config.json

- name: cfar-lats
  serial: true
  serial_groups:
  - bosh-cfar-lats
  plan:
    - aggregate:
      - get: cfar-logging-acceptance-tests
        trigger: true
      - get: cf-syslog-drain-release
        passed: ["cf-deploy"]
        trigger: true
      - get: loggregator-ci
      - get: cf-drain-cli
        passed: ["deploy-on-demand-broker"]
        trigger: true
    - task: run-cfar-lats
      file: loggregator-ci/tasks/cfar-lats/task.yml
      params:
        CF_ADMIN_USER: {{eight-username}}
        CF_ADMIN_PASSWORD: {{eight-password}}
        CF_DOMAIN: eight.loggr.cf-app.com
        SKIP_SSL_VALIDATION: true

