resources:
- name: 10m
  type: time
  source: {interval: 10m}
- name: 15m
  type: time
  source: {interval: 15m}
- name: 1h
  type: time
  source: {interval: 1h}

- name: loggregator-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci

- name: loggregator-tools
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/loggregator-tools

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

jobs:
- name: floodspinner
  public: false
  serial: true
  plan:
  - get: loggregator-tools
  - get: loggregator-ci
  - get: 15m
    trigger: true
  - task: restage-logspinner
    file: loggregator-ci/tasks/restage-apps.yml
    timeout: 15m
    params:
      APP_NAMES: "floodspinner"
      CF_API: "api.coconut.cf-app.com"
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/cf-blackbox/task.yml
    params:
      CF_API: "api.coconut.cf-app.com"
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
      APP_DOMAIN: "floodspinner.coconut.cf-app.com"
      APP_NAME: "floodspinner"
      WAIT: 60
      CYCLES: 10000
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DELAY: "2"
      DELAY_UNIT: "us"
      MESSAGE: "FIFTEEN-MINUTE"
    timeout: 15m
  - task: run-recent-logs-smoke-tests
    file: loggregator-ci/tasks/blackbox-recent-logs/task.yml
    params:
      APP_NAME: "floodspinner"
      CF_API: "api.coconut.cf-app.com"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      LOGGREGATOR_ADDR: "wss://doppler.coconut.cf-app.com:443"
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
    timeout: 15m

- name: dripspinner
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: 1h
    trigger: true
  - task: restage-logspinner
    file: loggregator-ci/tasks/restage-apps.yml
    timeout: 15m
    params:
      APP_NAMES: "dripspinner"
      CF_API: "api.coconut.cf-app.com"
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/cf-blackbox/task.yml
    params:
      CF_API: "api.coconut.cf-app.com"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      LOGGREGATOR_ADDR: "wss://doppler.coconut.cf-app.com:443"
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
      APP_DOMAIN: "dripspinner.coconut.cf-app.com"
      APP_NAME: "dripspinner"
      WAIT: 600
      CYCLES: 1000
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY-STREAM"
    timeout: 15m

- name: flowspinner
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: 1h
    trigger: true
  - task: restage-logspinner
    file: loggregator-ci/tasks/restage-apps.yml
    timeout: 15m
    params:
      APP_NAMES: "flowspinner"
      CF_API: "api.coconut.cf-app.com"
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/cf-blackbox/task.yml
    params:
      CF_API: "api.coconut.cf-app.com"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      LOGGREGATOR_ADDR: "wss://doppler.coconut.cf-app.com:443"
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
      APP_DOMAIN: "flowspinner.coconut.cf-app.com"
      APP_NAME: "flowspinner"
      WAIT: 60
      CYCLES: 1000
      DELAY: "1"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
    timeout: 15m

- name: floodspinner-stream
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: 15m
    trigger: true
  - task: restage-logspinner
    file: loggregator-ci/tasks/restage-apps.yml
    timeout: 15m
    params:
      APP_NAMES: "floodspinner-stream"
      CF_API: "api.coconut.cf-app.com"
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/cf-log-stream-blackbox/task.yml
    params:
      DOMAIN: coconut.cf-app.com
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
      APP_NAME: "floodspinner-stream"
      WAIT: 30
      CYCLES: 10000
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DELAY: "2"
      DELAY_UNIT: "us"
      MESSAGE: "FIFTEEN-MINUTE-STREAM"
    timeout: 15m

- name: dripspinner-stream
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: 1h
    trigger: true
  - task: restage-logspinner
    file: loggregator-ci/tasks/restage-apps.yml
    timeout: 15m
    params:
      APP_NAMES: "dripspinner-stream"
      CF_API: "api.coconut.cf-app.com"
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/cf-log-stream-blackbox/task.yml
    params:
      DOMAIN: coconut.cf-app.com
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
      APP_NAME: dripspinner-stream
      WAIT: 600
      CYCLES: 1000
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY-STREAM"
    timeout: 15m

- name: flowspinner-stream
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: 1h
    trigger: true
  - task: restage-logspinner
    file: loggregator-ci/tasks/restage-apps.yml
    timeout: 15m
    params:
      APP_NAMES: "flowspinner-stream"
      CF_API: "api.coconut.cf-app.com"
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/cf-log-stream-blackbox/task.yml
    params:
      DOMAIN: coconut.cf-app.com
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
      APP_NAME: flowspinner-stream
      WAIT: 30
      CYCLES: 1000
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DELAY: "1"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY-STREAM"
    timeout: 15m

- name: https-syslog-drain
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: 1h
    trigger: true
  - task: v2-drain
    file: loggregator-ci/tasks/cf-syslog-drain-smoke-test.yml
    params:
      CF_ORG: system
      CF_SPACE: blackbox-testing
      CF_APP_DOMAIN: coconut.cf-app.com
      CF_SYSTEM_DOMAIN: coconut.cf-app.com
      CF_USERNAME: {{coconut-username}}
      CF_PASSWORD: {{coconut-password}}
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DRAIN_VERSION: "2.0"
      DRAIN_TYPE: "https"
      JOB_NAME: "https-teardown"
    timeout: 20m

- name: https-syslog-drain-no-teardown
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: 1h
    trigger: true
  - task: v2-drain
    file: loggregator-ci/tasks/cf-syslog-drain-smoke-test.yml
    params:
      TEARDOWN: false
      CF_ORG: system
      CF_SPACE: blackbox-testing
      CF_APP_DOMAIN: coconut.cf-app.com
      CF_SYSTEM_DOMAIN: coconut.cf-app.com
      CF_USERNAME: {{coconut-username}}
      CF_PASSWORD: {{coconut-password}}
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DRAIN_VERSION: "2.0"
      DRAIN_TYPE: "https"
      JOB_NAME: "https-no-teardown"
    timeout: 20m

- name: latency
  public: false
  serial: true
  plan:
  - get: loggregator-tools
  - get: loggregator-ci
  - get: 15m
    trigger: true
  - task: run-latency-tests
    file: loggregator-ci/tasks/latency-test.yml
    params:
      APP_DOMAIN: "loggregator-latency.coconut.cf-app.com"
      APP_NAME: "loggregator-latency"
      CF_API: "api.coconut.cf-app.com"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      ORG: system
      SPACE: blackbox-testing
      USERNAME: {{coconut-username}}
      PASSWORD: {{coconut-password}}
      SKIP_CERT_VERIFY: true
    timeout: 15m

- name: vm-health-metrics
  public: false
  serial: true
  plan:
  - aggregate:
    - get: loggregator-ci
    - get: deployments-loggregator
    - get: 10m
      trigger: true
  - task: health-check
    file: loggregator-ci/tasks/bosh-vm-health-check/task.yml
    input_mapping:
      bbl-state: deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/coconut-bbl
      DEPLOYMENT_NAME: cf
