resources:
- name: 10m
  type: time
  source: {interval: 10m}
- name: 15m
  type: time
  source: {interval: 15m}
- name: 1h
  type: time
  source: {interval: 1h}

- name: loggregator-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci

- name: loggregator-tools
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/loggregator-tools

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

jobs:
- name: dripspinner
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: bbl-state
    resource: deployments-loggregator
  - get: 1h
    trigger: true
  - task: restage-logspinner
    file: loggregator-ci/tasks/blackbox/restage-apps/task.yml
    timeout: 15m
    params:
      APP_NAMES: "dripspinner"
      APP: "logspinner"
      CF_API: api.((acceptance_system_domain))
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
  - task: run-smoke-tests
    file: loggregator-ci/tasks/blackbox/logspinner/task.yml
    params:
      CF_API: api.((acceptance_system_domain))
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      LOGGREGATOR_ADDR: wss://doppler.((acceptance_system_domain)):443
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
      APP_DOMAIN: dripspinner.((acceptance_system_domain))
      APP_NAME: "dripspinner"
      WAIT: 600
      CYCLES: 1000
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY-STREAM"
    timeout: 15m

- name: flowspinner
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: bbl-state
    resource: deployments-loggregator
  - get: 1h
    trigger: true
  - task: restage-logspinner
    file: loggregator-ci/tasks/blackbox/restage-apps/task.yml
    timeout: 15m
    params:
      APP_NAMES: "flowspinner"
      APP: "logspinner"
      CF_API: api.((acceptance_system_domain))
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
  - task: run-smoke-tests
    file: loggregator-ci/tasks/blackbox/logspinner/task.yml
    params:
      CF_API: api.((acceptance_system_domain))
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      LOGGREGATOR_ADDR: wss://doppler.((acceptance_system_domain)):443
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
      APP_DOMAIN: flowspinner.((acceptance_system_domain))
      APP_NAME: "flowspinner"
      WAIT: 60
      CYCLES: 1000
      DELAY: "1"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
    timeout: 15m

- name: dripspinner-stream
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: bbl-state
    resource: deployments-loggregator
  - get: 1h
    trigger: true
  - task: restage-logspinner
    file: loggregator-ci/tasks/blackbox/restage-apps/task.yml
    timeout: 15m
    params:
      APP_NAMES: "dripspinner-stream"
      APP: "logspinner"
      CF_API: api.((acceptance_system_domain))
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
  - task: run-smoke-tests
    file: loggregator-ci/tasks/blackbox/cf-log-stream/task.yml
    params:
      DOMAIN: ((acceptance_system_domain))
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
      APP_NAME: dripspinner-stream
      WAIT: 600
      CYCLES: 1000
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY-STREAM"
    timeout: 15m

- name: flowspinner-stream
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: bbl-state
    resource: deployments-loggregator
  - get: 1h
    trigger: true
  - task: restage-logspinner
    file: loggregator-ci/tasks/blackbox/restage-apps/task.yml
    timeout: 15m
    params:
      APP_NAMES: "flowspinner-stream"
      APP: "logspinner"
      CF_API: api.((acceptance_system_domain))
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
  - task: run-smoke-tests
    file: loggregator-ci/tasks/blackbox/cf-log-stream/task.yml
    params:
      DOMAIN: ((acceptance_system_domain))
      ORG: "system"
      SPACE: "blackbox-testing"
      USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
      APP_NAME: flowspinner-stream
      WAIT: 30
      CYCLES: 1000
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DELAY: "1"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY-STREAM"
    timeout: 15m

- name: https-syslog-drain
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: bbl-state
    resource: deployments-loggregator
  - get: 1h
    trigger: true
  - task: v2-drain
    file: loggregator-ci/tasks/blackbox/cf-syslog-drain/task.yml
    params:
      CF_ORG: system
      CF_SPACE: blackbox-testing
      CF_APP_DOMAIN: ((acceptance_system_domain))
      CF_SYSTEM_DOMAIN: ((acceptance_system_domain))
      CF_USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DRAIN_VERSION: "2.0"
      DRAIN_TYPE: "https"
      JOB_NAME: "https-teardown"
    timeout: 20m

- name: https-syslog-drain-no-teardown
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator-tools
  - get: bbl-state
    resource: deployments-loggregator
  - get: 1h
    trigger: true
  - task: v2-drain
    file: loggregator-ci/tasks/blackbox/cf-syslog-drain/task.yml
    params:
      TEARDOWN: false
      CF_ORG: system
      CF_SPACE: blackbox-testing
      CF_APP_DOMAIN: ((acceptance_system_domain))
      CF_SYSTEM_DOMAIN: ((acceptance_system_domain))
      CF_USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DRAIN_VERSION: "2.0"
      DRAIN_TYPE: "https"
      JOB_NAME: "https-no-teardown"
    timeout: 20m

- name: latency
  public: false
  serial: true
  plan:
  - get: loggregator-tools
  - get: bbl-state
    resource: deployments-loggregator
  - get: loggregator-ci
  - get: 15m
    trigger: true
  - task: run-latency-tests
    file: loggregator-ci/tasks/blackbox/latency-test/task.yml
    params:
      APP_DOMAIN: loggregator-latency.((acceptance_system_domain))
      APP_NAME: "loggregator-latency"
      CF_API: api.((acceptance_system_domain))
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      ORG: system
      SPACE: blackbox-testing
      USERNAME: admin
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
    timeout: 15m

- name: vm-health-metrics
  public: false
  serial: true
  plan:
  - in_parallel:
    - get: loggregator-ci
    - get: deployments-loggregator
    - get: 10m
      trigger: true
  - task: health-check
    file: loggregator-ci/tasks/blackbox/bosh-vm-health-check/task.yml
    input_mapping:
      bbl-state: deployments-loggregator
    params:
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
      DEPLOYMENT_NAME: cf
