groups:
- name: concourse
  jobs:
  - build-base-image
  - bosh10
  - cf-deployment-concourse-tasks
  - blackbox
- name: tools
  jobs:
  - emitter
  - logspinner
  - log-cache-emitter
  - log-cache-blackbox
  - certs
  - fluentd

resources:
- name: loggregator-tools
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/loggregator-tools

- name: base-image
  type: docker-image
  source:
    repository: loggregator/base
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: cf-deployment-concourse-tasks-image
  type: docker-image
  source:
    repository: loggregator/cf-deployment-concourse-tasks
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/loggregator/cf-deployment-concourse-tasks
    branch: master
    paths:
    - dockerfiles/cf-deployment-concourse-tasks

- name: base-image-docker-build-context
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/base

- name: golang-1.10-tarball
  type: s3
  source:
    endpoint: storage.googleapis.com
    bucket: golang
    regexp: 'go(1\.10(\.\d+)?)\.linux-amd64\.tar.gz'

- name: loggregator-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master

- name: bosh10-image-docker-build-context
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/bosh10

- name: bosh10-image
  type: docker-image
  source:
    repository: loggregator/bosh10
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: blackbox-image-docker-build-context
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/blackbox

- name: blackbox-image
  type: docker-image
  source:
    repository: loggregator/blackbox
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: log-cache-blackbox-image-docker-build-context
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/log-cache-blackbox

- name: log-cache-blackbox-image
  type: docker-image
  source:
    repository: loggregator/log-cache-blackbox
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: emitter-image-docker-build-context
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/emitter

- name: emitter-image
  type: docker-image
  source:
    repository: loggregator/emitter
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: logspinner-image-docker-build-context
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/logspinner

- name: logspinner-image
  type: docker-image
  source:
    repository: loggregator/logspinner
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: log-cache-emitter-image-docker-build-context
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/log-cache-emitter

- name: log-cache-emitter-image
  type: docker-image
  source:
    repository: loggregator/log-cache-emitter
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: certs-image-docker-build-context
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/certs

- name: certs-image
  type: docker-image
  source:
    repository: loggregator/certs
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

- name: fluentd-image-docker-build-context
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
    branch: master
    paths:
    - docker-images/fluentd

- name: fluentd-image
  type: docker-image
  source:
    repository: loggregator/fluentd
    username: {{docker-hub-username}}
    password: {{docker-hub-password}}

jobs:
- name: build-base-image
  public: true
  plan:
  - aggregate:
    - get: golang-1.10-tarball
      trigger: true
    - get: base-image-docker-build-context
      trigger: true
  - put: base-image
    params:
      build: base-image-docker-build-context/docker-images/base
      tag_as_latest: true
      cache_tag: latest

- name: bosh10
  plan:
  - get: bosh10-image-docker-build-context
    trigger: true
  - put: bosh10-image
    params:
      build: bosh10-image-docker-build-context/docker-images/bosh10
      tag_as_latest: true
      cache_tag: latest

- name: cf-deployment-concourse-tasks
  plan:
  - get: cf-deployment-concourse-tasks
    trigger: true
  - put: cf-deployment-concourse-tasks-image
    params:
      build: cf-deployment-concourse-tasks/dockerfiles/cf-deployment-concourse-tasks
      tag_as_latest: true
      cache_tag: latest

- name: blackbox
  plan:
  - get: blackbox-image-docker-build-context
    trigger: true
  - put: blackbox-image
    params:
      build: blackbox-image-docker-build-context/docker-images/blackbox
      tag_as_latest: true
      cache_tag: latest

- name: log-cache-blackbox
  plan:
  - aggregate:
    - get: log-cache-blackbox-image-docker-build-context
      trigger: true
    - get: loggregator-tools
      trigger: true
    - get: loggregator-ci
  - task: build-image
    file: loggregator-ci/tasks/build-docker-image/task.yml
    input_mapping:
      source-repo: loggregator-tools
    params:
      BASE_PACKAGE: code.cloudfoundry.org/loggregator-tools
      SUB_PACKAGE: log-cache-blackbox
      IMAGE_NAME: log-cache-blackbox
  - put: log-cache-blackbox-image
    params:
      build: build-image/build
      tag: build-image/tag
      tag_as_latest: true
      cache: true
      cache_tag: latest

- name: emitter
  plan:
  - aggregate:
    - get: emitter-image-docker-build-context
      trigger: true
    - get: loggregator-tools
      trigger: true
    - get: loggregator-ci
  - task: build-image
    file: loggregator-ci/tasks/build-docker-image/task.yml
    input_mapping:
      source-repo: loggregator-tools
    params:
      BASE_PACKAGE: code.cloudfoundry.org/loggregator-tools
      SUB_PACKAGE: emitter
      IMAGE_NAME: emitter
  - put: emitter-image
    params:
      build: build-image/build
      tag: build-image/tag
      tag_as_latest: true
      cache: true
      cache_tag: latest

- name: logspinner
  plan:
  - aggregate:
    - get: logspinner-image-docker-build-context
      trigger: true
    - get: loggregator-tools
      trigger: true
    - get: loggregator-ci
  - task: build-image
    file: loggregator-ci/tasks/build-docker-image/task.yml
    input_mapping:
      source-repo: loggregator-tools
    params:
      BASE_PACKAGE: code.cloudfoundry.org/loggregator-tools
      SUB_PACKAGE: logspinner
      IMAGE_NAME: logspinner
  - put: logspinner-image
    params:
      build: build-image/build
      tag: build-image/tag
      tag_as_latest: true
      cache: true
      cache_tag: latest

- name: log-cache-emitter
  plan:
  - aggregate:
    - get: log-cache-emitter-image-docker-build-context
      trigger: true
    - get: loggregator-tools
      trigger: true
    - get: loggregator-ci
  - task: build-image
    file: loggregator-ci/tasks/build-docker-image/task.yml
    input_mapping:
      source-repo: loggregator-tools
    params:
      BASE_PACKAGE: code.cloudfoundry.org/loggregator-tools
      SUB_PACKAGE: log-cache-emitter
      IMAGE_NAME: log-cache-emitter
  - put: log-cache-emitter-image
    params:
      build: build-image/build
      tag: build-image/tag
      tag_as_latest: true
      cache: true
      cache_tag: latest

- name: certs
  plan:
  - get: certs-image-docker-build-context
    trigger: true
  - put: certs-image
    params:
      build: certs-image-docker-build-context/docker-images/certs
      tag_as_latest: true
      cache_tag: latest

- name: fluentd
  plan:
  - get: fluentd-image-docker-build-context
    trigger: true
  - put: fluentd-image
    params:
      build: fluentd-image-docker-build-context/docker-images/fluentd
      tag_as_latest: true
      cache_tag: latest
