resources:
- name: datadog-firehose-nozzle-release
  type: git
  source: &datadog-firehose-nozzle-release
    uri: https://github.com/datadog/datadog-firehose-nozzle-release.git
    branch: master

- name: deployments-loggregator
  type: git
  source: &deployments_loggregator
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

- name: loggregator-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-ci
    branch: master
    private_key: {{cf-loggregator-oauth-bot-key}}

jobs:
- name: deploy-datadog-nozzle
  serial: true
  plan:
  - aggregate:
    - get: datadog-firehose-nozzle-release
    - get: deployments-loggregator
    - get: loggregator-ci
  - task: upload-release
    file: loggregator-ci/tasks/upload-release/task.yml
    params:
      BBL_STATE_DIR: gcp/coconut-bbl
      CREATE_RELEASE: false
    input_mapping:
      bbl-state: deployments-loggregator
      bosh-release-dir: datadog-firehose-nozzle-release
  - task: deploy
    file: loggregator-ci/tasks/bosh-deploy/task.yml
    params:
      BBL_STATE_DIR: gcp/coconut-bbl
      DEPLOYMENT_NAME: datadog
      MANIFEST_FILE: templates/datadog-bosh2.yml
      OPS_FILES: gcp/coconut-bbl/ops-files/datadog.yml
      VARS_FILES: gcp/coconut-bbl/vars-files/datadog.yml
      VARS_STORE_FILE: null
    input_mapping:
      bbl-state: deployments-loggregator
      bosh-release: datadog-firehose-nozzle-release
      ops-files: deployments-loggregator
      vars-files: deployments-loggregator
      vars-store: deployments-loggregator
