resources:
- name: datadog-firehose-nozzle-release
  type: git
  source:
    uri: https://github.com/datadog/datadog-firehose-nozzle-release.git
    branch: master

- name: loggregator-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-ci
    branch: master
    private_key: {{cf-loggregator-oauth-bot-key}}

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    tag_filter: v*

- name: 24h
  type: time
  source:
    interval: 24h

jobs:
- name: deploy-datadog-nozzle
  serial: true
  plan:
  - in_parallel:
    - get: datadog-firehose-nozzle-release
    - get: bbl-state
      resource: deployments-loggregator
    - get: loggregator-ci
    - get: 24h
      trigger: true
    - get: cf-deployment-concourse-tasks
  - task: prepare-ops-and-vars-files
    file: loggregator-ci/tasks/prepare-datadog-ops-and-vars/task.yml
    params:
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
      SYSTEM_DOMAIN: ((acceptance_system_domain))
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
  - task: deploy-standalone
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      vars-store: bbl-state
      cf-deployment: datadog-firehose-nozzle-release
    params:
      BBL_STATE_DIR: ((acceptance_bbl_state_dir))
      DEPLOYMENT_NAME: datadog
      MANIFEST_FILE: templates/datadog-bosh2.yml
      OPS_FILES: datadog.yml
      VARS_FILES: datadog.yml
      VARS_STORE_FILE: null
      SYSTEM_DOMAIN: ((acceptance_system_domain))
