---
resource_types:
- name: pcf-pool
  source:
    repository: cftoolsmiths/toolsmiths-envs-resource
  type: docker-image

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:
- name: 5m
  type: time
  source:
    interval: 5m

- name: 24h
  type: time
  source:
    interval: 24h

- name: cf-acceptance-tests
  type: git
  source:
    branch: main
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    tag_filter: v*

- name: loggregator-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-ci
    branch: master
    private_key: ((cf-loggregator-oauth-bot-key))

- name: loggregator-release-elect
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-release.git
    branch: release-elect
    private_key: ((cf-loggregator-oauth-bot-key))
    ignore_paths:
      - .final_builds
      - releases

- name: loggregator-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-release.git
    branch: develop
    private_key: ((cf-loggregator-oauth-bot-key))
    ignore_paths:
      - .final_builds
      - releases

- name: loggregator-release-main
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-release.git
    branch: main
    private_key: ((cf-loggregator-oauth-bot-key))
    disable_ci_skip: true

- name: cf-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-deployment.git
    branch: main
    private_key: ((cf-loggregator-oauth-bot-key))

- name: cf-env
  type: pcf-pool
  source:
    api_token: ((toolsmith-api-key))
    hostname: environments.toolsmiths.cf-app.com
    pool_name: cf-deployment
  tags:
  - cf-denver-shared-vsphere

- name: log-egrets-channel
  type: slack-notification
  source:
    url: ((slack-url))

jobs:
- name: loggregator-tests
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: loggregator-ci
    - get: 24h
      trigger: true
    - get: loggregator-release
      trigger: true
  - task: run-tests
    file: loggregator-ci/tasks/go-test/task.yml
    input_mapping:
      source-repo: loggregator-release

  - task: commit
    file: loggregator-ci/tasks/commit/task.yml
    input_mapping:
      release-repo: tested-source
    output_mapping:
      committed-repo: committed-loggregator-release
    params:
      COMMIT_MESSAGE: "Bump modules"
  - put: loggregator-release
    params:
      repository: committed-loggregator-release
      rebase: true

- name: claim-cf-env
  plan:
  - get: loggregator-release
    passed: ["loggregator-tests"]
    trigger: true
  - put: cf-env
    tags:
    - cf-denver-shared-vsphere
    params:
      action: claim

- name: cf-deploy
  serial: true
  plan:
  - get: cf-env
    passed:
    - claim-cf-env
    tags:
    - cf-denver-shared-vsphere
  - get: loggregator-release
    trigger: true
    passed:
    - claim-cf-env
  - get: cf-deployment
  - get: cf-deployment-concourse-tasks
  - task: make-loggregator-manifest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          tag: latest
      inputs:
      - name: cf-env
      outputs:
      - name: loggregator-manifest
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -eo pipefail
          eval "$(bbl print-env --metadata-file cf-env/metadata)"
          bosh -d cf manifest > loggregator-manifest/manifest.yml

  - task: deploy-loggregator
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      cf-deployment: loggregator-manifest
      toolsmiths-env: cf-env
      release: loggregator-release
      ops-files: cf-deployment
      vars-files: cf-deployment
    params:
      MANIFEST_FILE: manifest.yml

- name: system-health
  serial: true
  serial_groups:
  - bosh-cf-cats
  plan:
  - get: cf-env
    passed:
    - cf-deploy
    tags:
    - cf-denver-shared-vsphere
  - get: cf-deployment-concourse-tasks
  - get: loggregator-ci
  - get: loggregator-release
    trigger: true
    passed:
    - cf-deploy
  - task: ensure-system-health
    file: loggregator-ci/tasks/system-health/task.yml
    input_mapping:
      toolsmiths-env: cf-env
    on_failure:
      put: log-egrets-channel
      params:
        text: "system health sad"

- name: cats
  serial: true
  serial_groups:
  - bosh-cf-cats
  plan:
  - get: cf-env
    passed:
    - system-health
    tags:
    - cf-denver-shared-vsphere
  - get: cf-deployment-concourse-tasks
  - get: cf-acceptance-tests
  - get: loggregator-ci
  - get: loggregator-release
    trigger: true
    passed:
    - system-health
  - task: generate-config
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      toolsmiths-env: cf-env
      integration-configs: loggregator-ci
    params:
      CATS_INTEGRATION_CONFIG_FILE: cats-config.json
  - task: run-cats
    file: cf-deployment-concourse-tasks/run-cats/task.yml
    input_mapping:
      integration-config: updated-integration-configs
    params:
      CONFIG_FILE_PATH: cats-config.json

- name: unclaim-cf-env
  plan:
  - get: cf-env
    passed: ["cats"]
    trigger: true
    tags:
      - cf-denver-shared-vsphere
  - put: cf-env
    tags:
      - cf-denver-shared-vsphere
    params:
      env_file: cf-env/metadata
      action: unclaim

- name: loggregator-promotion
  serial: true
  plan:
  - in_parallel:
    - get: develop
      resource: loggregator-release
      trigger: true
      passed:
      - cats
    - get: loggregator-release-elect
  - put: loggregator-release-elect
    params:
      repository: develop

- name: loggregator-main-promotion
  serial: true
  plan:
  - in_parallel:
    - get: 5m
      trigger: true
    - get: loggregator-release-elect
      passed: ["loggregator-promotion"]
      trigger: true
    - get: loggregator-release-main
    - get: loggregator-ci
  - task: bumper
    file: loggregator-ci/tasks/bumper/task.yml
    input_mapping:
      source: loggregator-release-elect
      dest: loggregator-release-main
    params:
      SOURCE_BRANCH: release-elect
      DEST_BRANCH: main
      TRACKER_API_TOKEN: ((tracker-api-token))
  - put: loggregator-release-main
    params:
      repository: merged-dest

