resources:
- name: loggregator-ci
  type: git
  source:
    branch: product-pipelines
    uri: git@github.com:cloudfoundry/loggregator-ci.git
    private_key: ((loggregator-key))

- name: loggregator-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-release.git
    branch: &release-branch master
    private_key: ((loggregator-key))

- name: loggregator-release-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-release.git
    branch: develop
    private_key: ((loggregator-key))

- name: loggregator-github-release-drafts
  type: github-release
  source:
    user: cloudfoundry
    repository: loggregator-release
    access_token: ((access-token))
    drafts: true

jobs:
- name: loggregator-create-release
  serial: true
  plan:
  - aggregate:
    - get: loggregator-release
    - get: loggregator-release-develop
    - get: loggregator-ci
  - task: create-release
    file: loggregator-ci/tasks/loggregator-create-release/task.yml
    input_mapping:
      from-repo: loggregator-release
      dest-repo: loggregator-release-develop
    params:
      S3_ACCESS_KEY: ((s3-access-key-id))
      S3_SECRET_KEY: ((s3-secret-access-key))
      BLOBSTORE_BUCKET: loggregator-release-blobs
      SSH_KEY: ((loggregator-key))
      NEW_VERSION: "102.2"
      RELEASE_NAME: "Loggregator"
      FROM_BRANCH: *release-branch
      CHERRY_PICK_BRANCH: develop
  - put: loggregator-release-develop
    params:
      rebase: false
  - put: loggregator-release
    params:
      rebase: false
  - put: loggregator-github-release-drafts
    params:
      name: github-release/name
      tag: github-release/tag
      body: github-release/body
      globs:
      - github-release/*.tgz
