resources:
- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment
    branch: master

- name: deployments-loggregator
  type: git
  source: &deployments_loggregator
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

# This is here because concourse has a bug in which putting to a git resource
# creates a new version that can trigger jobs even if the commit has [ci skip]
# present.
- name: deployments-loggregator-with-changes
  type: git
  source: *deployments_loggregator

- name: loggregator-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-ci
    branch: master
    private_key: {{deployments-loggregator-key}}

jobs:
- name: create-bosh-lite
  serial_groups:
  - bosh-lite
  plan:
  - aggregate:
    - get: bosh-deployment
    - get: deployments-loggregator
      resource: deployments-loggregator-with-changes
      passed: ['delete-bosh-lite']
      trigger: true
    - get: loggregator-ci
  - task: create-bosh-lite
    config:
    file: loggregator-ci/tasks/create-bosh-lite.yml
    params:
      deploy_dir: deployments-loggregator/gcp/loggregator-lite
      subnet_prefix: 10.100.0
      subnetwork: bosh-lite
  - task: commit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: loggregator/base
      inputs:
      - name: updated-deployments-loggregator
      outputs:
      - name: committed-deployments-loggregator
      params:
        SOURCE: updated-deployments-loggregator
        PATHS: gcp/loggregator-lite
        COMMIT_MESSAGE: "Create bosh-lite GCP director"
        OUTPUT: committed-deployments-loggregator
      run:
        path: bash
        args:
        - -c
        - {{commit}}
  - put: deployments-loggregator-with-changes
    params:
      repository: committed-deployments-loggregator
      rebase: true

- name: delete-bosh-lite
  serial_groups:
  - bosh-lite
  plan:
  - aggregate:
    - get: bosh-deployment
    - get: deployments-loggregator
    - get: loggregator-ci
  - task: delete-bosh-lite
    file: loggregator-ci/tasks/destroy-bosh-lite.yml
    params:
      deploy_dir: deployments-loggregator/gcp/loggregator-lite
      subnet_prefix: 10.100.0
      subnetwork: bosh-lite
  - task: commit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: loggregator/base
      inputs:
      - name: updated-deployments-loggregator
      outputs:
      - name: committed-deployments-loggregator
      params:
        SOURCE: updated-deployments-loggregator
        PATHS: gcp/loggregator-lite
        COMMIT_MESSAGE: "Delete bosh-lite GCP director"
        OUTPUT: committed-deployments-loggregator
      run:
        path: bash
        args:
        - -c
        - {{commit}}
  - put: deployments-loggregator-with-changes
    params:
      repository: committed-deployments-loggregator
      rebase: true

