groups:
- name: main
  jobs:
  - cf-deploy
  - log-cache-blackbox
  - cf-destroy
- name: director-lifecycle
  jobs:
  - bbl-create
  - bbl-destroy

resources:
- name: 10m
  type: time
  source: {interval: 10m}

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    branch: v4.21

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: develop

- name: log-cache-release
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/log-cache-release
    branch: master

- name: loggregator
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-release
    branch: release-elect

- name: loggregator-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci

- name: loggregator-tools
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/loggregator-tools

- name: statsd-injector-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/statsd-injector-release
    branch: master

- name: cf-syslog-drain-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-syslog-drain-release
    branch: release-elect

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

- name: weekday-before-work
  type: time
  source:
    start: 7:00 AM
    stop: 8:00 AM
    location: America/Denver
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]

- name: weekday-after-work
  type: time
  source:
    start: 6:00 PM
    stop: 7:00 PM
    location: America/Denver
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]

jobs:
- name: bbl-create
  public: false
  plan:
  - get: cf-deployment-concourse-tasks
    trigger: false
  - get: bbl-state
    resource: deployments-loggregator
    trigger: false
  - get: ops-files
    resource: bosh-deployment
    trigger: false
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: service-account.key.json
      BBL_GCP_PROJECT_ID: cff-loggregator
      BBL_GCP_ZONE: us-central1-a
      BBL_GCP_REGION: us-central1
      BBL_STATE_DIR: gcp/playground
      BBL_IAAS: gcp
      BBL_LB_CERT: {{coconut_bbl_lb_cert}}
      BBL_LB_KEY: {{coconut_bbl_lb_key}}
      BBL_ENV_NAME: playground
      LB_DOMAIN: playground.loggr.cf-app.com
      OPS_FILES: "local-dns.yml"
  - put: deployments-loggregator
    params:
      repository: updated-bbl-state
      rebase: true

- name: bbl-destroy
  public: false
  plan:
  - get: cf-deployment-concourse-tasks
    trigger: false
  - get: bbl-state
    resource: deployments-loggregator
    trigger: false
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: gcp/playground
  - put: deployments-loggregator
    params:
      repository: updated-bbl-state
      rebase: true

- name: cf-deploy
  public: false
  serial_groups: ["deployment"]
  plan:
  - get: weekday-before-work
    trigger: true
  - aggregate:
    - get: bbl-state
      resource: deployments-loggregator
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: vars-store
      resource: deployments-loggregator
    - get: vars-files
      resource: deployments-loggregator
    - get: loggregator
    - get: cf-syslog-drain-release
    - get: statsd-injector-release
    - get: log-cache-release
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    params:
      BBL_STATE_DIR: gcp/playground
  - task: upload-releases
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
      inputs:
      - name: bbl-state
      - name: loggregator
      - name: statsd-injector-release
      - name: cf-syslog-drain-release
      - name: log-cache-release
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash

          set -ex

          pushd bbl-state/gcp/playground
            export BOSH_CLIENT=`bbl director-username`
            export BOSH_CLIENT_SECRET=`bbl director-password`
            export BOSH_CA_CERT=`bbl director-ca-cert`
            export BOSH_ENVIRONMENT=`bbl director-address`
          popd

          releases="loggregator cf-syslog-drain-release statsd-injector-release log-cache-release"
          for rel in $releases; do
            pushd $rel
              bosh create-release
              bosh upload-release --rebase
            popd
          done
  - task: copy-ops-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
      inputs:
      - name: bbl-state
      - name: cf-deployment
      - name: log-cache-release
      outputs:
      - name: ops-files
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -x

          cp cf-deployment/operations/scale-to-one-az.yml ops-files/
          cp cf-deployment/operations/experimental/use-bosh-dns.yml ops-files/
          cp cf-deployment/operations/experimental/use-bosh-dns-for-containers.yml ops-files/
          cp bbl-state/gcp/playground/ops-files/*.yml ops-files/
          cp log-cache-release/manifests/operations/deploy-in-cf.yml ops-files/deploy-log-cache.yml
  - task: cf-deploy
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    params:
      BBL_STATE_DIR: gcp/playground
      SYSTEM_DOMAIN: playground.loggr.cf-app.com
      VARS_STORE_FILE: gcp/playground/deployment-vars.yml
      OPS_FILES: "scale-to-one-az.yml clients.yml allow-insecure-syslog-drains.yml cf-versions.yml use-bosh-dns.yml use-bosh-dns-for-containers.yml deploy-log-cache.yml enable-metrics-to-syslog.yml"
      VARS_FILES: gcp/playground/datadog-vars.yml
  - task: bosh-cleanup
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    params:
      BBL_STATE_DIR: gcp/playground
  - put: deployments-loggregator
    params:
      repository: updated-vars-store
      rebase: true

- name: cf-destroy
  serial_groups: ["deployment"]
  public: false
  plan:
  - get: weekday-after-work
    trigger: true
  - aggregate:
    - get: bbl-state
      resource: deployments-loggregator
    - get: cf-deployment-concourse-tasks
  - aggregate:
    - task: cf-deployment-destroy
      file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
      params:
        BBL_STATE_DIR: gcp/playground
        DEPLOYMENT_NAME: cf
    - task: cf-syslog-drain-destroy
      file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
      params:
        BBL_STATE_DIR: gcp/playground
        DEPLOYMENT_NAME: cf-syslog-drain

- name: log-cache-blackbox
  public: false
  serial: true
  plan:
  - aggregate:
    - get: loggregator-tools
    - get: loggregator-ci
    - get: 10m
      trigger: true
  - task: log-cache-blackbox-tests
    file: loggregator-ci/tasks/log-cache-blackbox/task.yml
    params:
      APP_DOMAIN: "log-cache-blackbox.playground.loggr.cf-app.com"
      APP_NAME: "log-cache-blackbox"
      SYSTEM_DOMAIN: "playground.loggr.cf-app.com"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      LOG_CACHE_ADDR: http://log-cache.playground.loggr.cf-app.com
      ORG: system
      SPACE: blackbox-testing
      SKIP_SSL_VALIDATION: true
      USERNAME: {{playground-username}}
      PASSWORD: {{playground-password}}
      UAA_CLIENT: {{playground-uaa-client}}
      UAA_CLIENT_SECRET: {{playground-uaa-client-secret}}
  - task: push-datadog-accumulator
    file: loggregator-ci/tasks/log-cache-datadog-accumulator/task.yml
    params:
      APP_DOMAIN: "log-cache-blackbox.playground.loggr.cf-app.com"
      APP_NAME: "log-cache-data-dog-accumulator"
      SYSTEM_DOMAIN: "playground.loggr.cf-app.com"
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      LOG_CACHE_ADDR: http://log-cache.playground.loggr.cf-app.com
      ORG: system
      SPACE: blackbox-testing
      SKIP_SSL_VALIDATION: true
      USERNAME: {{playground-username}}
      PASSWORD: {{playground-password}}
      UAA_CLIENT: {{playground-uaa-client}}
      UAA_CLIENT_SECRET: {{playground-uaa-client-secret}}
