resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    branch: v6.9

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: ((deployments-loggregator-key))

- name: bosh-bootloader
  type: git
  source:
    uri: https://github.com/loggregator/bosh-bootloader
    branch: master

- name: create-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/loggregator-locks.git
    branch: master
    pool: create
    private_key: ((cf-loggregator-oauth-bot-key))

- name: destroy-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/loggregator-locks.git
    branch: master
    pool: destroy
    private_key: ((cf-loggregator-oauth-bot-key))

- name: environments-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/loggregator-locks.git
    branch: master
    pool: environments
    private_key: ((cf-loggregator-oauth-bot-key))

- name: loggregator-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-ci.git
    branch: master
    private_key: ((cf-loggregator-oauth-bot-key))

jobs:
- name: bbl-create
  public: false
  plan:
  - put: create-pool
    params: {acquire: true}
  - aggregate:
    - get: loggregator-ci
    - get: cf-deployment-concourse-tasks
    - get: deployments-loggregator
    - get: bosh-bootloader
  - task: create-director
    input_mapping:
      bbl-state: deployments-loggregator
      bbl-config: bosh-bootloader
      environment: create-pool
    output_mapping:
      updated-bbl-state: updated-deployments-loggregator
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: gcp/service-account.key.json
      BBL_GCP_PROJECT_ID: cff-loggregator
      BBL_GCP_ZONE: us-central1-a
      BBL_GCP_REGION: us-central1
      BBL_IAAS: gcp
      BBL_LB_CERT: ((coconut_bbl_lb_cert))
      BBL_LB_KEY: ((coconut_bbl_lb_key))
      BBL_CONFIG_DIR: plan-patches/iso-segs-gcp
    file: loggregator-ci/tasks/bbl-up-from-pool/task.yml
  - put: deployments-loggregator
    params:
      repository: updated-deployments-loggregator
      rebase: true
  - task: configure-dns
    input_mapping:
      bbl-state: updated-deployments-loggregator
      environment: create-pool
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: gcp/service-account.key.json
      GCP_DNS_ZONE: loggr
      GCP_LB_DOMAIN: loggr.cf-app.com
    file: loggregator-ci/tasks/gcp-set-nameservers/task.yml
  - put: environments-pool
    params: {add: create-pool}
  - put: create-pool
    params: {remove: create-pool}

- name: bbl-destroy
  public: false
  plan:
  - put: destroy-pool
    params: {acquire: true}
  - aggregate:
    - get: loggregator-ci
    - get: cf-deployment-concourse-tasks
    - get: deployments-loggregator
  - task: delete-deployments
    file: loggregator-ci/tasks/env-pool-tasks/bosh-delete-all-deployments.yml
    input_mapping:
      environment: destroy-pool
      bbl-state: deployments-loggregator
  - task: bbl-destroy
    file: loggregator-ci/tasks/bbl-destroy-from-pool/task.yml
    input_mapping:
      bbl-state: deployments-loggregator
      environment: destroy-pool
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: gcp/service-account.key.json
      GIT_COMMIT_USERNAME: Loggregator CI
      GIT_COMMIT_EMAIL: "cf-loggregator@pivotal.io"
  - put: deployments-loggregator
    params:
      repository: updated-bbl-state
      rebase: true
  - put: destroy-pool
    params: {remove: destroy-pool}
