resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    branch: v6.9

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

- name: create-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/loggregator-locks.git
    branch: master
    pool: create
    private_key: {{cf-loggregator-oauth-bot-key}}

- name: pipeline-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/loggregator-locks.git
    branch: master
    pool: pipelines
    private_key: {{cf-loggregator-oauth-bot-key}}

- name: loggregator-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator-ci.git
    branch: master
    private_key: {{cf-loggregator-oauth-bot-key}}

jobs:
- name: bbl-create
  public: false
  serial: true
  plan:
  - put: create-pool
    params: {acquire: true}
  - aggregate:
    - get: loggregator-ci
    - get: cf-deployment-concourse-tasks
    - get: deployments-loggregator
  - task: create-director
    input_mapping:
      bbl-state: deployments-loggregator
      bbl-config: deployments-loggregator
      environment: create-pool
    output_mapping:
      updated-bbl-state: updated-deployments-loggregator
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: gcp/service-account.key.json
      BBL_GCP_PROJECT_ID: cff-loggregator
      BBL_GCP_ZONE: us-central1-a
      BBL_GCP_REGION: us-central1
      BBL_IAAS: gcp
      BBL_LB_CERT: {{coconut_bbl_lb_cert}}
      BBL_LB_KEY: {{coconut_bbl_lb_key}}
    file: loggregator-ci/tasks/bbl-up-from-pool/task.yml
  - put: deployments-loggregator
    params:
      repository: updated-deployments-loggregator
  - task: configure-dns
    input_mapping:
      bbl-state: updated-deployments-loggregator
      environment: create-pool
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: gcp/service-account.key.json
      GCP_DNS_ZONE: loggr
      GCP_LB_DOMAIN: loggr.cf-app.com
    file: loggregator-ci/tasks/gcp-set-nameservers/task.yml
  - put: pipeline-pool
    params: {add: create-pool}
  - put: create-pool
    params: {remove: create-pool}
