resources:
- name: 15m
  type: time
  source: {interval: 15m}
- name: 1h
  type: time
  source: {interval: 1h}
- name: loggregator-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
- name: scalable-syslog
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/scalable-syslog

jobs:
- name: floodspinner
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: 15m
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/generic-smoke-test.yml
    params:
      CF_API: "api.run.pivotal.io"
      APP_DOMAIN: "floodspinner.cfapps.io"
      ORG: "cf-lamb"
      SPACE: "development"
      APP_NAME: "floodspinner"
      USERNAME: {{pws-username}}
      PASSWORD: {{pws-password}}

      WAIT: 60
      CYCLES: 10000
      DATADOG_API_KEY: {{datadog-prod-api-key}}
      DELAY: "2"
      DELAY_UNIT: "us"
      MESSAGE: "FIFTEEN-MINUTE"

- name: dripspinner
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: 1h
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/generic-smoke-test.yml
    params:
      CF_API: "api.run.pivotal.io"
      APP_DOMAIN: "dripspinner.cfapps.io"
      ORG: "cf-lamb"
      SPACE: "development"
      APP_NAME: "dripspinner"
      USERNAME: {{pws-username}}
      PASSWORD: {{pws-password}}

      WAIT: 600
      CYCLES: 1000
      DATADOG_API_KEY: {{datadog-prod-api-key}}
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
