resources:
- name: 15m
  type: time
  source: {interval: 15m}
- name: 1h
  type: time
  source: {interval: 1h}
- name: loggregator-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
- name: scalable-syslog-release
  type: git
  source:
    uri: https://code.cloudfoundry.org/scalable-syslog-release

jobs:
- name: floodspinner
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: 15m
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/generic-smoke-test.yml
    params:
      CF_API: "api.eu-pws.pivotal.io"
      APP_DOMAIN: "floodspinner.eu-pwsapps.io"
      ORG: "system"
      SPACE: "loggregator-team"
      APP_NAME: "floodspinner"
      USERNAME: {{pws-eu-username}}
      PASSWORD: {{pws-eu-password}}
      WAIT: 60
      CYCLES: 10000
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DELAY: "2"
      DELAY_UNIT: "us"
      MESSAGE: "FIFTEEN-MINUTE"

- name: dripspinner
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: 1h
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/generic-smoke-test.yml
    params:
      CF_API: "api.eu-pws.pivotal.io"
      APP_DOMAIN: "dripspinner.eu-pwsapps.io"
      ORG: "system"
      SPACE: "loggregator-team"
      APP_NAME: "dripspinner"
      USERNAME: {{pws-eu-username}}
      PASSWORD: {{pws-eu-password}}
      WAIT: 600
      CYCLES: 1000
      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"

- name: https-syslog-drain
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: scalable-syslog-release
  - get: 1h
    trigger: true
  - task: v1-drain
    file: loggregator-ci/tasks/scalable-syslog-smoke-test.yml
    params:
      CF_SYSTEM_DOMAIN: "eu-pws.pivotal.io"
      CF_USERNAME: {{pws-eu-username}}
      CF_PASSWORD: {{pws-eu-password}}
      CF_APP_DOMAIN: "eu-pwsapps.io"
      CF_ORG: "system"
      CF_SPACE: "loggregator-team"

      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DRAIN_VERSION: "1.0"
      DRAIN_TYPE: "https"
      METRIC_PREFIX: ""
  - task: v2-drain
    file: loggregator-ci/tasks/scalable-syslog-smoke-test.yml
    params:
      CF_SYSTEM_DOMAIN: "eu-pws.pivotal.io"
      CF_USERNAME: {{pws-eu-username}}
      CF_PASSWORD: {{pws-eu-password}}
      CF_APP_DOMAIN: "eu-pwsapps.io"
      CF_ORG: "system"
      CF_SPACE: "loggregator-team"

      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DRAIN_VERSION: "2.0"
      DRAIN_TYPE: "https"
      METRIC_PREFIX: ""

- name: tcp-syslog-drain
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: scalable-syslog-release
  - get: 1h
    trigger: true
  - task: v1-drain
    file: loggregator-ci/tasks/scalable-syslog-smoke-test.yml
    params:
      CF_SYSTEM_DOMAIN: "eu-pws.pivotal.io"
      CF_USERNAME: {{pws-eu-username}}
      CF_PASSWORD: {{pws-eu-password}}
      CF_APP_DOMAIN: "eu-pwsapps.io"
      CF_ORG: "system"
      CF_SPACE: "loggregator-team"

      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DRAIN_VERSION: "1.0"
      DRAIN_TYPE: "syslog"
      METRIC_PREFIX: ""
  - task: v2-drain
    file: loggregator-ci/tasks/scalable-syslog-smoke-test.yml
    params:
      CF_SYSTEM_DOMAIN: "eu-pws.pivotal.io"
      CF_USERNAME: {{pws-eu-username}}
      CF_PASSWORD: {{pws-eu-password}}
      CF_APP_DOMAIN: "eu-pwsapps.io"
      CF_ORG: "system"
      CF_SPACE: "loggregator-team"

      DATADOG_API_KEY: {{datadog-loggregator-api-key}}
      DRAIN_VERSION: "2.0"
      DRAIN_TYPE: "syslog"
      METRIC_PREFIX: ""
