resources:
- name: weekly
  source:
    days:
    - Monday
    interval: 23h
    location: America/Denver
    start: 2:00 AM
    stop: 3:00 AM
  type: time

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

jobs:
- name: recreate-concourse-workers
  plan:
  - get: weekly
    trigger: true
  - get: bbl-state
    resource: deployments-loggregator
  - task: recreate
    config:
      image_resource:
        type: docker-image
        source:
          repository: loggregator/base
      platform: linux
      inputs:
      - name: bbl-state
      params:
        BBL_STATE_DIR: ((concourse_bbl_state_dir))
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          set -e
          pushd "bbl-state/${BBL_STATE_DIR}" > /dev/null
            eval "$(bbl print-env)"
          popd > /dev/null

          bosh -n -d concourse recreate worker