groups:
- name: main
  jobs:
  - run-regression-test
  - cf-destroy
- name: director-lifecycle
  jobs:
  - bbl-create
  - bbl-destroy

resources:
- name: loggregator-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/loggregator-ci

- name: cats-concourse-task
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cats-concourse-task

- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    branch: v4.21

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: develop

- name: loggregator-release-99
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-release
    branch: v99.x

- name: loggregator-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-release
    branch: release-elect

- name: cf-syslog-drain-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-syslog-drain-release
    branch: release-elect

- name: capi-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/capi-release
    branch: ci-passed

- name: diego-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/diego-release
    branch: release-candidate

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

jobs:
- name: bbl-create
  public: false
  plan:
  - get: cf-deployment-concourse-tasks
    trigger: false
  - get: bbl-state
    resource: deployments-loggregator
    trigger: false
  - get: ops-files
    resource: bosh-deployment
    trigger: false
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: service-account.key.json
      BBL_GCP_PROJECT_ID: cff-loggregator
      BBL_GCP_ZONE: us-central1-a
      BBL_GCP_REGION: us-central1
      BBL_STATE_DIR: gcp/regression
      BBL_IAAS: gcp
      BBL_LB_CERT: {{coconut_bbl_lb_cert}}
      BBL_LB_KEY: {{coconut_bbl_lb_key}}
      BBL_ENV_NAME: regression
      LB_DOMAIN: regression.loggr.cf-app.com
      OPS_FILES: "local-dns.yml"
  - put: deployments-loggregator
    params:
      repository: updated-bbl-state
      rebase: true

- name: bbl-destroy
  public: false
  plan:
  - get: cf-deployment-concourse-tasks
    trigger: false
  - get: bbl-state
    resource: deployments-loggregator
    trigger: false
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: gcp/regression
  - put: deployments-loggregator
    params:
      repository: updated-bbl-state
      rebase: true

- name: run-regression-test
  public: false
  serial_groups: ["deployment"]
  plan:
  - aggregate:
    - get: deployments-loggregator
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: cf-syslog-drain-release
    - get: loggregator-ci
    - get: cats-concourse-task
    - get: cf-acceptance-tests
    - get: loggregator-release-99
      trigger: true
    - get: capi-release
      trigger: true
    - get: diego-release
      trigger: true
    - get: loggregator-release
      trigger: true
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    input_mapping:
      bbl-state: deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/regression
  - aggregate:
    - task: upload-loggregator-99
      file: loggregator-ci/tasks/upload-release/task.yml
      input_mapping:
        bbl-state: deployments-loggregator
        bosh-release-dir: loggregator-release-99
      params:
        BBL_STATE_DIR: gcp/regression
        NO_REBASE: true
    - task: upload-cf-syslog-drain
      file: loggregator-ci/tasks/upload-release/task.yml
      input_mapping:
        bbl-state: deployments-loggregator
        bosh-release-dir: cf-syslog-drain-release
      params:
        BBL_STATE_DIR: gcp/regression
    - task: upload-capi
      file: loggregator-ci/tasks/upload-release/task.yml
      input_mapping:
        bbl-state: deployments-loggregator
        bosh-release-dir: capi-release
      params:
        BBL_STATE_DIR: gcp/regression
    - task: upload-diego
      file: loggregator-ci/tasks/upload-release/task.yml
      input_mapping:
        bbl-state: deployments-loggregator
        bosh-release-dir: diego-release
      params:
        BBL_STATE_DIR: gcp/regression
  - task: copy-ops-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
      inputs:
      - name: deployments-loggregator
      - name: cf-deployment
      outputs:
      - name: ops-files
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -x

          cp cf-deployment/operations/scale-to-one-az.yml ops-files/
          cp cf-deployment/operations/experimental/use-bosh-dns.yml ops-files/
          cp deployments-loggregator/gcp/regression/ops-files/*.yml ops-files/
  - task: cf-deploy
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      vars-store: deployments-loggregator
      vars-files: deployments-loggregator
      bbl-state: deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/regression
      SYSTEM_DOMAIN: regression.loggr.cf-app.com
      VARS_STORE_FILE: gcp/regression/deployment-vars.yml
      OPS_FILES: "scale-to-one-az.yml clients.yml allow-insecure-syslog-drains.yml cf-versions.yml use-bosh-dns.yml enable-metrics-to-syslog.yml disable-doppler-etcd.yml versions.yml"
      VARS_FILES: gcp/regression/datadog-vars.yml
  - task: bosh-cleanup
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    input_mapping:
      bbl-state: deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/regression
  - put: deployments-loggregator
    params:
      repository: updated-vars-store
      rebase: true
  - task: run-cats
    file: cats-concourse-task/task.yml
    input_mapping:
      integration-config: deployments-loggregator
    params:
      CONFIG_FILE_PATH: gcp/regression/cats-config.json
      NODES: 6
  - task: upload-loggregator
    file: loggregator-ci/tasks/upload-release/task.yml
    input_mapping:
      bbl-state: deployments-loggregator
      bosh-release-dir: loggregator-release
    params:
      BBL_STATE_DIR: gcp/regression
      NO_REBASE: true
  - task: cf-deploy
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      vars-store: deployments-loggregator
      vars-files: deployments-loggregator
      bbl-state: deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/regression
      SYSTEM_DOMAIN: regression.loggr.cf-app.com
      VARS_STORE_FILE: gcp/regression/deployment-vars.yml
      OPS_FILES: "scale-to-one-az.yml clients.yml allow-insecure-syslog-drains.yml cf-versions.yml use-bosh-dns.yml enable-metrics-to-syslog.yml disable-doppler-etcd.yml versions.yml"
      VARS_FILES: gcp/regression/datadog-vars.yml
  - task: run-cats
    file: cats-concourse-task/task.yml
    input_mapping:
      integration-config: deployments-loggregator
    params:
      CONFIG_FILE_PATH: gcp/regression/cats-config.json
      NODES: 6
  ensure:
    do:
    - task: delete-deployment
      file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
      input_mapping:
        bbl-state: deployments-loggregator
      params:
        BBL_STATE_DIR: gcp/regression
    - task: bosh-cleanup
      file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
      input_mapping:
        bbl-state: deployments-loggregator
      params:
        BBL_STATE_DIR: gcp/regression

- name: cf-destroy
  serial_groups: ["deployment"]
  public: false
  plan:
  - aggregate:
    - get: bbl-state
      resource: deployments-loggregator
    - get: cf-deployment-concourse-tasks
  - aggregate:
    - task: cf-deployment-destroy
      file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
      params:
        BBL_STATE_DIR: gcp/regression
        DEPLOYMENT_NAME: cf
    - task: cf-syslog-drain-destroy
      file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
      params:
        BBL_STATE_DIR: gcp/regression
        DEPLOYMENT_NAME: cf-syslog-drain
