resources:
- name: deployments-loggregator
  type: git
  source: &deployments_loggregator
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

- name: loggregator-develop
  type: git
  source: &loggregator_develop
    uri: git@github.com:cloudfoundry/loggregator.git
    branch: develop
    private_key: {{loggregator-key}}
    ignore_paths:
    - .final_builds
    - releases

- name: loggregator-master
  type: git
  source:
    disable_ci_skip: true
    uri: git@github.com:cloudfoundry/loggregator.git
    branch: master
    private_key: {{loggregator-key}}

- name: loggregator-final-release-develop
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator.git
    branch: develop
    private_key: {{loggregator-key}}
    ignore_paths:
    - .final_builds
    - releases

- name: loggregator-final-release-master
  type: git
  source:
    uri: git@github.com:cloudfoundry/loggregator.git
    branch: master
    private_key: {{loggregator-key}}
    ignore_paths:
    - .final_builds
    - releases

- name: loggregator-github-release-drafts
  type: github-release
  source:
    user: cloudfoundry
    repository: loggregator
    access_token: {{access-token}}
    drafts: true

- name: cf-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-release
    branch: develop
    private_key: {{cf-loggregator-oauth-bot-key}}

jobs:
- name: create-final-release
  serial: true
  plan:
  - aggregate:
    - get: loggregator-develop
      trigger: false
    - get: loggregator-master
      resource: loggregator-master
  - task: create-final-release
    config:
      image_resource:
        type: docker-image
        source:
        - repository: loggregator/bosh20
      platform: linux
      params:
        S3_ACCESS_KEY: {{s3-access-key}}
        S3_SECRET_KEY: {{s3-secret-key}}
        SSH_KEY: {{loggregator-key}}
        NEW_VERSION: 82
      inputs:
      - name: loggregator-develop
      - name: loggregator-master
      outputs:
      - name: github-release
      - name: create-final-release
      run:
        path: bash
        args:
          - -c
          - |
            #!/bin/bash
            set -ex

            # establish version/tag strings
            new_version="$NEW_VERSION"
            tag_name="v$new_version"

            # write out github release files
            echo "Loggregator $new_version" > github-release/name
            echo $tag_name > github-release/tag
            echo "TBD" > github-release/body

            # setup git for committing
            git config --global user.email "cf-loggregator@pivotal.io"
            git config --global user.name "Loggregator CI"

            # setup ssh for reading from github
            eval "$(ssh-agent -s)"
            mkdir -p ~/.ssh
            echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
            ssh-add <(echo "$SSH_KEY")

            # build final release on master
            pushd loggregator-master
              # this is needed to land commits on master since the commit for
              # master is checked out as a detatched head when the git
              # resource clones it down
              git checkout master

              # setup private.yml used by `create-release --final`
              cat << EOF > config/private.yml
            ---
            blobstore:
              provider: s3
              options:
                bucket_name: loggregator-release-blobs
                access_key_id: $S3_ACCESS_KEY
                secret_access_key: $S3_SECRET_KEY
                credentials_source: static
            EOF

              # create final release and commit artifcats
              bosh -n create-release --final \
                --tarball ../github-release/release.tgz \
                --version $new_version
              git add .
              git commit -m "Create final release\


            [ci skip]"

              final_release_abbrev=$(git rev-parse --abbrev-ref HEAD)
              final_release_sha=$(git rev-parse HEAD)
              git tag "$tag_name" $final_release_sha
            popd

            # merge final release artifacts with develop
            pushd loggregator-develop
              # this is needed to land commits on develop since the commit for
              # develop is checked out as a detatched head when the git
              # resource clones it down
              git checkout develop

              git remote add -f master-repo ../loggregator-master
              git pull
              git merge -v -m "Merge final release artifacts\


            [ci skip]" "master-repo/$final_release_abbrev"
            popd

            # copy repos into output
            cp -r loggregator-develop loggregator-master create-final-release
  - put: loggregator-final-release-master
    params:
      repository: create-final-release/loggregator-master
      rebase: false
  - put: loggregator-final-release-develop
    params:
      repository: create-final-release/loggregator-develop
      rebase: false
  - put: loggregator-github-release-drafts
    params:
      name: github-release/name
      tag: github-release/tag
      body: github-release/body
      globs:
      - github-release/*.tgz

- name: test-and-bump-cf-release
  plan:
    - get: loggregator-master
      resource: loggregator-final-release-master
      passed: [create-final-release]
    - get: cf-release
    - get: deployments-loggregator
    - task: bump-submodule
      config:
        image_resource:
          type: docker-image
          source:
          - repository: loggregator/bosh10
        platform: linux
        inputs:
        - name: loggregator-master
        - name: deployments-loggregator
        - name: cf-release
        outputs:
        - name: cf-release-bump
        run:
          path: bash
          args:
            - -c
            - |
              #!/bin/bash
              set -ex

              function canibump {
                res=$(curl canibump.cfapps.io -H "Accept: application/json")
                can_bump="{\"can_i_bump\":true}"

                if [ "${res}" != "${can_bump}" ]; then
                  echo "canibump.cfapps.io reported cf-release cannot be bumped"
                  echo "response ${can_bump}"
                  exit 1
                fi
              }
              canibump

              pushd loggregator-master
                LOGGREGATOR_SHA=$(git rev-parse HEAD)
              popd

              pushd cf-release/src/loggregator
                echo "Moving Loggregator in cf-release to ${LOGGREGATOR_SHA}"
                git checkout ${LOGGREGATOR_SHA}
                git submodule update --init --recursive
              popd

              password=$(cat deployments-loggregator/gcp/cf-release-bosh-lite/creds.yml |
                grep admin_password |
                awk '{print $2}')
              bosh -u admin -p "$password" target 10.102.0.6 lite
              bosh login admin "$password"

              pushd cf-release
                cat <<EOF > acceptance-stub.yml
              properties:
                acceptance_test:
                  default_timeout: 300
                  cf_push_timeout: 4
              EOF

                echo "Deploying Release to Bosh Lite"
                ./scripts/generate-bosh-lite-dev-manifest acceptance-stub.yml
                bosh --parallel 10 sync blobs
                bosh create release --name cf --force
                bosh -t 10.102.0.6 -n upload release --rebase
                bosh -t 10.102.0.6 -d bosh-lite/deployments/cf.yml -n deploy

                echo "Running CATs with most recent Loggregator"
                bosh -t 10.102.0.6 run errand acceptance_tests

                echo "Configuring Git"
                git config --global user.email "cf-loggregator@pivotal.io"
                git config --global user.name "Loggregator CI"
                git config --global alias.ci commit

                echo "Bumping loggregator SHA in cf-release"
                echo "New loggregator SHA is ${LOGGREGATOR_SHA}"
                git add src/loggregator

                echo "Commiting with shortlog"
                ./scripts/commit_with_shortlog
              popd

              rsync -ca cf-release/ cf-release-bump/

              canibump
    - put: cf-release
      params:
        rebase: true
        repository: cf-release-bump
