resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: loggregator-release-elect
    type: git
    source:
      uri: git@github.com:cloudfoundry/loggregator.git
      branch: release-elect
      private_key: {{loggregator-key}}
      ignore_paths:
        - .final_builds
        - releases

  - name: loggregator-develop
    type: git
    source:
      uri: git@github.com:cloudfoundry/loggregator.git
      branch: develop
      private_key: {{loggregator-key}}
      ignore_paths:
      - .final_builds
      - releases

  - name: loggregator-latest
    type: bosh-io-release
    source:
      repository: cloudfoundry/loggregator

  - name: scalable-syslog-release-elect
    type: git
    source:
      uri: git@github.com:cloudfoundry/scalable-syslog-release.git
      branch: release-elect
      private_key: {{loggregator-key}}
      ignore_paths:
      - .final_builds
      - releases

  - name: scalable-syslog-github-release
    type: github-release
    source:
      user: cloudfoundry
      repository: scalable-syslog-release
      access_token: {{access-token}}

  - name: consul-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/consul-release

  - name: deployments-loggregator
    type: git
    source: &deployments_loggregator
      uri: git@github.com:cloudfoundry/deployments-loggregator.git
      branch: master
      private_key: {{deployments-loggregator-key}}

  - name: deployments-loggregator-with-changes
    type: git
    source: *deployments_loggregator

  - name: cf-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-deployment
      branch: develop

  - name: cf-deployment-concourse-tasks
    type: git
    source:
      uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
      branch: v3.1

  - name: loggregator-ci
    type: git
    source:
      uri: https://github.com/cloudfoundry/loggregator-ci

  - name: pipeline-lock
    type: pool
    source:
      uri: git@github.com:cloudfoundry/loggregator-locks.git
      branch: master
      pool: release-elect-regression
      private_key: {{cf-loggregator-oauth-bot-key}}

  - name: 5m
    type: time
    source: {interval: 5m}

  - name: daily
    type: time
    source:
      start: 8:00 PM
      stop: 9:00 PM
      location: America/Denver

  - name: slack-alert
    type: slack-notification
    source:
      url: {{slack-bot-url}}

jobs:
- name: loggregator-elect-bbl-create
  plan:
  - get: cf-deployment-concourse-tasks
    trigger: false
  - get: bbl-state
    resource: deployments-loggregator
    trigger: false
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: service-account.key.json
      BBL_GCP_PROJECT_ID: cff-loggregator
      BBL_GCP_ZONE: us-central1-a
      BBL_GCP_REGION: us-central1
      BBL_STATE_DIR: gcp/loggregator-elect-bbl
      BBL_IAAS: gcp
      BBL_LB_CERT: {{coconut_director_cert}}
      BBL_LB_KEY: {{coconut_director_key}}
      BBL_ENV_NAME: loggregator-elect-bbl
      LB_DOMAIN: loggregator-elect.cf-app.com
  - put: deployments-loggregator-with-changes
    params:
      repository: updated-bbl-state
      rebase: true
- name: loggregator-elect-bbl-destroy
  plan:
  - get: cf-deployment-concourse-tasks
    trigger: false
  - get: bbl-state
    resource: deployments-loggregator
    trigger: false
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: gcp/loggregator-elect-bbl
  - put: deployments-loggregator-with-changes
    params:
      repository: updated-bbl-state
      rebase: true
- name: loggregator-latest-bbl-create
  plan:
  - get: cf-deployment-concourse-tasks
    trigger: false
  - get: bbl-state
    resource: deployments-loggregator
    trigger: false
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: service-account.key.json
      BBL_GCP_PROJECT_ID: cff-loggregator
      BBL_GCP_ZONE: us-central1-a
      BBL_GCP_REGION: us-central1
      BBL_STATE_DIR: gcp/loggregator-latest-bbl
      BBL_IAAS: gcp
      BBL_LB_CERT: {{coconut_director_cert}}
      BBL_LB_KEY: {{coconut_director_key}}
      BBL_ENV_NAME: loggregator-latest-bbl
      LB_DOMAIN: loggregator-latest.cf-app.com
  - put: deployments-loggregator-with-changes
    params:
      repository: updated-bbl-state
      rebase: true
- name: loggregator-latest-bbl-destroy
  plan:
  - get: cf-deployment-concourse-tasks
    trigger: false
  - get: bbl-state
    resource: deployments-loggregator
    trigger: false
  - task: bbl-destroy
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    params:
      BBL_STATE_DIR: gcp/loggregator-latest-bbl
  - put: deployments-loggregator-with-changes
    params:
      repository: updated-bbl-state
      rebase: true

- name: start-pipeline
  serial: true
  serial_groups: ["locking"]
  plan:
    - get: daily
      trigger: true
    - get: pipeline-lock
    - put: pipeline-lock
      params:
        claim: pipeline

- name: loggregator-elect-deploy
  serial: true
  serial_groups: ["loggregator-elect"]
  plan:
    - aggregate:
      - get: pipeline-lock
        passed: ["start-pipeline"]
        trigger: true
      - get: bbl-state
        resource: deployments-loggregator
      - get: cf-deployment
      - get: cf-deployment-concourse-tasks
      - get: release
        resource: loggregator-release-elect
      - get: vars-store
        resource: deployments-loggregator
      - get: vars-files
        resource: deployments-loggregator
      - get: consul-release
      - get: scalable-syslog-release-elect
    - do:
      - task: upload-stemcell
        file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
        params:
          BBL_STATE_DIR: gcp/loggregator-elect-bbl
      - task: copy-ops-files
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: ubuntu }
          inputs:
          - name: bbl-state
          - name: cf-deployment
          outputs:
          - name: ops-files
          run:
            path: /bin/bash
            args:
            - "-c"
            - |
              #!/bin/bash
              set -ex

              cp cf-deployment/operations/workarounds/use-4-azs-for-router.yml ops-files/
              cp bbl-state/gcp/loggregator-elect-bbl/ops-files/*.yml ops-files/

      - task: cf-deploy
        file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
        params:
          BBL_STATE_DIR: gcp/loggregator-elect-bbl
          SYSTEM_DOMAIN: loggregator-elect.cf-app.com
          VARS_STORE_FILE: gcp/loggregator-elect-bbl/deployment-vars.yml
          OPS_FILES: "clients.yml use-4-azs-for-router.yml"
      - task: deploy-scalable-syslog
        config:
          image_resource:
            type: docker-image
            source:
              repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          platform: linux
          inputs:
          - name: scalable-syslog-release-elect
          - name: consul-release
          - name: updated-vars-store
          outputs:
          - name: updated-deployments-loggregator
          params:
          run:
            path: bash
            args:
              - -c
              - |
                #!/bin/bash
                set -eux

                pushd updated-vars-store/gcp/loggregator-elect-bbl
                  export BOSH_CLIENT=`bbl director-username`
                  export BOSH_CLIENT_SECRET=`bbl director-password`
                  export BOSH_CA_CERT=`bbl director-ca-cert`
                  export BOSH_ENVIRONMENT=`bbl director-address`
                popd

                for release in $(find consul-release -name '*.tgz'); do
                  bosh upload-release $release
                done

                pushd scalable-syslog-release-elect
                  bosh create-release --force
                  bosh upload-release --rebase
                popd

                ss_dir="$PWD/scalable-syslog-release-elect"
                bbl_dir="updated-vars-store/gcp/loggregator-elect-bbl"

                bosh -n -d scalablesyslog deploy \
                  --vars-store "$bbl_dir/scalablesyslog-vars.yml" \
                  --ops-file "$ss_dir/manifests/cf-deployment-ops.yml" \
                  --vars-file "$bbl_dir/deployment-vars.yml" \
                  -v "system_domain=loggregator-elect.cf-app.com" \
                  "$ss_dir/manifests/scalable-syslog.yml"

                pushd updated-vars-store
                  git config user.email "cf-loggregator@pivotal.io"
                  git config user.name "Loggregator CI"
                  git add . --all
                  git commit -m "Updated scalable syslog deployment vars

                  [ci-skip]"
                popd

                rsync -ac updated-vars-store/ updated-deployments-loggregator
      - put: deployments-loggregator-with-changes
        params:
          repository: updated-deployments-loggregator
          rebase: true
      on_failure: &slack-failure-alert
        put: slack-alert
        params:
          text: |
            The `science` pipeline has failed. Please resolve any issues and ensure the pipeline lock was released. Check it out at:
            $ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME

- name: loggregator-latest-deploy
  serial: true
  serial_groups: ["loggregator-latest"]
  plan:
    - aggregate:
      - get: pipeline-lock
        passed: ["start-pipeline"]
        trigger: true
      - get: bbl-state
        resource: deployments-loggregator
      - get: cf-deployment
      - get: cf-deployment-concourse-tasks
      - get: vars-store
        resource: deployments-loggregator
      - get: release
        resource: loggregator-latest
      - get: vars-files
        resource: deployments-loggregator
      - get: consul-release
      - get: scalable-syslog-release-elect
      - get: scalable-syslog-github-release
    - do:
      - task: upload-stemcell
        file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
        params:
          BBL_STATE_DIR: gcp/loggregator-latest-bbl
      - task: copy-ops-files
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: ubuntu }
          inputs:
          - name: bbl-state
          - name: cf-deployment
          - name: release
          outputs:
          - name: ops-files
          run:
            path: /bin/bash
            args:
            - "-c"
            - |
              #!/bin/bash
              set -ex

              cp cf-deployment/operations/workarounds/use-4-azs-for-router.yml ops-files/
              cp bbl-state/gcp/loggregator-latest-bbl/ops-files/*.yml ops-files/

              version=$(cat release/version)
              sha=$(cat release/sha1)

              cat <<EOT >> ops-files/loggregator-version.yml
              - type: replace
                path: /releases/name=loggregator
                value:
                  name: loggregator
                  url: https://bosh.io/d/github.com/cloudfoundry/loggregator?v=$version
                  version: "$version"
                  sha1: "$sha"
              EOT
      - task: cf-deploy
        file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
        params:
          BBL_STATE_DIR: gcp/loggregator-latest-bbl
          SYSTEM_DOMAIN: loggregator-latest.cf-app.com
          VARS_STORE_FILE: gcp/loggregator-latest-bbl/deployment-vars.yml
          OPS_FILES: "clients.yml use-4-azs-for-router.yml loggregator-version.yml"
      - task: deploy-scalable-syslog
        config:
          image_resource:
            type: docker-image
            source:
              repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          platform: linux
          inputs:
          - name: scalable-syslog-github-release
          - name: scalable-syslog-release-elect
          - name: consul-release
          - name: updated-vars-store
          outputs:
          - name: updated-deployments-loggregator
          params:
          run:
            path: bash
            args:
              - -c
              - |
                #!/bin/bash
                set -eux

                pushd updated-vars-store/gcp/loggregator-latest-bbl
                  export BOSH_CLIENT=`bbl director-username`
                  export BOSH_CLIENT_SECRET=`bbl director-password`
                  export BOSH_CA_CERT=`bbl director-ca-cert`
                  export BOSH_ENVIRONMENT=`bbl director-address`
                popd

                for release in $(find consul-release -name '*.tgz'); do
                  bosh upload-release $release
                done

                pushd scalable-syslog-github-release
                  bosh upload-release *.tgz
                popd

                pushd scalable-syslog-release-elect
                  git checkout $(cat ../scalable-syslog-github-release/tag)
                popd

                ss_dir="$PWD/scalable-syslog-release-elect"
                bbl_dir="updated-vars-store/gcp/loggregator-latest-bbl"

                bosh -n -d scalablesyslog deploy \
                  --vars-store "$bbl_dir/scalablesyslog-vars.yml" \
                  --ops-file "$ss_dir/manifests/cf-deployment-ops.yml" \
                  --vars-file "$bbl_dir/deployment-vars.yml" \
                  -v "system_domain=loggregator-latest.cf-app.com" \
                  "$ss_dir/manifests/scalable-syslog.yml"

                pushd updated-vars-store
                  git config user.email "cf-loggregator@pivotal.io"
                  git config user.name "Loggregator CI"
                  git add . --all
                  git commit -m "Updated scalable syslog deployment vars

                  [ci-skip]"
                popd

                rsync -ac updated-vars-store/ updated-deployments-loggregator
      - put: deployments-loggregator-with-changes
        params:
          repository: updated-deployments-loggregator
          rebase: true
      on_failure: *slack-failure-alert

- name: cf-setup
  serial: true
  serial_groups: ["loggregator-elect", "loggregator-latest"]
  plan:
    - aggregate:
      - get: pipeline-lock
        passed: ["loggregator-latest-deploy", "loggregator-elect-deploy"]
        trigger: true
      - get: vars-store
        resource: deployments-loggregator-with-changes
      - get: loggregator
        resource: loggregator-develop
      - get: release-elect
        passed:
          - loggregator-elect-deploy
        resource: loggregator-release-elect
      - get: release-latest
        passed:
          - loggregator-latest-deploy
        resource: loggregator-latest
      - get: loggregator-ci
    - do:
      - aggregate:
        - task: setup-loggregator-elect
          file: loggregator-ci/tasks/science/setup-cf.yml
          params:
            SYSTEM_DOMAIN: loggregator-elect.cf-app.com
            VARS_STORE_FILE: gcp/loggregator-elect-bbl/deployment-vars.yml
            ORG: cf-lamb
            SPACE: development
        - task: setup-loggregator-latest
          file: loggregator-ci/tasks/science/setup-cf.yml
          params:
            SYSTEM_DOMAIN: loggregator-latest.cf-app.com
            VARS_STORE_FILE: gcp/loggregator-latest-bbl/deployment-vars.yml
            ORG: cf-lamb
            SPACE: development
      timeout: 5m
      on_failure: *slack-failure-alert

- name: setup-datadog
  serial: true
  serial_groups: ["loggregator-elect", "loggregator-latest"]
  plan:
    - aggregate:
      - get: pipeline-lock
        passed: ["cf-setup"]
        trigger: true
      - get: release-latest
        resource: loggregator-latest
        passed:
        - cf-setup
      - get: release-elect
        resource: loggregator-release-elect
        passed:
        - cf-setup
      - get: loggregator-ci
    - do:
      - task: setup-event
        file: loggregator-ci/tasks/science/setup-datadog-event.yml
        params:
          DATADOG_API_KEY: {{datadog-dev-api-key}}
          DATADOG_APP_KEY: {{datadog-dev-app-key}}
          LATEST_SYSTEM_DOMAIN: loggregator-latest.cf-app.com
          ELECT_SYSTEM_DOMAIN: loggregator-elect.cf-app.com
      - put: pipeline-lock
        params:
          release: pipeline-lock
      timeout: 5m
      on_failure: *slack-failure-alert

- name: smoke-tests
  serial: true
  serial_groups: ["locking"]
  plan:
    - get: pipeline-lock
    - put: pipeline-lock
      params:
        claim: "pipeline"
    - aggregate:
      - get: vars-store
        resource: deployments-loggregator-with-changes
      - get: release-elect
        resource: loggregator-release-elect
        passed:
        - setup-datadog
      - get: release-latest
        resource: loggregator-latest
        passed:
        - setup-datadog
      - get: loggregator-ci
    - get: 5m
      trigger: true
    - do:
      - aggregate:
        - do:
          - task: get-release-version
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: loggregator/base
              inputs:
                - name: release-elect
              outputs:
                - name: release-info
              run:
                path: bash
                args:
                - -c
                - |
                  #/bin/bash
                  set -ex

                  cd release-elect
                  git rev-parse HEAD > ../release-info/version
          - task: loggregator-elect
            file: loggregator-ci/tasks/science/cf-logs-smoke-test.yml
            params:
              PREFIX: "regression."
              CYCLES: 10000
              DELAY: "2"
              DELAY_UNIT: "us"
              MESSAGE: "FIFTEEN-MINUTE"
              APP_NAME: "floodspinner"
              WAIT: 60
              API_ENDPOINT: api.loggregator-elect.cf-app.com
              USERNAME: admin
              DATADOG_API_KEY: {{datadog-dev-api-key}}
              SKIP_SSL_VALIDATION: true
              VARS_STORE_FILE: gcp/loggregator-elect-bbl/deployment-vars.yml
              VERSION_TAG: elect
        - do:
          - task: get-release-version
            config:
              platform: linux
              image_resource:
                type: docker-image
                source:
                  repository: loggregator/base
              inputs:
                - name: release-latest
              outputs:
                - name: release-info
              run:
                path: bash
                args:
                - -c
                - |
                  #/bin/bash
                  set -ex

                  cp release-latest/version release-info/version
          - task: loggregator-latest
            file: loggregator-ci/tasks/science/cf-logs-smoke-test.yml
            params:
              PREFIX: "regression."
              CYCLES: 10000
              DELAY: "2"
              DELAY_UNIT: "us"
              MESSAGE: "FIFTEEN-MINUTE"
              APP_NAME: "floodspinner"
              WAIT: 60
              API_ENDPOINT: api.loggregator-latest.cf-app.com
              USERNAME: admin
              DATADOG_API_KEY: {{datadog-dev-api-key}}
              SKIP_SSL_VALIDATION: true
              VARS_STORE_FILE: gcp/loggregator-latest-bbl/deployment-vars.yml
              VERSION_TAG: latest
      timeout: 5m
      ensure:
        put: pipeline-lock
        params:
          release: pipeline-lock
