resources:
- name: 15m
  type: time
  source: {interval: 15m}
- name: 1h
  type: time
  source: {interval: 1h}
- name: loggregator-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci

jobs:
- name: log-spinner-smoke-test
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: 15m
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/smoke-test.yml
    params:
      CYCLES: 10000
      DELAY: "2"
      DELAY_UNIT: "us"
      MESSAGE: "FIFTEEN-MINUTE"
      NAME: "fifteen minute smoke test (flood)"
      APP_NAME: "floodspinner"
      WAIT: 300
      USERNAME: {{pws-username}}
      PASSWORD: {{pws-password}}
      DATADOG_API_KEY: {{datadog-prod-api-key}}
- name: log-spinner-hourly-smoke-test
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: 1h
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/smoke-test.yml
    params:
      CYCLES: 1000
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
      NAME: "one hour smoke test (slow drip)"
      APP_NAME: "dripspinner"
      WAIT: 600
      USERNAME: {{pws-username}}
      PASSWORD: {{pws-password}}
      DATADOG_API_KEY: {{datadog-prod-api-key}}
