resources:
- name: 15m
  type: time
  source: {interval: 15m}
- name: 1h
  type: time
  source: {interval: 1h}
- name: loggregator-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci
- name: loggregator
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator

jobs:
- name: pws-cf-logs-floodspinner-smoke-test
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: 15m
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/cf-logs-smoke-test.yml
    params:
      CYCLES: 10000
      DELAY: "2"
      DELAY_UNIT: "us"
      MESSAGE: "FIFTEEN-MINUTE"
      APP_NAME: "floodspinner"
      WAIT: 300
      USERNAME: {{pws-username}}
      PASSWORD: {{pws-password}}
      DATADOG_API_KEY: {{datadog-prod-api-key}}
- name: pws-cf-logs-dripspinner-smoke-test
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: 1h
    trigger: true
  - task: run-smoke-tests
    file: loggregator-ci/tasks/cf-logs-smoke-test.yml
    params:
      CYCLES: 1000
      DELAY: "500"
      DELAY_UNIT: "ms"
      MESSAGE: "HOURLY"
      APP_NAME: "dripspinner"
      WAIT: 600
      USERNAME: {{pws-username}}
      PASSWORD: {{pws-password}}
      DATADOG_API_KEY: {{datadog-prod-api-key}}

- name: coconut-scalable-syslog-https-drain-smoke-test
  public: false
  serial: true
  plan:
  - get: loggregator-ci
  - get: loggregator
  - get: 1h
    trigger: true
  - task: v1-drain-smoke-tests
    file: loggregator-ci/tasks/scalable-syslog-smoke-test.yml
    params:
      CF_SYSTEM_DOMAIN: coconut.cf-app.com
      CF_USERNAME: {{coconut-username}}
      CF_PASSWORD: {{coconut-password}}
      CF_SPACE: space
      CF_ORG: org
      DATADOG_API_KEY: {{datadog-dev-api-key}}
      DRAIN_VERSION: 1.0
  - task: v2-drain-smoke-tests
    file: loggregator-ci/tasks/scalable-syslog-smoke-test.yml
    params:
      CF_SYSTEM_DOMAIN: coconut.cf-app.com
      CF_USERNAME: {{coconut-username}}
      CF_PASSWORD: {{coconut-password}}
      CF_SPACE: space
      CF_ORG: org
      DATADOG_API_KEY: {{datadog-dev-api-key}}
      DRAIN_VERSION: 2.0
