resources:
- name: 15m
  type: time
  source: {interval: 15m}
jobs:
- name: log-spinner-smoke-test
  public: false
  plan:
  - get: 15m
    trigger: true
  - task: run-smoke-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
        - repository: loggregator/bosh20
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash

          # target api
          cf_api="api.run.pivotal.io"
          cf login -a $cf_api \
              -u {{pws-username}} \
              -p {{pws-password}} \
              -s development \
              -o cf-lamb

          # cf logs to a file
          rm -f output.txt
          cf logs mylogspinner > output.txt 2>&1 &
          sleep 30 #wait 30 seconds for socket connection
          # curl my logspinner
          curl 'mylogspinner.cfapps.io?cycles=10000&delay=2us'

          sleep 300 # wait for a bit

          msg_count=$(cat output.txt | grep -c 'msg')

          echo $msg_count

          currenttime=$(date +%s)
          curl  -X POST -H "Content-type: application/json" \
          -d "{ \"series\" :
                   [{\"metric\":\"smoke_test.loggregator.msg_count\",
                    \"points\":[[$currenttime, $msg_count]],
                    \"type\":\"gauge\",
                    \"host\":\"$cf_api\",
                    \"tags\":[]}
                  ]
              }" \
          'https://app.datadoghq.com/api/v1/series?api_key='{{datadog-api-key}}
