resources:
- name: statsd-injector-release
  type: git
  source:
    uri: git@github.com:cloudfoundry/statsd-injector-release
    branch: master
    private_key: {{cf-loggregator-oauth-bot-key}}
    ignore_paths:
    - .final_builds
    - releases

- name: statsd-injector
  type: git
  source:
    uri: git@github.com:cloudfoundry/statsd-injector
    private_key: {{cf-loggregator-oauth-bot-key}}

- name: version
  type: semver
  source:
    initial_version: 1.0.0
    bucket: statsd-injector-release-blobs
    key: version
    access_key_id: {{s3-access-key-id}}
    secret_access_key: {{s3-secret-access-key}}

- name: cf-release-develop
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-release
    branch: develop

jobs:
- name: unit-tests
  serial: true
  plan:
  - aggregate:
    - get: statsd-injector-release
    - get: statsd-injector
      trigger: true
  - task: run-units
    config:
      image_resource:
        type: docker-image
        source:
        - repository: loggregator/go18
      platform: linux
      inputs:
      - name: statsd-injector-release
      - name: statsd-injector
      run:
        path: bash
        args:
        - -c
        - {{statsd_units}}

- name: bump-release-submodule
  serial: true
  plan:
  - aggregate:
    - get: statsd-injector-release
      trigger: false
    - get: statsd-injector
      passed:
      - unit-tests
      trigger: true
  - task: update-submodule
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: loggregator/go18
      inputs:
      - name: statsd-injector-release
      - name: statsd-injector
      outputs:
      - name: bumped-statsd-injector-release
      params:
        PARENT: statsd-injector-release
        OUTPUT: bumped-statsd-injector-release
        CHILD: statsd-injector
        CHILD_PATH: src/github.com/cloudfoundry/statsd-injector
      run:
        path: bash
        args:
        - -c
        - {{update_submodule}}
  - task: sync-package-spec
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: loggregator/go18
      inputs:
        - name: bumped-statsd-injector-release
      outputs:
        - name: synced-statsd-injector-release
      params:
        RELEASE: bumped-statsd-injector-release
        OUTPUT: synced-statsd-injector-release
      run:
        path: bash
        args:
        - -c
        - {{update_package_specs}}
  - task: commit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: loggregator/go18
      inputs:
        - name: synced-statsd-injector-release
      outputs:
      - name: committed-statsd-injector-release
      params:
        SOURCE: synced-statsd-injector-release
        PATHS: src/github.com/cloudfoundry/statsd-injector
        COMMIT_MESSAGE: "Bump statsd-injector"
        OUTPUT: committed-statsd-injector-release
      run:
        path: bash
        args:
        - -c
        - {{commit}}
  - put: statsd-injector-release
    params:
      repository: committed-statsd-injector-release
      rebase: false

- name: create-final-release
  serial: true
  plan:
  - aggregate:
    - get: version
      params:
        bump: patch
    - get: statsd-injector-release
  - task: create-final-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: loggregator/bosh20
      inputs:
      - name: version
      - name: statsd-injector-release
      outputs:
      - name: final-statsd-injector-release
      params:
        RELEASE: statsd-injector-release
        S3_BUCKET: statsd-injector-release-blobs
        S3_ACCESS_KEY: {{s3-access-key-id}}
        S3_SECRET_KEY: {{s3-secret-access-key}}
        OUTPUT: final-statsd-injector-release
      run:
        path: bash
        args:
        - -c
        - {{create_final_release}}
  - put: version
    params:
      file: version/version
  - put: statsd-injector-release
    params:
      repository: final-statsd-injector-release
      rebase: false
      tag: version/version
      tag_prefix: v

- name: diff-cert-generation-scripts
  plan:
  - get: statsd-injector-release
    trigger: true
  - get: cf-release
    resource: cf-release-develop
    trigger: true
  - task: diff
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: loggregator/ubuntu-base
      inputs:
      - name: statsd-injector-release
      - name: cf-release
      run:
        path: bash
        args:
          - -c
          - |
            #!/bin/bash
            set -e
            echo diffing statsd-injector cert generation
            diff --unified statsd-injector-release/scripts/generate-certs \
                           cf-release/scripts/generate-statsd-injector-certs
