groups: []
resources:
- name: loggregator-tools
  type: git
  source:
    branch: syslog_test_deployer
    uri: https://github.com/cloudfoundry-incubator/loggregator-tools
- name: datadog-firehose-nozzle-release
  type: git
  source:
    uri: https://github.com/DataDog/datadog-firehose-nozzle-release.git
- name: deployments-loggregator
  type: git
  source:
    private_key: ((deployments-loggregator-key))
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
- name: cf-drain-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-drain-cli
- name: cf-deployment
  type: git
  source:
    branch: release-candidate
    uri: https://github.com/cloudfoundry/cf-deployment
- name: loggregator-agent-release
  type: git
  source:
    branch: syslog_test
    uri: https://github.com/cloudfoundry/loggregator-agent-release
- name: loggregator-ci
  type: git
  source:
    branch: syslog_test_deployer
    uri: https://github.com/cloudfoundry/loggregator-ci
- name: cf-deployment-concourse-tasks
  type: git
  source:
    tag_filter: v7.*
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
resource_types: []
jobs:
- name: cf-deploy
  serial: true
  serial_groups:
  - cf-deploy
  plan:
  - aggregate:
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: deployments-loggregator
    - get: loggregator-agent-release
    - get: loggregator-ci
    - get: loggregator-tools
    - get: cf-drain-cli
  - aggregate:
    - task: upload-loggregator-agent-release
      file: loggregator-ci/tasks/upload-release/task.yml
      params:
        BBL_STATE_DIR: gcp/ci-pool/syslog-test
      input_mapping:
        bbl-state: deployments-loggregator
        bosh-release-dir: loggregator-agent-release
    - task: upload-stemcell
      file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
      params:
        BBL_STATE_DIR: gcp/ci-pool/syslog-test
      input_mapping:
        bbl-state: deployments-loggregator
  - task: copy-ops-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          tag: v3.19.0
      run:
        path: /bin/bash
        args:
        - -c
        - |
          set -e

          cp loggregator-agent-release/manifests/operations/cf-add-forwarder-agent.yml ops-files/
          cp loggregator-agent-release/manifests/operations/cf-syslog-agent-skip-cert-verify.yml ops-files/
          cp loggregator-agent-release/manifests/operations/cf-deployment-addon.yml ops-files/
          cp loggregator-agent-release/manifests/operations/cf-deployment-add-system-metrics-agent.yml ops-files/
          cp cf-deployment/operations/scale-database-cluster.yml ops-files/
          cp deployments-loggregator/gcp/ci-pool/syslog-test/ops-files/clients.yml ops-files/

          cat <<EOT >> ops-files/on-the-fly.yml
          - type: replace
            path: /releases/name=loggregator-agent
            value:
              name: loggregator-agent
              version: latest
          - type: replace
            path: /update/max_in_flight
            value: 10
          - type: replace
            path: /update/canaries
            value: 1
          - type: replace
            path: /instance_groups/name=diego-cell/instances
            value: 150
          - type: replace
            path: /instance_groups/name=database/vm_type
            value: n1-highcpu-16
          - type: replace
            path: /instance_groups/name=database/persistent_disk_type
            value: 1TB
          - type: replace
            path: /instance_groups/name=database/vm_extensions?
            value:
            - 1TB_ephemeral_disk
          - type: replace
            path: /instance_groups/name=router/instances
            value: 20
          - type: replace
            path: /instance_groups/name=api/instances
            value: 12
          - type: replace
            path: /instance_groups/name=diego-api/instances
            value: 10
          - type: replace
            path: /instance_groups/name=doppler/instances
            value: 30
          - type: replace
            path: /instance_groups/name=doppler/vm_type
            value: n1-standard-8
          - type: replace
            path: /instance_groups/name=log-api/instances
            value: 12
          - type: replace
            path: /instance_groups/name=log-api/vm_type
            value: n1-standard-8
          - type: replace
            path: /instance_groups/name=singleton-blobstore/persistent_disk_type
            value: 500GB
          - type: replace
            path: /instance_groups/name=singleton-blobstore/vm_type
            value: medium
          EOT

          cat <<EOT >> ops-files/on-the-fly-binding-limit.yml
          - type: replace
            path: /addons/name=loggr-syslog-agent/jobs/name=loggr-syslog-agent/properties/binding_per_app_limit?
            value: 100
          EOT
      inputs:
      - name: loggregator-agent-release
      - name: cf-deployment
      - name: deployments-loggregator
      outputs:
      - name: ops-files
  - task: cf-deploy
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    params:
      BBL_STATE_DIR: gcp/ci-pool/syslog-test
      OPS_FILES: |
        scale-database-cluster.yml
        on-the-fly.yml
        cf-deployment-addon.yml
        cf-add-forwarder-agent.yml
        on-the-fly-binding-limit.yml
        cf-syslog-agent-skip-cert-verify.yml
        cf-deployment-add-system-metrics-agent.yml
        clients.yml
      SYSTEM_DOMAIN: syslog-test.loggr.cf-app.com
    input_mapping:
      bbl-state: deployments-loggregator
      vars-files: deployments-loggregator
- name: push-apps
  serial: true
  serial_groups:
  - cf-deploy
  - create-spaces
  plan:
  - aggregate:
    - get: deployments-loggregator
      passed:
      - create-spaces
    - get: loggregator-ci
    - get: loggregator-tools
    - get: cf-drain-cli
  - task: push-apps-and-create-drain-bindings
    file: loggregator-ci/tasks/push-many-logging-telemetry/task.yml
    params:
      APP_PREFIX: syslog-scale-test
      APPS_PER_SPACE: 40
      BBL_STATE_DIR: gcp/ci-pool/syslog-test
      DRAIN_COUNT: 20
      DRAIN_IPS: "10.0.2.9, 10.0.2.10, 10.0.2.11, 10.0.2.12, 10.0.2.13, 10.0.2.14, 10.0.2.15, 10.0.2.16, 10.0.2.17, 10.0.2.18, 10.0.2.19, 10.0.2.20, 10.0.2.21, 10.0.2.22, 10.0.2.23, 10.0.2.24, 10.0.2.25, 10.0.2.26, 10.0.2.27, 10.0.2.28, 10.0.2.29, 10.0.2.30, 10.0.2.31, 10.0.2.32, 10.0.2.33, 10.0.2.34, 10.0.2.35, 10.0.2.36, 10.0.2.37, 10.0.2.38, 10.0.2.39, 10.0.2.40, 10.0.2.41, 10.0.2.42, 10.0.2.43, 10.0.2.44, 10.0.2.45, 10.0.2.46, 10.0.2.47, 10.0.2.48, 10.0.2.49, 10.0.2.50, 10.0.2.51, 10.0.2.52, 10.0.2.53, 10.0.2.54, 10.0.2.55, 10.0.2.56, 10.0.2.57, 10.0.2.58, 10.0.2.59, 10.0.2.60, 10.0.2.61, 10.0.2.62, 10.0.2.63, 10.0.2.64, 10.0.2.65, 10.0.2.66, 10.0.2.67, 10.0.2.68, 10.0.2.69, 10.0.2.70, 10.0.2.71, 10.0.2.72, 10.0.2.73, 10.0.2.74, 10.0.2.75, 10.0.2.76, 10.0.2.77, 10.0.2.78, 10.0.2.79, 10.0.2.80, 10.0.2.81, 10.0.2.82, 10.0.2.83, 10.0.2.84, 10.0.2.85, 10.0.2.86, 10.0.2.87, 10.0.2.8, 10.0.2.88, 10.0.2.89, 10.0.2.90, 10.0.2.91, 10.0.2.92, 10.0.2.93, 10.0.2.94, 10.0.2.95, 10.0.2.96, 10.0.2.97, 10.0.2.98, 10.0.2.99, 10.0.2.100, 10.0.2.101, 10.0.2.102, 10.0.2.103, 10.0.2.104, 10.0.2.105, 10.0.2.106, 10.0.2.107, 10.0.2.108, 10.0.2.109, 10.0.2.110, 10.0.2.111, 10.0.2.112, 10.0.2.113, 10.0.2.114, 10.0.2.115, 10.0.2.116, 10.0.2.117, 10.0.2.118, 10.0.2.119, 10.0.2.120, 10.0.2.121, 10.0.2.122, 10.0.2.123, 10.0.2.124, 10.0.2.125, 10.0.2.126, 10.0.2.127, 10.0.2.128, 10.0.2.129, 10.0.2.130, 10.0.2.131, 10.0.2.132"
      EMIT_INTERVAL: 2ms
      ENDING_SPACE_ID: 51
      ORG: syslog-test
      SCHEME_SUFFIX: -v3
      SKIP_SSL_VALIDATION: true
      SPACE_PREFIX: syslog-test
      STARTING_SPACE_ID: 1
      SYSTEM_DOMAIN: syslog-test.loggr.cf-app.com
    input_mapping:
      bbl-state: deployments-loggregator
- name: create-spaces
  serial: true
  serial_groups:
  - cf-deploy
  - push-apps
  plan:
  - aggregate:
    - get: deployments-loggregator
      passed:
      - cf-deploy
    - get: loggregator-ci
  - task: create-org-and-spaces
    file: loggregator-ci/tasks/create-many-spaces/task.yml
    params:
      BBL_STATE_DIR: gcp/ci-pool/syslog-test
      ORG: syslog-test
      SPACE_COUNT: 100
      SPACE_PREFIX: syslog-test
      SYSTEM_DOMAIN: syslog-test.loggr.cf-app.com
    input_mapping:
      bbl-state: deployments-loggregator
- name: deploy-datadog-nozzle
  serial: true
  plan:
  - aggregate:
    - get: datadog-firehose-nozzle-release
    - get: deployments-loggregator
    - get: loggregator-ci
  - task: upload-release
    file: loggregator-ci/tasks/upload-release/task.yml
    params:
      BBL_STATE_DIR: gcp/ci-pool/syslog-test
      CREATE_RELEASE: false
    input_mapping:
      bbl-state: deployments-loggregator
      bosh-release-dir: datadog-firehose-nozzle-release
  - task: deploy
    file: loggregator-ci/tasks/bosh-deploy/task.yml
    params:
      BBL_STATE_DIR: gcp/ci-pool/syslog-test
      DEPLOYMENT_NAME: datadog
      MANIFEST_FILE: templates/datadog-bosh2.yml
      OPS_FILES: gcp/ci-pool/syslog-test/ops-files/datadog.yml
      VARS_FILES: gcp/ci-pool/syslog-test/vars-files/datadog.yml
      VARS_STORE_FILE: null
    input_mapping:
      bbl-state: deployments-loggregator
      bosh-release: datadog-firehose-nozzle-release
      ops-files: deployments-loggregator
      vars-files: deployments-loggregator
      vars-store: deployments-loggregator
