resources:
- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: release-candidate

- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    tag_filter: v7.*

- name: datadog-firehose-nozzle-release
  type: git
  source:
    uri: https://github.com/DataDog/datadog-firehose-nozzle-release.git

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    private_key: ((deployments-loggregator-key))

- name: loggregator-agent-release
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-agent-release
    branch: develop

- name: loggregator-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/loggregator-ci

- name: logging-deployment
  type: git
  source:
    uri: https://github.com/loggregator/logging-deployment

- name: cf-drain-cli
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-drain-cli

jobs:
- name: cf-deploy
  serial: true
  serial_groups: ["cf-deploy"]
  plan:
  - aggregate:
    - get: cf-deployment
    - get: cf-deployment-concourse-tasks
    - get: deployments-loggregator
    - get: loggregator-agent-release
    - get: loggregator-ci
    - get: logging-deployment
    - get: cf-drain-cli
  - aggregate:
    - task: upload-loggregator-agent-release
      file: loggregator-ci/tasks/upload-release/task.yml
      input_mapping:
        bosh-release-dir: loggregator-agent-release
        bbl-state: deployments-loggregator
      params:
        BBL_STATE_DIR: gcp/ci-pool/syslog-test
    - task: upload-stemcell
      file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
      input_mapping:
        bbl-state: deployments-loggregator
      params:
        BBL_STATE_DIR: gcp/ci-pool/syslog-test
  - task: copy-ops-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
          tag: v3.19.0
      inputs:
      - name: loggregator-agent-release
      - name: cf-deployment
      - name: deployments-loggregator
      outputs:
      - name: ops-files
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          set -e

          cp loggregator-agent-release/manifests/operations/cf-add-forwarder-agent.yml ops-files/
          cp loggregator-agent-release/manifests/operations/cf-syslog-agent-skip-cert-verify.yml ops-files/
          cp loggregator-agent-release/manifests/operations/cf-deployment-addon.yml ops-files/
          cp loggregator-agent-release/manifests/operations/cf-deployment-add-system-metrics-agent.yml ops-files/
          cp cf-deployment/operations/scale-database-cluster.yml ops-files/
          cp deployments-loggregator/gcp/ci-pool/syslog-test/ops-files/clients.yml ops-files/

          cat <<EOT >> ops-files/on-the-fly.yml
          - type: replace
            path: /releases/name=loggregator-agent
            value:
              name: loggregator-agent
              version: latest
          - type: replace
            path: /update/max_in_flight
            value: 10
          - type: replace
            path: /update/canaries
            value: 1
          - type: replace
            path: /instance_groups/name=diego-cell/instances
            value: 150
          - type: replace
            path: /instance_groups/name=database/vm_type
            value: n1-highcpu-16
          - type: replace
            path: /instance_groups/name=database/persistent_disk_type
            value: 1TB
          - type: replace
            path: /instance_groups/name=database/vm_extensions?
            value:
            - 1TB_ephemeral_disk
          - type: replace
            path: /instance_groups/name=router/instances
            value: 20
          - type: replace
            path: /instance_groups/name=api/instances
            value: 12
          - type: replace
            path: /instance_groups/name=diego-api/instances
            value: 10
          - type: replace
            path: /instance_groups/name=doppler/instances
            value: 30
          - type: replace
            path: /instance_groups/name=doppler/vm_type
            value: n1-standard-8
          - type: replace
            path: /instance_groups/name=log-api/instances
            value: 12
          - type: replace
            path: /instance_groups/name=log-api/vm_type
            value: n1-standard-8
          - type: replace
            path: /instance_groups/name=singleton-blobstore/persistent_disk_type
            value: 500GB
          - type: replace
            path: /instance_groups/name=singleton-blobstore/vm_type
            value: medium
          EOT
  - task: cf-deploy
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      bbl-state: deployments-loggregator
      vars-files: deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/ci-pool/syslog-test
      SYSTEM_DOMAIN: syslog-test.loggr.cf-app.com
      OPS_FILES: |
          scale-database-cluster.yml
          on-the-fly.yml
          cf-deployment-addon.yml
          cf-add-forwarder-agent.yml
          cf-syslog-agent-skip-cert-verify.yml
          cf-deployment-add-system-metrics-agent.yml
          clients.yml

- name: deploy-datadog-nozzle
  serial: true
  plan:
  - aggregate:
    - get: datadog-firehose-nozzle-release
    - get: deployments-loggregator
    - get: loggregator-ci
  - task: upload-release
    file: loggregator-ci/tasks/upload-release/task.yml
    params:
      BBL_STATE_DIR: gcp/ci-pool/syslog-test
      CREATE_RELEASE: false
    input_mapping:
      bbl-state: deployments-loggregator
      bosh-release-dir: datadog-firehose-nozzle-release
  - task: deploy
    file: loggregator-ci/tasks/bosh-deploy/task.yml
    params:
      BBL_STATE_DIR: gcp/ci-pool/syslog-test
      DEPLOYMENT_NAME: datadog
      MANIFEST_FILE: templates/datadog-bosh2.yml
      OPS_FILES: gcp/ci-pool/syslog-test/ops-files/datadog.yml
      VARS_FILES: gcp/ci-pool/syslog-test/vars-files/datadog.yml
      VARS_STORE_FILE: null
    input_mapping:
      bbl-state: deployments-loggregator
      bosh-release: datadog-firehose-nozzle-release
      ops-files: deployments-loggregator
      vars-files: deployments-loggregator
      vars-store: deployments-loggregator

- name: push-apps
  serial: true
  serial_groups: ["cf-deploy", "create-spaces"]
  plan:
  - aggregate:
    - get: deployments-loggregator
      passed: ["create-spaces"]
    - get: loggregator-ci
    - get: logging-deployment
    - get: cf-drain-cli
  - task: push-apps-and-create-drain-bindings
    file: loggregator-ci/tasks/push-many-logging-telemetry/task.yml
    input_mapping:
      bbl-state: deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/ci-pool/syslog-test
      SYSTEM_DOMAIN: syslog-test.loggr.cf-app.com
      ORG: syslog-test
      SPACE_PREFIX: syslog-test
      APP_PREFIX: syslog-scale-test
      DATADOG_API_KEY: ((datadog-loggregator-api-key))
      SKIP_SSL_VALIDATION: true
      SCHEME_SUFFIX: "-v3"
      STARTING_SPACE_ID: 1
      ENDING_SPACE_ID: 25
      APPS_PER_SPACE: 40
      BINDING_COUNT: 5
  # TODO: Schedule teardown and create of environment on weekends

- name: create-spaces
  serial: true
  serial_groups:
  - cf-deploy
  - push-apps
  plan:
  - aggregate:
    - get: deployments-loggregator
      passed: ["cf-deploy"]
    - get: loggregator-ci
  - task: create-org-and-spaces
    file: loggregator-ci/tasks/create-many-spaces/task.yml
    params:
      BBL_STATE_DIR: gcp/ci-pool/syslog-test
      ORG: syslog-test
      SPACE_COUNT: 100
      SPACE_PREFIX: syslog-test
      SYSTEM_DOMAIN: syslog-test.loggr.cf-app.com
    input_mapping:
      bbl-state: deployments-loggregator

