groups:
- name: main
  jobs:
  - uptimer
- name: director-lifecycle
  jobs:
  - bbl-create

resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks
    branch: v5.0

- name: bosh-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment

- name: cf-deployment
  type: git
  source:
    uri: https://github.com/cloudfoundry/cf-deployment
    branch: develop

- name: deployments-loggregator
  type: git
  source:
    uri: git@github.com:cloudfoundry/deployments-loggregator.git
    branch: master
    private_key: {{deployments-loggregator-key}}

- name: uptimer
  type: git
  source:
    uri: https://github.com/cloudfoundry/uptimer

jobs:
- name: bbl-create
  public: false
  plan:
  - get: cf-deployment-concourse-tasks
    trigger: false
  - get: deployments-loggregator
  - get: bosh-deployment
  - task: bbl-up
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    input_mapping:
      env-repo: deployments-loggregator
      ops-files: bosh-deployment
    params:
      BBL_GCP_SERVICE_ACCOUNT_KEY: gcp/service-account.key.json
      BBL_GCP_PROJECT_ID: cff-loggregator
      BBL_GCP_ZONE: us-central1-a
      BBL_GCP_REGION: us-central1
      BBL_STATE_DIR: gcp/upity
      BBL_IAAS: gcp
      BBL_LB_CERT: {{coconut_bbl_lb_cert}}
      BBL_LB_KEY: {{coconut_bbl_lb_key}}
      BBL_ENV_NAME: upity
      LB_DOMAIN: upity.loggr.cf-app.com
      OPS_FILES: "local-dns.yml"
  - put: deployments-loggregator
    params:
      repository: updated-env-repo
      rebase: true

# - name: bbl-destroy
#   public: false
#   plan:
#   - get: cf-deployment-concourse-tasks
#     trigger: false
#   - get: bbl-state
#     resource: deployments-loggregator
#     trigger: false
#   - task: bbl-destroy
#     file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
#     params:
#       BBL_STATE_DIR: gcp/upity
#   - put: deployments-loggregator
#     params:
#       repository: updated-bbl-state
#       rebase: true

- name: uptimer
  public: false
  plan:
  - aggregate:
    - get: cf-deployment
    - get: deployments-loggregator
    - get: cf-deployment-concourse-tasks
    - get: uptimer
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    input_mapping:
      env-repo: deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/upity
  - task: copy-ops-files
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
      inputs:
      - name: deployments-loggregator
      - name: cf-deployment
      outputs:
      - name: ops-files
      run:
        path: /bin/bash
        args:
        - "-c"
        - |
          #!/bin/bash
          set -x

          cp cf-deployment/operations/scale-database-cluster.yml ops-files/
          cp deployments-loggregator/gcp/upity/ops-files/*.yml ops-files/
          cat <<EOT >> ops-files/starting-doppler-count.yml
          - type: replace
            path: /instance-groups/name=doppler/instances
            value: 2
          EOT
          cat <<EOT >> ops-files/scaling-doppler-count.yml
          - type: replace
            path: /instance-groups/name=doppler/instances
            value: 4
          EOT
  - task: cf-deploy
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      vars-store: deployments-loggregator
      vars-files: deployments-loggregator
      env-repo: deployments-loggregator
    output_mapping:
      updated-vars-store: updated-deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/upity
      SYSTEM_DOMAIN: upity.loggr.cf-app.com
      VARS_STORE_FILE: gcp/upity/deployment-vars.yml
      OPS_FILES: "allow-insecure-syslog-drains.yml scale-database-cluster.yml starting-doppler-count.yml"
  - put: deployments-loggregator
    params:
      repository: updated-deployments-loggregator
      rebase: true
  - task: cf-deploy
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      vars-store: deployments-loggregator
      vars-files: deployments-loggregator
      bbl-state: deployments-loggregator
      env-repo: deployments-loggregator
    output_mapping:
      updated-vars-store: updated-deployments-loggregator
    params:
      BBL_STATE_DIR: gcp/upity
      SYSTEM_DOMAIN: upity.loggr.cf-app.com
      VARS_STORE_FILE: gcp/upity/deployment-vars.yml
      OPS_FILES: "allow-insecure-syslog-drains.yml scale-database-cluster.yml scaling-doppler-count.yml"
      DEPLOY_WITH_UPTIME_MEASUREMENTS: true
      MEASURE_SYSLOG_AVAILABILITY: true
      TCP_DOMAIN: tcp.upity.loggr.cf-app.com
      AVAILABLE_PORT: 1025
      FAIL_ON_DOWNTIME: true
