#!/bin/bash

function join_by {
  local IFS="$1"
  shift
  echo "$*"
}

set -exo pipefail

# setup ssh for reading from github
eval "$(ssh-agent -s)"
mkdir -p ~/.ssh
echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
ssh-add <(echo "$SSH_KEY")

pushd release-repo
  git checkout $BACKPORT_BRANCH
  old_tag=$(git describe --abbrev=0 --tags --match 'v*' || true)
  if [[ $old_tag == "" ]]; then
    exit 1
  fi

  old_version=${old_tag//v}
  split_version=( ${old_version//./ })
  patch=${split_version[2]}

  # bump patch
  split_version[2]=`expr ${patch} + 1`

  NEW_VERSION=$(join_by . "${split_version[@]}")
  commit_range="${old_tag}..HEAD"

  set +x
  BUMPER_RESULT=$( (bumper --commit-range ${commit_range} --verbose --no-color) 2>&1 | grep -v "Bump modules")
  BUMPER_RESULT=${BUMPER_RESULT//  / &nbsp; &nbsp;}
  BUMPER_RESULT=${BUMPER_RESULT//... / &nbsp; &nbsp;}
  GIT_DIFF_JOBS=$(git diff ${commit_range} -- jobs)
  set -x
popd

tag_name="v$NEW_VERSION"

# write out github release files
echo "$RELEASE_NAME $NEW_VERSION" > github-release/name
echo $tag_name > github-release/tag
printf '## BUMPER OUTPUT\n%s\n\n' "$BUMPER_RESULT" >> github-release/body
printf '## GIT DIFF jobs directory\n```diff\n%s\n```\n\n' "${GIT_DIFF_JOBS}" >> github-release/body

# build final release on BACKPORT_BRANCH
pushd release-repo
  # setup private.yml used by `create-release --final`
  cat << EOF > config/private.yml
---
blobstore:
  provider: s3
  options:
    bucket_name: $BLOBSTORE_BUCKET
    access_key_id: $S3_ACCESS_KEY
    secret_access_key: $S3_SECRET_KEY
    credentials_source: static
EOF

  # create final release and commit artifcats
  bosh -n create-release --sha2 --final \
    --tarball ../github-release/release.tgz \
    --version "$NEW_VERSION"
  git add .
  git commit -m "Create final release"

  final_release_abbrev=$(git rev-parse --abbrev-ref HEAD)
  final_release_sha=$(git rev-parse HEAD)
  git tag "$tag_name" $final_release_sha
popd

exit 1
