#!/bin/bash
set -exu

fcomp() {
    awk -v n1="$1" -v n2="$2" 'BEGIN {if (n1+0<n2+0) exit 0; exit 1}'
}

source cf-deployment-concourse-tasks/shared-functions
setup_bosh_env_vars

set +x
echo "Authenticating as CF admin"
cf api --skip-ssl-validation "api.${SYSTEM_DOMAIN}"
cf auth admin $(get_password_from_credhub cf_admin_password)
set -x

# Doppler ingress <= 500/sec?
cf install-plugin -f -r CF-Community "log-cache"
echo "Testing platform ingress rate of dopplers"
ingress_rate=$(cf query 'sum(rate(ingress{source_id="doppler"}[5m]))' | jq .data.result[0].value[1] -r)
echo $ingress_rate

if [ $(awk 'BEGIN {print ('$ingress_rate' >= 500)}') -eq 1 ]; then
    exit 1
fi
# All cpus < 75%
echo "Testing platform cpu percentages"
bosh -d cf vms --vitals | \
    sed 's/%//g' | \
    awk '
    # user, system, and idle cpu < 75%
    $23 + $24 + $25 < 75 {
        printf"%s\t%s\n", "SUCCESS", $1;
    }
    # user, system, and idle cpu >= 75%
    $23 + $24 + $25 >= 75 {
        printf "%s\t%s\n", "FAIL", $1;
    }
' > cpu-measure

cat cpu-measure
if cat cpu-measure | grep FAIL; then
    exit 1
fi
# All memory < 75 %
echo "Testing platform mem consumption"
bosh -d cf vms --vitals | \
    sed 's/%//g' | \
    awk '
    # memory percent < 75%
    $26 < 75 {
        printf"%s\t%s\n", "SUCCESS", $1;
    }
    # memory percent >= 75%
    $26 >= 75 {
        printf "%s\t%s\n", "FAIL", $1;
    }
' > mem-measure
cat mem-measure
if cat mem-measure | grep FAIL; then
    exit 1
fi

