---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: loggregator-ci
  - name: bbl-state

run:
  path: loggregator-ci/tasks/create-many-spaces/task

params:
  # - Required
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - Defaults to the root of the `bbl-state` input
  BBL_STATE_DIR:

  # - Required
  # - The CF Orginization to create the spaces under.
  ORG:

  # - Required
  # - The prefix to prepend to all the spaces. Space names will be
  # - `SPACE_PREFIX-#`.
  SPACE_PREFIX:

  # - Required
  # - The number of spaces to create.
  SPACE_COUNT: 40

  # - Required
  # - The system domain used for targeting the foundation.
  SYSTEM_DOMAIN:
