#!/bin/bash
set -ex

pushd source-repo/src
  export PROJECT_DIR=$PWD
  export GO111MODULE=on

  go get -u ./...
  go mod tidy
  go mod vendor
  go test -mod=vendor ./... -race -ginkgo.randomizeAllSpecs
popd

cp -a source-repo/. bumped-source