#!/bin/bash
set -ex

pushd source-repo/src
  export PROJECT_DIR=$PWD
  export GO111MODULE=on

  # do not bump pinned dependencies
  go get -u -m $(awk '/require/{y=1;next}y' go.mod | grep -v ')' | grep -v pinned | awk '{print $1}')
  go mod tidy
  go mod vendor
  go test -mod=vendor ./... -race -ginkgo.randomizeAllSpecs
popd

cp -a source-repo/. bumped-source