---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci # - This repo
- name: source-repo    # - The Go package to test

run:
  path: loggregator-ci/tasks/go-mod-test/task

