#!/bin/bash
set -ex

source $(cd $(dirname ${BASH_SOURCE})/../../scripts/helpers) && pwd)/retry.sh

pushd source-repo/src
  export PROJECT_DIR=$PWD
  export GO111MODULE=on

  # do not bump pinned dependencies
  retry 3 go get -u -m $(awk '/require/{y=1;next}y' go.mod | grep -v ')' | grep -v pinned | grep -v replace | awk '{print $1}')
  retry 3 go mod tidy

  export GOPROXY=off
  go mod vendor
  go test -mod=vendor ./... -race -ginkgo.randomizeAllSpecs
popd

cp -a source-repo/. bumped-source