platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci
- name: bbl-state

outputs:
- name: ops-files
- name: vars-files

run:
  path: loggregator-ci/tasks/prepare-datadog-ops-and-vars/task

params:
  BBL_STATE_DIR:
  SYSTEM_DOMAIN:
  DATADOG_API_KEY: