platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
inputs:
- name: loggregator-tools
- name: loggregator-ci
- name: bbl-state
  optional: true
params:
  CF_SYSTEM_DOMAIN:
  CF_USERNAME:
  CF_PASSWORD:
  CF_SPACE:
  CF_ORG:
  DATADOG_API_KEY:
  DRAIN_VERSION:
  SINK_DEPLOY: "cf"
  EXTERNAL_DRAIN_HOST:
  EXTERNAL_DRAIN_PORT:
  EXTERNAL_COUNTER_PORT:
  TEARDOWN: true
  JOB_NAME:
  USE_CLIENT_AUTH: false
  BBL_STATE_DIR:
run:
  path: loggregator-ci/tasks/blackbox/firehose-reliability/task
