platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: releases
- name: published-releases

outputs:
- name: slack

run:
  path: loggregator-ci/tasks/release-reminder/task

params:
  MASTER_BRANCH: master
  SSH_KEY:
  COMMITS_BEFORE_RELEASE:
