---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: loggregator-ci
- name: cfd-env
- name: releases
  optional: true

run:
  path: loggregator-ci/tasks/check-metrics/task

params:
  USERNAME:
  ORG:
  SPACE:

  # only runs checks for data from all instances
  INSTANCE_CHECK_ONLY: false

  # source IDs that will always be checked regardless of job names
  STATIC_SOURCE_IDS:

  # jobs that will be omitted when checking for source ids
  JOB_BLACKLIST:
