---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: release
- name: loggregator-ci

outputs:
- name: test-binaries

params:
  IGNORE_PACKAGE_REGEX:

run:
  path: loggregator-ci/tasks/go-windows-tests/build-binary/task

