#!/bin/bash
set -ex

ci_root=$PWD
function munge {
  echo $1 | tr '/' '_'
}

export GOOS=windows
export PATH="$GOPATH/bin:$PATH"
export GO111MODULE=on

pushd release/src
  # do not bump pinned dependencies
  pushd cmd
    for pkg in $(go list ./... | grep -vE ${IGNORE_PACKAGE_REGEX}); do
      go test -mod=vendor -c -o $ci_root/test-binaries/$(munge $pkg)_test.exe $pkg &
    done
  popd
popd
wait
