#!/bin/bash
set -ex

source $(cd $(dirname ${BASH_SOURCE})/../../../scripts/helpers && pwd)/retry.sh
ci_root=$PWD
function munge {
  echo $1 | tr '/' '_'
}

export GOOS=windows
export PATH="$GOPATH/bin:$PATH"
export GO111MODULE=on

pushd release/src
  # do not bump pinned dependencies
  retry 3 go get -u -m $(awk '/require/{y=1;next}y' go.mod | grep -v ')' | grep -v pinned | grep -v replace | awk '{print $1}')
  retry 3 go mod tidy

  export GOPROXY=off
  go mod vendor

  pushd cmd
    for pkg in $(go list ./... | grep -vE ${IGNORE_PACKAGE_REGEX}); do
      go test -mod=vendor -c -o $ci_root/test-binaries/$(munge $pkg)_test.exe $pkg &
    done
  popd
popd
wait