#!/bin/bash

set -ex

login_args=""
if [ "$SKIP_SSL_VALIDATION" = "true" ]; then
    login_args="--skip-ssl-validation"
fi

# target api
cf login \
  -a api."$SYSTEM_DOMAIN" \
  -u "$USERNAME" \
  -p "$PASSWORD" \
  -s "$SPACE" \
  -o "$ORG" \
  $login_args

GOPATH=$PWD/go

pushd loggregator-tools/log-cache-siege
  go get -d ./...
  go build

  cf push $APP_NAME -b binary_buildpack -c ./log-cache-siege -m 1G -u none --no-start

  cf set-env $APP_NAME REQUEST_SPINNER_ADDR $REQUEST_SPINNER_ADDR
  cf set-env $APP_NAME LOG_CACHE_ADDR $LOG_CACHE_ADDR

  cf set-env "$APP_NAME" UAA_ADDR https://uaa."$SYSTEM_DOMAIN"
  cf set-env "$APP_NAME" UAA_CLIENT $UAA_CLIENT
  cf set-env "$APP_NAME" UAA_CLIENT_SECRET $UAA_CLIENT_SECRET

  if [ "$SKIP_SSL_VALIDATION" = "true" ]; then
    cf set-env "$APP_NAME" SKIP_SSL_VALIDATION $SKIP_SSL_VALIDATION
  fi

  cf start $APP_NAME
popd
