#!/bin/bash

set -ex

if [ $SKIP_SSL_VALIDATION == "true" ]; then
    cf api api.$SYSTEM_DOMAIN --skip-ssl-validation
else
    cf api api.$SYSTEM_DOMAIN
fi

cf auth $USERNAME $PASSWORD
cf target -o $ORG -s $SPACE

IMPORT_PATH=code.cloudfoundry.org/cf-drain-cli

mkdir -p "workspace/src/$IMPORT_PATH"
cp -r cf-drain-cli/. "workspace/src/$IMPORT_PATH"

pushd workspace
  export GOPATH="$PWD"
  export PATH="$GOPATH/bin:$PATH"

  go get code.cloudfoundry.org/cf-drain-cli/cmd/cf-drain-cli
  cf install-plugin $GOPATH/bin/cf-drain-cli -f
popd


IMPORT_PATH=github.com/loggregator/logging-deployment

mkdir -p "workspace/src/$IMPORT_PATH"
cp -r logging-deployment/. "workspace/src/$IMPORT_PATH"

pushd $GOPATH/src/$IMPORT_PATH/ci/assets/logging-telemetry
  go get ./...
  ./deploy.sh $APP_PREFIX $DATADOG_API_KEY
popd
