#!/bin/bash
set -exo pipefail

source loggregator-ci/tasks/create-final-release/helpers.sh
setup_github_ssh

root_dir=$PWD

pushd master-repo
  NEW_VERSION=$(cat src/version)
  old_tag=$(git describe --abbrev=0 --tags --match v* || git rev-list --max-parents=0 HEAD)

  if no_commits "${old_tag}..HEAD"; then
    echo "There are no commits... aborting"
    exit 1
  fi

  # this is needed to land commits on master since the commit for
  # master is checked out as a detatched head when the git
  # resource clones it down
  git checkout master

  create_tagged_release "$NEW_VERSION"
  build_github_release_info "$RELEASE_NAME" "$NEW_VERSION" "${old_tag}..HEAD" "$root_dir/github-release"

  if only_auto_bumpable_commits "${old_tag}..HEAD"; then
    touch "${root_dir}/publish/true"
  fi
popd

# copy repos into output
cp -r master-repo repos
