platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v3.15.0
inputs:
# - The source bosh release repo where the script resides and will be ran.
- name: release-repo
# - The repo that contains run-release-script.sh.
- name: loggregator-ci
outputs:
# - The directory where the result of running the script is copied. This will
#   include all the files from the input bosh release.
- name: updated-release-repo
params:
  # - Required
  # - The version of Go to bump to.
  VERSION:

  # - Optional
  # - Whether to bump windows golang version.
  INCLUDE_WINDOWS: false
run:
  path: ../loggregator-ci/tasks/bump-golang/task
  dir: updated-release-repo
