#!/bin/bash

set -exu

pushd bbl-state/$BBL_STATE_DIR
  export BOSH_CLIENT=$(bbl director-username)
  export BOSH_CLIENT_SECRET=$(bbl director-password)
  export BOSH_CA_CERT=$(bbl director-ca-cert)
  export BOSH_ENVIRONMENT=$(bbl director-address)
popd

function bosh_delete_deployment() {
  echo bosh \
  -n \
  delete-deployment -d $1
}

deployments=$(bosh deployments --column=name --json)
if [[ ! -z $deployments ]]; then
  names=$(echo $deployments | jq -r .Tables[].Rows[].name)
  echo $names
  for d in $names; do
    bosh_delete_deployment $d
  done
fi

