---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v4.11.0

inputs:
- name: bbl-state
- name: loggregator-ci  # - This repo

run:
  path: loggregator-ci/tasks/bosh-delete-all-deployment/task

params:
  BBL_STATE_DIR: bbl-state
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to the `env-repo` input
  # - If blank or '.', uses `env-repo` input as the location for bbl state
