platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.2.0

inputs:
- name: deployments-loggregator
- name: loggregator-ci
- name: loggregator-release
- name: loggregator-bench-results
outputs:
- name: updated-loggregator-bench-results
params:
  DATADOG_VARS_DIR: deployments-loggregator
  BBL_STATE_DIR: deployments-loggregator/gcp/coconut-bbl
run:
  path: loggregator-ci/tasks/loggregator-bench/task
