platform: linux
image_resource:
  type: docker-image
  source:
    repository: loggregator/base
inputs:
- name: release-latest
- name: release-elect
params:
  DATADOG_API_KEY:
  DATADOG_APP_KEY:
  LATEST_SYSTEM_DOMAIN:
  ELECT_SYSTEM_DOMAIN:
run:
  path: bash
  args:
  - -c
  - |
    #/bin/bash
    set -ex

    pushd release-elect
      ELECT_SHA=$(git rev-parse HEAD)
    popd

    LATEST_VERSION=$(cat release-latest/version)

    DASHBOARD_TITLE="Release Elect Regression (v$LATEST_VERSION..$ELECT_SHA)"
    echo $DASHBOARD_TITLE

    cat <<EOF >> /tmp/request-body.json
    {
      "title": "$DASHBOARD_TITLE",
      "text": "$DASHBOARD_TITLE",
      "tags": [
        "latest:$LATEST_VERSION",
        "elect:$ELECT_SHA"
      ]
    }
    EOF

    curl "https://app.datadoghq.com/api/v1/events?api_key=${DATADOG_API_KEY}&application_key=${DATADOG_APP_KEY}" -X POST -H "Content-type: application/json" -d "@/tmp/request-body.json"
