platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci
- name: bbl-state

outputs:
- name: ops-files

run:
  path: loggregator-ci/tasks/prepare-service-logs-ops/task

params:
  ENV_NAME:
  BBL_STATE_DIR: