platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
inputs:
- name: bbl-state
- name: deployment-settings
- name: loggregator-capacity-planning-release
- name: loggregator-ci
- name: updated-vars-store
outputs:
- name: updated-capacity-planning-vars-store
run:
  path: loggregator-ci/tasks/automated-rampup-test/task