---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v3.15.0

inputs:
- name: loggregator-ci # - This repo
- name: release-repo

outputs:
- name: committed-repo

run:
  path: loggregator-ci/tasks/commit-with-shortlog/task
  dir: commited-repo

params:
  # Required. The paths to commit.
  PATHS:
