#!/bin/bash
set -ex

if [ "$IMAGE_NAME" = "" ]; then
    echo IMAGE_NAME was not set
    exit 1
fi

ciroot="$PWD"
sha="$(cd loggregator-src && git rev-parse @)"

workspace_code_path=workspace/src/code.cloudfoundry.org/loggregator
mkdir -p "$workspace_code_path"
cp -r loggregator-src/. "$workspace_code_path/"
go get -d -v code.cloudfoundry.org/loggregator/...
export GOPATH="$PWD/workspace"

pushd "loggregator-ci/docker-images/$IMAGE_NAME" > /dev/null
    ./build_bin.sh

    mkdir -p "$ciroot/build-image/build"
    cp Dockerfile "$IMAGE_NAME" "$ciroot/build-image/build/"
    echo "$sha" > "$ciroot/build-image/tag"
popd > /dev/null
