#!/bin/bash
set -ex

if [ -z "$BASE_PACKAGE" ]; then
    echo BASE_PACKAGE was not set
    exit 1
fi

if [ -z "$IMAGE_NAME" ]; then
    echo IMAGE_NAME was not set
    exit 1
fi

ciroot="$PWD"
sha="$(cd source-repo && git rev-parse @)"

workspace_code_path=workspace/src/$BASE_PACKAGE
mkdir -p "$workspace_code_path"
cp -r source-repo/. "$workspace_code_path/"
export GOPATH="$PWD/workspace"
go get -d -v $BASE_PACKAGE/...

pushd "loggregator-ci/docker-images/$IMAGE_NAME" > /dev/null
    mkdir -p "$ciroot/build-image/build"
    cp -r "$GOPATH/." "$ciroot/build-image/build/"
    cp Dockerfile "$ciroot/build-image/build/"
    echo "$sha" > "$ciroot/build-image/tag"
popd > /dev/null
