#!/bin/bash
set -e

ci_root=$PWD

# setup ssh for reading from github
eval "$(ssh-agent -s)"
mkdir -p ~/.ssh
echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
ssh-add <(echo "$SSH_KEY")

published_tag=$(cat ${ci_root}/published-release/tag)

pushd release
  git fetch --tags
  bumper --commit-range ${published_tag}..HEAD --verbose
popd
