#!/bin/bash

set -ex

export workspace=$PWD

export BBL_STATE_DIR=$(cat environment/metadata)
export BBL_ENV_NAME=$(cat environment/name)
export LB_DOMAIN="$BBL_ENV_NAME.$GCP_LB_DOMAIN"
export SERVICE_ACCOUNT_KEY=$workspace/bbl-state/$BBL_GCP_SERVICE_ACCOUNT_KEY

gcloud auth activate-service-account --key-file=$SERVICE_ACCOUNT_KEY

pushd "bbl-state/$BBL_STATE_DIR"
  NS=$(bbl --gcp-service-account-key=$SERVICE_ACCOUNT_KEY lbs | grep "System Domain" | cut -d':' -f2)
popd

gcloud dns record-sets transaction start -z $GCP_DNS_ZONE
gcloud dns record-sets transaction add $(echo $NS) --zone $GCP_DNS_ZONE --name "$LB_DOMAIN" --ttl 300 --type NS
gcloud dns record-sets transaction execute -z $GCP_DNS_ZONE
