#!/bin/bash
set -ex

pushd package-repo
  commit_sha=$(git rev-parse HEAD)
popd

pushd base-repo
  export PROJECT_DIR=$PWD
  export GO111MODULE=on
  go get "${PACKAGE_URL}@${commit_sha}"
popd

cp -a base-repo/. bumped-base-repo