platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: base-repo
- name: package-repo

outputs:
- name: bumped-base-repo

params:
  PACKAGE_URL: