platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: base-repo
- name: package-repo
- name: loggregator-ci

outputs:
- name: bumped-base-repo

run:
  path: loggregator-ci/tasks/go-mod-pin-commit/task

params:
  PACKAGE_URL:
