---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci # - This repo
- name: source-repo    # - The Go package to test

outputs:
- name: tested-source # A copy of the source-repo with modules updated

run:
  path: loggregator-ci/tasks/go-test/task

