#!/bin/bash
set -ex
                                                                                                         
cp cf-deployment/operations/experimental/*.yml ops-files/
cp cf-deployment/operations/*.yml ops-files/
cp denver-deployments/bosh-cf-deployment/operations/loggregator/*.yml ops-files/
cp denver-deployments/bosh-cf-deployment/operations/default/use-provided-router-certs.yml ops-files/
cp loggregator-agent-release/manifests/operations/*.yml ops-files/
cp log-cache-release/manifests/operations/*.yml ops-files/
cp log-cache-ci/ops-files/awaiting-cf-deployment-prs.yml ops-files/