#!/bin/bash
set -ex
                                                                                                         
cp cf-deployment/operations/*.yml ops-files/
cp denver-deployments/bosh-cf-deployment/operations/default/use-provided-router-certs.yml ops-files/

cp denver-deployments/bosh-cf-deployment/operations/loggregator/*.yml ops-files/denver/
cp cf-deployment/operations/experimental/*.yml ops-files/experimental/
cp loggregator-release/manifests/operations/*.yml ops-files/loggregator
cp loggregator-agent-release/manifests/operations/*.yml ops-files/loggregator-agent
cp metrics-discovery-release/manifests/operations/*.yml ops-files/metrics-discovery
cp log-cache-release/manifests/operations/*.yml ops-files/log-cache
cp system-metrics-release/manifests/operations/*.yml ops-files/system-metrics
