# This task checks the health of a VM in a bosh deployment.
---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.2.0

inputs:
- name: loggregator-ci # - This repo
- name: bbl-state      # - The Director's `bbl-state.json`

run:
  path: loggregator-ci/tasks/blackbox/bosh-vm-health-check/task

params:
  # - Optional
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - Defaults to the root of the `bbl-state` input
  BBL_STATE_DIR:

  # - Required
  # - The name of the deployment to perform health checks on.
  DEPLOYMENT_NAME:
