---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
  - name: bbl-state
  - name: loggregator-ci

run:
  path: loggregator-ci/tasks/service-metrics-smoke-test/task

params:
  # Required - path to bbl-state.json relative to bbl-state input
  BBL_STATE_DIR:

  # Required
  CF_API:

  # Required - Username to log in to CF
  USERNAME:

  # Required - source ID that is used in service metrics deployment
  SOURCE_ID:

  # Required - Organization in CF
  ORG:

  # Required - Space in CF
  SPACE:
