#!/usr/bin/env bash
set -exo pipefail

source loggregator-ci/scripts/environment-targeting/target-cf.sh && target-cf
cf install-plugin -f -r "CF-Community" log-stream

cf log-stream ${SOURCE_ID} > log-stream.log &
log_stream_pid=$!

function cleanup() {
    kill ${log_stream_pid}
}
trap cleanup EXIT

for i in {1..12}; do
  sleep 5
  if [[ $(cat log-stream.log | grep service_dummy | wc -l) -gt 0 ]]; then
      cat log-stream.log | grep service_dummy
      exit 0
  fi
done

echo "No service_dummy metrics were received"
exit 1
