#!/bin/bash
set -eu

if [[ "$DEBUG" = true ]]; then
    set -x
fi

pushd "bbl-state/$BBL_STATE_DIR"
  eval "$(bbl print-env)"
popd

deployed_release="$(bosh -d $DEPLOYMENT_NAME deployment | grep $RELEASE_NAME/ | awk '{print $1}')"

ubuntu_stemcell="ubunut-xenial/$(bosh -d $DEPLOYMENT_NAME deployment --column="Stemcell(s)" | grep xenial | awk -F'/' '{print $2}')"
bosh -d $DEPLOYMENT_NAME export-release $deployed_release $ubuntu_stemcell

if [[ ! -z $EXPORT_TO_WINDOWS ]]; then
    windows_stemcell="windows1803/$(bosh -d $DEPLOYMENT_NAME deployment --column="Stemcell(s)" | grep windows | awk -F'/' '{print $2}')"
    bosh -d $DEPLOYMENT_NAME export-release $deployed_release $windows_stemcell
fi