#!/bin/bash
set -ex

# establish version/tag strings
version="{\"Major\":$VERSION_MAJOR,\"Minor\":$VERSION_MINOR,\"Build\":$VERSION_BUILD}"
semver="v$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH"

# write out github release files
echo "CF Drain CLI $semver" > github-release/name
echo $semver> github-release/tag
echo "TBD" > github-release/body

# setup go path
cfdrain=$PWD/cf-drain-cli
tools=$PWD/loggregator-tools
mkdir -p go
pushd go
  export GOPATH=$PWD

  go get -d code.cloudfoundry.org/cf-drain-cli/...
  rm -rf src/code.cloudfoundry.org/cf-drain-cli
  cp -r $cfdrain src/code.cloudfoundry.org/cf-drain-cli

  go get -d code.cloudfoundry.org/loggregator-tools/log-cache-forwarders/cmd/syslog/...
  rm -rf src/code.cloudfoundry.org/loggregator-tools
  cp -r $tools src/code.cloudfoundry.org/loggregator-tools
popd

# build binaries
mkdir -p github-release/builds
output=$PWD/github-release/builds
pushd $GOPATH/src/code.cloudfoundry.org/cf-drain-cli/cmd/cf-drain-cli
  GOOS=linux go build -ldflags "-X main.version=$version" -o $output/cf-drain-cli-linux
  GOOS=darwin go build -ldflags "-X main.version=$version" -o $output/cf-drain-cli-darwin
  GOOS=windows go build -ldflags "-X main.version=$version" -o $output/cf-drain-cli-windows
popd

# build the space drain app
pushd $GOPATH/src/code.cloudfoundry.org/cf-drain-cli/cmd/space_drain
  GOOS=linux go build -o $output/space_drain
popd

# build the syslog forwarder app
pushd $GOPATH/src/code.cloudfoundry.org/cf-drain-cli
  ./scripts/build-forwarder.sh
  mv ./forwarder.zip $output/forwarder.zip
popd

pushd $cfdrain
  # add git tag
  git tag "$semver"
popd
cp -r $cfdrain output-repo/
