---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
- name: bbl-state
- name: loggregator-ci  # - This repo
- name: environment

run:
  path: loggregator-ci/tasks/env-pool-tasks/bosh-delete-all-deployments

params:
  # - Optional
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - Defaults to the root of the `bbl-state` input
  BBL_STATE_DIR:
