#!/bin/bash

set -ex

export BBL_STATE_DIR=$(cat environment/metadata)
export BBL_ENV_NAME=$(cat environment/name)
export VARS_STORE_FILE=$BBL_STATE_DIR/deployment-vars.yml

export SYSTEM_DOMAIN="$BBL_ENV_NAME.$SYSTEM_DOMAIN"

#Enable use of $BBL_STATE_DIR variable in vars files config
for v in $VARS_FILES; do
  arguments="$arguments ${v/'$BBL_STATE_DIR'/$BBL_STATE_DIR}"
done

export VARS_FILES=$arguments

./loggregator-ci/tasks/bosh-deploy/task
