---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.9.0

inputs:
- name: cf-deployment-concourse-tasks
- name: bbl-state # - The env repo containing the Director's bbl state dir
- name: loggregator-ci
- name: environment

run:
  path: loggreagor-ci/tasks/env-pool-tasks/bosh-cleanup

params:
  BBL_STATE_DIR: bbl-state
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to the `bbl-state` input
  # - If blank or '.', uses `bbl-state` input as the location for bbl state
  # - If the specified path does not exist, it will be created

  CLEAN_ALL: true
  # - Optional
  # - Boolean determines whether to use `--all` parameter to
  # - `bosh clean-up`
