---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci # - This repo
- name: cfar-logging-acceptance-tests
- name: environment
- name: bbl-state

run:
  path: loggregator-ci/tasks/env-pool-tasks/cfar-lats

params:
  # - Optional
  # - Whether to disable SSL validation.
  SKIP_SSL_VALIDATION: false

  # - Required
  SYSTEM_DOMAIN:
