#!/bin/bash

set -ex

export BBL_STATE_DIR=$(cat environment/metadata)

pushd integration-config/$BBL_STATE_DIR
  env_username=admin
  env_password=$(bosh int deployment-vars.yml --path=/cf_admin_password | head -n 1)
  env_domain=$(grep system_domain vars/bbl.tfvars | cut -d "=" -f2 | tr -d '"')
popd

cat <<EOF > integration-config/cats-config.json
{
  "api": "api.${env_domain}",
  "admin_user": "${env_username}",
  "admin_password": "${env_password}",
  "apps_domain": "${env_domain}",
  "skip_ssl_validation": true,
  "use_http": true,
  "backend": "diego",

  "include_apps": true,
  "include_backend_compatibility": true,
  "include_container_networking": true,
  "include_detect": true,
  "include_docker": true,
  "include_internet_dependent": true,
  "include_privileged_container_support": true,
  "include_route_services": true,
  "include_routing": true,
  "include_security_groups": true,
  "include_services": true,
  "include_ssh": true,
  "include_sso": true,
  "include_tasks": true,
  "include_v3": true,
  "use_log_cache": ${USE_LOG_CACHE},
  "include_windows": true,

  "include_zipkin": false,
  "include_capi_experimental": false,
  "include_credhub" : false,
  "include_isolation_segments": false,
  "include_routing_isolation_segments": false,
  "include_private_docker_registry": false,
  "include_privileged_container_support": false,
  "windows_stack": "windows2016"
}
EOF

export CONFIG_FILE_PATH=cats-config.json

./cf-deployment-concourse-tasks/run-cats/task
