#!/bin/bash

set -exu

export BBL_STATE_DIR=$(cat environment/metadata)

pushd "bbl-state/$BBL_STATE_DIR"
  eval $(bbl print-env)
  export BOSH_CA_CERT=$(bbl director-ca-cert)
popd

pushd bosh-release-dir
  if [ "$FORCE" == "true" ]; then
      bosh create-release --force --name=loggregator-backports-$(date +%s)
  else
    bosh create-release --name=loggregator-backports-$(date +%s)
  fi

  if [ "$NO_REBASE" = "true" ]; then
    bosh upload-release
  else
    bosh upload-release --rebase
  fi
popd
