#!/bin/bash

set -exu

export BBL_STATE_DIR=$(cat environment/metadata)

pushd "bbl-state/$BBL_STATE_DIR"
  eval $(bbl print-env)
  export BOSH_CA_CERT=$(bbl director-ca-cert)
popd

pushd bosh-release-dir
  if [ "$FORCE" == "true" ]; then
      bosh create-release --force --version=backports-$(date +%s)
  else
    bosh create-release --version=backports-$(date +%s)
  fi

  bosh upload-release
popd
