#!/bin/bash
set -ex

# establish version/tag strings
version="{\"Major\":$VERSION_MAJOR,\"Minor\":$VERSION_MINOR,\"Build\":$VERSION_BUILD}"
semver="v$VERSION_MAJOR.$VERSION_MINOR.$VERSION_BUILD"

# write out github release files
echo "Log Stream CLI $semver" > github-release/name
echo $semver> github-release/tag
echo "TBD" > github-release/body

# setup go path
logstream=$PWD/log-stream-cli
tools=$PWD/loggregator-tools
mkdir -p go
pushd go
  export GOPATH=$PWD

  go get -d code.cloudfoundry.org/log-stream-cli/...
  rm -rf src/code.cloudfoundry.org/log-stream-cli
  cp -r $logstream src/code.cloudfoundry.org/log-stream-cli

  go get -d code.cloudfoundry.org/loggregator-tools/log-cache-forwarders/cmd/syslog/...
  rm -rf src/code.cloudfoundry.org/loggregator-tools
  cp -r $tools src/code.cloudfoundry.org/loggregator-tools
popd

# build binaries
mkdir -p github-release/builds
output=$PWD/github-release/builds
pushd $GOPATH/src/code.cloudfoundry.org/log-stream-cli/cmd/log-stream-cli
  GOOS=linux go build -ldflags "-X main.version=$version" -o $output/log-stream-cli-linux
  GOOS=darwin go build -ldflags "-X main.version=$version" -o $output/log-stream-cli-darwin
  GOOS=windows go build -ldflags "-X main.version=$version" -o $output/log-stream-cli-windows
popd

pushd $logstream
  # add git tag
  git tag "$semver"
popd
cp -r $logstream output-repo/
