#!/bin/bash
set -ex

# establish version/tag strings
version="{\"Major\":$VERSION_MAJOR,\"Minor\":$VERSION_MINOR,\"Build\":$VERSION_BUILD}"
semver="v$VERSION_MAJOR.$VERSION_MINOR.$VERSION_BUILD"

# write out github release files
echo "Log Stream CLI $semver" > github-release/name
echo $semver> github-release/tag
echo "TBD" > github-release/body

# setup go path
logstream=$PWD/log-stream-cli
mkdir -p go
pushd go
  export GOPATH=$PWD
popd

# build binaries
mkdir -p github-release/builds
output=$PWD/github-release/builds
pushd $logstream/cmd/log-stream-cli
  GOOS=linux go build -ldflags "-X main.version=$version" -o $output/log-stream-cli-linux
  GOOS=darwin go build -ldflags "-X main.version=$version" -o $output/log-stream-cli-darwin
  GOOS=windows go build -ldflags "-X main.version=$version" -o $output/log-stream-cli-windows
popd

pushd $logstream
  # add git tag
  git tag "$semver"
popd
cp -r $logstream output-repo/
