#!/bin/bash
set -e

pushd bbl-state/$BBL_STATE_DIR
    eval "$(bbl print-env)"
    export BOSH_CA_CERT=$(bbl director-ca-cert)
popd

export USERNAME=admin
export PASSWORD=$(credhub get --name=$(credhub find | grep cf_admin | awk '{print $3}') --output-json | jq -r .value)

IMPORT_PATH=code.cloudfoundry.org/cf-drain-cli

mkdir -p "workspace/src/$IMPORT_PATH"
cp -r cf-drain-cli/. "workspace/src/$IMPORT_PATH"

pushd workspace
    export GOPATH="$PWD"
    export PATH="$GOPATH/bin:$PATH"

    go get code.cloudfoundry.org/cf-drain-cli/cmd/cf-drain-cli
    cf install-plugin $GOPATH/bin/cf-drain-cli -f
popd


IMPORT_PATH=github.com/loggregator/logging-deployment

mkdir -p "workspace/src/$IMPORT_PATH"
cp -r logging-deployment/. "workspace/src/$IMPORT_PATH"

pushd $GOPATH/src/$IMPORT_PATH/ci/assets/logging-telemetry
    go get ./...
    go build
popd

pushd $GOPATH/src/$IMPORT_PATH/ci/assets/logging-telemetry-scaled-deployer
    go get ./...
    go build

    export SCRIPT_COMMAND=$GOPATH/src/$IMPORT_PATH/ci/assets/logging-telemetry/deploy.sh
    export SCRIPT_COMMAND_DIR=$GOPATH/src/$IMPORT_PATH/ci/assets/logging-telemetry/
    export API_ENDPOINT="api.$SYSTEM_DOMAIN"

    ./logging-telemetry-scaled-deployer
popd
