---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks
    tag: v5.26.0

inputs:
- name: bbl-state
- name: loggregator-ci
- name: loggregator-tools
- name: cf-drain-cli        # - The repo that contains the cf drains plugin

run:
  path: loggregator-ci/tasks/push-many-logging-telemetry/task

params:
  # - Optional
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - Defaults to the root of the `bbl-state` input
  BBL_STATE_DIR:

  # - Optional
  # - How often will app initiate test.
  EMIT_INTERVAL: 1ms

  # - Required
  # - The CF org
  ORG:

  # - Required
  # - The CF system domain
  SYSTEM_DOMAIN:

  # - Required
  # - The prefix to prepend to all the spaces. Space names will be
  # - `SPACE_PREFIX-#`.
  SPACE_PREFIX:

  # - Required
  # - The ID of the space to start deploying apps to.
  SPACE_ID_START:

  # - Required
  # - The ID of the space to end deploying apps to.
  SPACE_ID_END:

  # - Required
  # - The number of apps to create per space.
  APP_COUNT: 200

  # - Optional
  # - Skip SSL validation when logging into CF.
  SKIP_SSL_VALIDATION: false

  # - Optional
  # - Suffix for scheme on drain URL.
  SCHEME_SUFFIX: ""

  # - Optional
  # - The number of drains to create.
  DRAIN_COUNT:

  # - Required
  # - The list of drain destination IPs to rotate through for load balancing
  DRAIN_IPS:
