#!/bin/bash
set -eux

set +eux
export TRACKER_API_TOKEN=${TRACKER_API_TOKEN}
set -eux

workspace=$(pwd)

bump_sha=""
pushd source
    git remote set-url origin $(git remote -v | grep fetch | awk '{print $2}' | sed 's|git@github.com:|https://github.com/|g')
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git fetch origin
    git checkout ${DEST_BRANCH}

    bumper --commit-range ${DEST_BRANCH}..${SOURCE_BRANCH} --verbose
    bump_sha=$(bumper --commit-range ${DEST_BRANCH}..${SOURCE_BRANCH})
popd

if [ -z $bump_sha ]; then
    echo "There are no commits to bump!"
    cp -R dest/. merged-dest

    exit 0
fi

pushd dest
    git remote set-url origin $(git remote -v | grep fetch | awk '{print $2}' | sed 's|git@github.com:|https://github.com/|g')
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git fetch origin
popd

cp -R dest/. merged-dest

pushd merged-dest
    git checkout ${SOURCE_BRANCH}
    git checkout ${DEST_BRANCH}
    git merge $bump_sha --ff-only
popd
