platform: linux

image_resource:
  type: docker-image
  source:
    repository: loggregator/base

inputs:
- name: loggregator-ci # - This repo
- name: source         # - The source repo to bump
- name: dest           # - The destination repo to bump

outputs:
- name: merged-dest # - The merged destination repo

run:
  path: loggregator-ci/tasks/bumper/task

params:
  # - Required
  # - The source branch to bump from.
  SOURCE_BRANCH:

  # - Required
  # - The destination branch to bump to.
  DEST_BRANCH:

  # - Optional
  # - Submodules for bumper to follow bumps of.
  # - Relative to dest.
  FOLLOW_BUMPS_OF:
