#!/bin/bash
set -eux

workspace=$(pwd)
pushd bumper-tool
    go build -o $workspace/bumper/bumper
popd

bump_sha=""
pushd source
    git remote set-url origin $(git remote -v | grep fetch | awk '{print $2}' | sed 's|git@github.com:|https://github.com/|g')
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git fetch origin
    git checkout ${DEST_BRANCH}

    $workspace/bumper/bumper --commit-range ${SOURCE_BRANCH}..${DEST_BRANCH} --verbose
    bumper_sha=$($workspace/bumper/bumper --commit-range ${SOURCE_BRANCH}..${DEST_BRANCH})
popd

if [ -z $bump_sha ]; then
    echo "There are no commits to bump!"
    exit 0
fi

pushd dest
    git remote set-url origin $(git remote -v | grep fetch | awk '{print $2}' | sed 's|git@github.com:|https://github.com/|g')
    git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    git fetch origin
popd

cp -R dest/. merged-dest

pushd merged-dest
    git checkout ${SOURCE_BRANCH}
    git checkout ${DEST_BRANCH}
    git merge $bump_sha --ff-only
popd
